/**
 * related-names.data.ts -- the built-in related-name library (Deterministic
 * Semantic Relationship Knowledge, 2026-07-30). GENERATED from Andrew's
 * canonical `related_names_scored.csv` (2,708 curated relationships,
 * manually assigned ordinal strengths 1-5) -- this file is APPLICATION
 * DATA, not code: the CSV text below is embedded VERBATIM and parsed/
 * validated at startup by RelatedNameProvider.ts's loader, exactly as if
 * it were read from disk.
 *
 * WHY embedded rather than fetched: this repo deliberately has no bundler
 * and the browser serves plain-tsc output (see README.md's environment
 * constraints); a runtime fetch() would add an async failure path to the
 * startup pipeline and be invisible to the Node verification harness. The
 * embed keeps the dataset deterministic, local-only, loaded at startup,
 * and Node-testable -- while remaining EASILY REPLACEABLE: to ship a new
 * dataset, regenerate this file from the new CSV (paste the text between
 * the backticks, bump RELATED_NAMES_DATASET_VERSION) -- no architectural
 * change, per the prompt's requirement. This follows the repo's
 * established .data.ts convention (quality-dictionaries.data.ts,
 * category-rule-labels.data.ts).
 */

export const RELATED_NAMES_DATASET_VERSION = "related_names_scored.csv (2026-07-30, 2708 rows)";

export const RELATED_NAMES_CSV = `full_name,related_name,score
aaron,erin,1
aaron,ron,4
aaron,ronnie,4
abbigail,abbe,2
abbigail,abbey,3
abbigail,abbi,4
abbigail,abbie,4
abbigail,abby,3
abbigail,gail,4
abbigail,nabby,2
abbigale,abbe,3
abbigale,abbey,4
abbigale,abbi,4
abbigale,abbie,4
abbigale,abby,3
abbigale,gail,2
abbigale,nabby,2
abednego,bedney,3
abel,ab,4
abel,abe,4
abel,eb,3
abel,ebbie,3
abiel,ab,4
abigail,abbe,2
abigail,abbey,2
abigail,abbi,2
abigail,abbie,2
abigail,abby,5
abigail,gail,5
abigail,nabby,3
abigale,abbe,2
abigale,abbey,2
abigale,abbi,2
abigale,abbie,3
abigale,abby,2
abigale,gail,2
abigale,nabby,2
abijah,ab,2
abijah,bige,2
abner,ab,4
abraham,ab,3
abraham,abe,3
abram,ab,4
abram,abe,2
absalom,ab,2
absalom,abbie,2
absalom,app,1
ada,addy,2
ada,adie,3
adaline,ada,4
adaline,addy,3
adaline,adie,4
adaline,delia,3
adaline,dell,3
adaline,lena,3
addison,addie,4
addison,addy,3
adela,adie,4
adela,della,4
adelaide,addy,3
adelaide,adele,4
adelaide,adie,3
adelaide,dell,3
adelaide,della,4
adelaide,heidi,3
adelbert,albert,4
adelbert,bert,4
adelbert,del,4
adelbert,delbert,4
adele,addy,2
adele,dell,3
adeline,ada,3
adeline,addy,3
adeline,delia,4
adeline,dell,4
adeline,lena,3
adelphia,addy,3
adelphia,adele,4
adelphia,dell,3
adelphia,delphia,4
adelphia,philly,3
adena,adina,4
adena,deena,4
adena,dena,4
adena,dina,3
adolphus,ado,4
adolphus,adolph,4
adolphus,dolph,4
adrian,rian,4
adriane,riane,4
adrienne,addie,3
adrienne,enne,4
adrienne,rienne,4
agatha,aga,4
agatha,aggy,3
agnes,aggy,3
agnes,inez,3
agnes,nessa,4
aileen,allie,4
aileen,lena,4
alan,al,4
alanson,al,2
alanson,lanson,4
alastair,al,2
alazama,ali,2
albert,al,3
albert,bert,4
alberta,allie,3
alberta,bert,4
alberta,bertie,4
aldo,al,4
aldrich,rich,4
aldrich,riche,4
aldrich,richie,3
aleksandr,alek,4
aleksandr,alex,2
aleva,leve,3
aleva,levy,3
alex,al,3
alexander,al,3
alexander,alec,2
alexander,alex,5
alexander,sandy,5
alexandra,alex,5
alexandra,alla,3
alexandra,sandra,4
alexandra,sandy,5
alexandria,alex,3
alexandria,alexander,4
alexandria,alla,2
alexandria,drina,2
alexandria,sandra,3
alexis,alex,4
alexis,lexi,4
alfonse,al,3
alfred,al,3
alfred,fred,4
alfred,freddy,4
alfreda,alfy,4
alfreda,freda,4
alfreda,freddy,4
alfreda,frieda,4
algernon,algy,3
alice,allie,4
alice,elsie,4
alice,lisa,3
alicia,allie,4
alicia,elsie,3
alicia,lisa,4
aline,adeline,4
alison,ali,4
alison,allie,2
alixandra,alix,4
allan,al,4
allan,alan,4
allan,allen,4
allen,al,4
allen,alan,3
allen,allan,4
allisandra,ali,2
allisandra,allie,4
allisandra,ally,3
allison,ali,3
allison,allie,4
allison,ally,3
allyson,ali,2
allyson,allie,3
allyson,ally,4
allyssa,ali,2
allyssa,allie,3
allyssa,ally,4
almena,ali,2
almena,allie,4
almena,ally,2
almena,mena,4
almina,minnie,2
almira,myra,3
alonzo,al,3
alonzo,lon,4
alonzo,lonzo,4
alphinias,alphus,3
althea,ally,2
alverta,vert,4
alverta,virdie,2
alyssa,al,2
alyssa,ally,3
alyssa,lissia,3
alzada,zada,4
amanda,manda,4
amanda,mandy,5
ambrose,brose,4
amelia,amy,4
amelia,emily,3
amelia,mel,4
amelia,millie,3
amos,moses,3
anastasia,ana,2
anastasia,stacy,2
anderson,andy,4
andre,drea,3
andrea,andi,3
andrea,andrew,4
andrea,andy,4
andrea,drea,4
andrea,rea,4
andrew,andy,5
andrew,drew,5
andrew,randy,1
andriane,ada,2
andriane,adri,3
andriane,rienne,2
angela,angel,4
angela,angie,4
angelica,angel,4
angelica,angelika,4
angelica,angelique,3
angelica,angie,4
angelina,angel,4
angelina,angie,4
angelina,lina,4
ann,annie,4
ann,nan,4
ann,nana,3
ann,nancy,2
ann,nanny,4
anna,ann,4
anna,anne,4
anna,annie,5
anna,nan,2
anne,ann,4
anne,annie,5
anne,nan,4
anne,nana,2
anne,nancy,2
anne,nanny,3
annette,anna,2
annette,nettie,4
annie,ann,4
annie,anna,3
anselm,ance,3
anselm,anse,4
anselm,ansel,4
anselm,selma,4
anthony,ant,5
anthony,tony,5
antoinette,ann,3
antoinette,netta,4
antoinette,tony,3
antonia,ann,4
antonia,netta,3
antonia,tony,4
antonio,ant,4
antonio,tony,2
appoline,appie,4
appoline,appy,3
aquilla,quil,4
aquilla,quillie,3
ara,arry,2
ara,belle,1
arabella,ara,4
arabella,arry,3
arabella,bella,4
arabella,belle,4
arabelle,ara,4
arabelle,arry,3
arabelle,bella,4
arabelle,belle,4
araminta,armida,3
araminta,middie,1
araminta,minty,3
araminta,ruminta,4
archibald,archie,4
archilles,kill,2
archilles,killis,2
ariadne,ari,4
ariadne,arie,4
arielle,arie,4
aristotle,telly,1
arizona,ona,4
arizona,onie,2
arlene,arly,4
arlene,lena,4
armanda,mandy,3
armena,arry,3
armena,mena,4
armilda,milly,2
arminda,mindie,3
arminta,minite,3
arminta,minnie,2
arnold,arnie,3
aron,erin,2
aron,ron,4
aron,ronnie,3
artelepsa,epsey,2
artemus,art,4
arthur,art,4
arthusa,thursa,4
arzada,zaddi,2
asahel,asa,4
asaph,asa,4
asenath,assene,4
asenath,natty,3
asenath,sene,4
ashley,ash,4
ashley,ashly,4
ashley,leah,2
ashley,lee,2
aubrey,bree,3
audrey,audree,4
audrey,dee,2
august,gus,4
augusta,aggy,3
augusta,gatsy,3
augusta,gussie,3
augusta,tina,3
augustina,aggy,3
augustina,gatsy,3
augustina,gussie,4
augustina,tina,4
augustine,august,4
augustine,austin,4
augustine,gus,3
augustus,august,4
augustus,austin,4
augustus,gus,4
aurelia,aurilla,3
aurelia,ora,1
aurelia,orilla,1
aurelia,ree,2
aurelia,rilly,2
avarilla,rilla,4
azariah,aze,3
azariah,riah,4
bab,barby,4
babs,bab,4
babs,barbara,2
babs,barby,3
barbara,bab,4
barbara,babs,4
barbara,barbie,5
barbara,barby,4
barbara,bobbie,3
barbery,barbara,3
barbie,barbara,3
barnabas,barney,4
barney,barnabas,2
bart,bartholomew,3
bartholomew,bart,4
bartholomew,bartel,4
bartholomew,bat,3
bartholomew,mees,3
bartholomew,meus,3
barticus,bart,4
bazaleel,basil,2
bea,beatrice,4
beatrice,bea,5
beatrice,trisha,3
beatrice,trix,3
beatrice,trixie,5
becca,beck,3
beck,becky,4
bedelia,bridgit,2
bedelia,delia,4
belinda,belle,3
belinda,linda,4
bella,arabella,4
bella,belle,4
bella,isabella,4
benedict,ben,4
benedict,bennie,4
benjamin,ben,5
benjamin,benjy,4
benjamin,bennie,4
benjamin,benny,5
benjamin,jamie,4
benjy,benjamin,3
bernard,barney,3
bernard,berney,4
bernard,bernie,4
bernard,berny,4
berney,bernie,4
bert,bertie,4
bert,bob,1
bert,bobby,1
bertha,bert,4
bertha,bertie,4
bertha,birdie,3
bertram,bert,4
bertrand,randy,3
bess,bessie,4
beth,betsy,3
beth,betty,3
beth,elizabeth,4
bethena,beth,4
bethena,thaney,2
beverly,bev,4
bezaleel,zeely,3
biddie,biddy,4
bill,billy,4
bill,fred,3
bill,robert,1
bill,william,2
bill,willie,3
billy,fred,3
billy,robert,1
billy,william,2
blanche,bea,2
bob,rob,3
bob,robert,2
bobby,bob,4
bobby,rob,2
boetius,bo,2
brad,bradford,4
brad,ford,2
bradford,brad,4
bradford,ford,4
bradley,brad,4
brady,brody,4
breanna,bree,2
breanna,bri,2
breeanna,bree,4
brenda,brandy,3
brian,bryan,4
brian,bryant,4
brianna,bri,4
bridget,biddie,4
bridget,biddy,3
bridget,bridgie,4
bridget,bridie,4
brittany,britt,4
brittany,brittnie,4
brittney,britt,4
brittney,brittnie,4
broderick,brady,3
broderick,brody,4
broderick,rick,4
broderick,ricky,4
broderick,rod,2
bryanna,ana,3
bryanna,anna,4
bryanna,bri,2
bryanna,briana,4
bryanna,brianna,4
caitlin,cait,4
caitlin,caity,4
caitlyn,cait,4
caitlyn,caity,4
caldonia,calliedona,4
caleb,cal,4
california,callie,2
calista,kissy,2
calpurnia,cally,2
calvin,cal,4
calvin,vin,4
calvin,vinny,4
cameron,cam,4
cameron,ron,4
cameron,ronny,3
camile,cammie,4
camille,cammie,4
camille,millie,4
campbell,cam,4
candace,candy,4
candace,dacey,3
carla,carly,4
carla,karla,4
carlotta,lottie,2
carlton,carl,4
carmellia,mellia,4
carmelo,melo,4
carmon,cammie,2
carmon,carm,4
carmon,charm,4
carol,carolann,4
carol,carole,4
carol,caroline,4
carol,carri,3
carol,carrie,4
carol,cassie,3
carol,kara,2
carol,kari,2
carol,lynn,3
carolann,carol,4
carolann,carole,4
caroline,carol,4
caroline,carole,4
caroline,carrie,4
caroline,cassie,4
caroline,lynn,3
carolyn,carrie,3
carolyn,cassie,3
carolyn,lynn,4
carrie,cassie,3
carthaette,etta,2
carthaette,etty,2
casey,k.c.,3
casper,jasper,4
cassandra,cassie,4
cassandra,sandra,4
cassandra,sandy,4
cassidy,cass,4
cassidy,cassie,4
caswell,cass,2
catherine,casey,2
catherine,cassie,3
catherine,cathy,5
catherine,kathy,3
catherine,katy,3
catherine,kay,3
catherine,kit,3
catherine,kittie,3
catherine,lena,3
catherine,trina,4
cathleen,casey,2
cathleen,cassie,3
cathleen,cathy,4
cathleen,kathy,3
cathleen,katy,3
cathleen,kay,3
cathleen,kit,3
cathleen,kittie,3
cathleen,lena,3
cathleen,trina,3
cathy,catherine,2
cathy,cathleen,3
cathy,kathy,4
cecilia,celia,4
cecilia,cissy,3
cedric,ced,4
cedric,rick,4
cedric,ricky,4
celeste,celia,2
celeste,lessie,3
celinda,linda,4
celinda,lindy,3
celinda,lynn,2
charity,chat,4
charles,carl,4
charles,charlie,5
charles,chick,3
charles,chuck,5
charlie,charles,4
charlie,chuck,2
charlotte,char,4
charlotte,lotta,4
charlotte,lottie,5
charlotte,sherry,3
chauncey,chan,4
chelsey,chelsie,4
cheryl,cher,4
chesley,chet,2
chester,chet,4
chet,chester,4
chick,caroline,2
chick,charlotte,1
chick,chuck,4
chloe,clo,4
chris,kris,3
christa,chris,4
christian,chris,4
christian,kit,3
christiana,ann,3
christiana,chris,4
christiana,christy,4
christiana,crissy,3
christiana,kris,3
christiana,kristy,3
christiana,tina,4
christiano,chris,4
christina,chris,4
christina,chrissy,3
christina,christy,4
christina,crissy,4
christina,kris,3
christina,kristy,4
christina,tina,5
christine,chris,5
christine,chrissy,5
christine,christy,4
christine,crissy,4
christine,kris,3
christine,kristy,4
christine,tina,3
christoffer,chris,3
christoph,chris,4
christopher,chris,5
christopher,kit,3
christy,crissy,4
cicely,cilla,2
cinderella,arilla,2
cinderella,cindy,3
cinderella,rella,4
cinderella,rilla,2
cindy,cinderella,2
claire,clair,4
claire,clara,4
claire,clare,4
clara,clarissa,4
clare,clara,4
clarence,clair,4
clarence,clare,4
clarinda,clara,4
clarissa,cissy,4
clarissa,clara,4
claudia,claud,4
cleatus,cleat,4
clement,clem,4
clementine,clem,3
clementine,clement,4
cliff,clifford,4
clifford,cliff,4
clifford,ford,4
clifton,cliff,4
clifton,tony,4
cole,colie,4
columbus,clum,4
con,conny,4
conrad,con,4
conrad,conny,4
constance,connie,4
cordelia,cordy,4
cordelia,delia,4
corey,coco,2
corey,cordy,4
corey,ree,2
corinne,cora,2
corinne,ora,2
cornelia,cornie,4
cornelia,corny,4
cornelia,nelia,4
cornelia,nelle,3
cornelia,nelly,3
cornelius,con,3
cornelius,conny,3
cornelius,corny,4
cornelius,neil,2
cornelius,niel,3
cory,coco,2
cory,cordy,4
cory,ree,1
courtney,court,4
courtney,curt,4
crystal,chris,2
crystal,crys,4
crystal,stal,4
crystal,tal,4
curtis,curt,4
cynthia,cindy,3
cynthia,cintha,4
cyrenius,cene,3
cyrenius,cy,3
cyrenius,renius,4
cyrenius,serene,3
cyrenius,swene,3
cyrus,cy,2
dahl,dal,4
dal,dahl,4
dalton,dahl,4
dalton,dal,4
daniel,dan,5
daniel,dann,3
daniel,danny,5
danielle,dani,5
danielle,ellie,3
danny,daniel,2
daphne,daph,4
daphne,daphie,4
darlene,darry,3
darlene,lena,4
david,dave,5
david,davey,5
david,day,4
daycia,dacia,4
daycia,daisha,3
deanne,ann,4
deanne,dee,3
debbie,deb,4
debbie,debby,4
debbie,deborah,2
debbie,debra,2
debby,deb,4
debora,deb,4
debora,debbie,3
debora,debby,4
deborah,deb,5
deborah,debbie,5
deborah,debby,3
debra,deb,4
debra,debbie,4
deidre,deedee,3
delbert,bert,4
delbert,del,4
delia,cordelia,4
delia,delius,4
delia,fidelia,4
delilah,dell,4
delilah,della,4
delilah,lil,4
delilah,lila,4
deliverance,della,3
deliverance,delly,3
deliverance,dilly,3
della,adela,4
della,adelaide,3
della,delilah,4
della,dell,4
delores,dee,4
delores,dell,4
delores,della,3
delores,lola,3
delores,lolly,3
delpha,philadelphia,3
delphine,del,4
delphine,delf,2
delphine,delphi,4
demaris,dea,3
demaris,maris,4
demaris,mary,2
demerias,dea,2
demerias,maris,3
demerias,mary,2
democrates,mock,2
dennis,dennie,4
dennis,denny,4
dennison,dennis,4
dennison,denny,4
derek,derrek,4
derek,rick,2
derek,ricky,2
derick,rick,4
derick,ricky,4
derrick,eric,4
derrick,rick,4
derrick,ricky,4
deuteronomy,duty,2
diana,di,2
diana,dicey,2
diana,didi,2
diane,di,2
diane,dian,4
diane,dianne,4
diane,dicey,3
diane,didi,2
dicey,dicie,4
dick,richard,2
dick,rick,4
dickson,dick,4
domenic,dom,4
domenic,nic,4
dominic,dom,4
dominic,nic,4
dominick,dom,4
dominick,nick,4
dominick,nicky,3
dominico,dom,4
donald,don,5
donald,donnie,5
donald,donny,4
donald,dony,4
donato,don,4
donna,dona,4
donovan,don,4
donovan,donnie,3
donovan,donny,3
donovan,dony,3
dorcus,darkey,3
dorinda,dora,4
dorinda,dorothea,2
doris,dora,3
dorothea,doda,2
dorothea,dora,3
dorothy,dolly,5
dorothy,dora,2
dorothy,dortha,4
dorothy,dot,5
dorothy,dottie,5
dorothy,dotty,4
dotha,dotty,3
dotty,dot,4
douglas,doug,4
drusilla,silla,4
duncan,dunk,3
earnest,ernestine,4
earnest,ernie,3
ebbie,eb,2
ebenezer,eb,3
ebenezer,ebbie,3
ebenezer,eben,4
eddie,ed,2
eddy,ed,3
edgar,ed,4
edgar,eddie,3
edgar,eddy,3
edith,edie,4
edith,edye,3
edmond,ed,3
edmond,eddie,4
edmond,eddy,4
edmund,ed,3
edmund,eddie,4
edmund,eddy,4
edmund,ned,3
edmund,ted,3
edna,edny,4
eduardo,ed,3
eduardo,eddie,3
eduardo,eddy,4
edward,ed,5
edward,eddie,5
edward,eddy,4
edward,ned,5
edward,ted,5
edward,teddy,5
edwin,ed,4
edwin,eddie,4
edwin,eddy,3
edwin,ned,3
edwin,win,4
edwina,edwin,4
edyth,edie,4
edyth,edye,4
edythe,edie,4
edythe,edye,4
egbert,bert,4
egbert,burt,3
eighta,athy,1
eileen,helen,4
elaine,helen,2
elaine,lainie,4
elbert,albert,4
elbert,bert,4
elbertson,bert,4
elbertson,elbert,4
eldora,dora,4
eleanor,elaine,3
eleanor,ellen,4
eleanor,ellie,5
eleanor,lanna,3
eleanor,lenora,4
eleanor,nelly,3
eleanor,nora,5
eleazer,lazar,4
elena,helen,4
elias,eli,4
elias,lee,3
elias,lias,4
elijah,eli,4
elijah,lige,3
eliphalel,life,2
eliphalet,left,3
elisa,lisa,4
elisha,eli,4
elisha,lish,4
eliza,elizabeth,4
elizabeth,bess,3
elizabeth,bessie,3
elizabeth,beth,5
elizabeth,betsy,5
elizabeth,betty,5
elizabeth,eliza,5
elizabeth,lib,3
elizabeth,libby,3
elizabeth,lisa,3
elizabeth,liz,5
elizabeth,liza,4
elizabeth,lizzie,5
elizabeth,lizzy,2
ella,el,3
ella,ellen,3
ellen,helen,4
ellen,nell,3
ellen,nellie,4
ellender,ellen,4
ellender,helen,3
ellender,nellie,2
ellie,elly,4
ellswood,elsey,3
elminie,minnie,4
elmira,ellie,4
elmira,elly,3
elmira,mira,4
elnora,nora,4
eloise,heloise,4
eloise,louise,4
elouise,louise,4
elsie,elsey,4
elswood,elsey,4
elvira,elvie,4
elwood,woody,4
elysia,lisa,3
elysia,lissa,2
elze,elsey,4
emanuel,manny,3
emanuel,manuel,4
emeline,em,3
emeline,emily,3
emeline,emma,3
emeline,emmy,3
emeline,milly,3
emil,em,3
emil,emily,4
emily,em,2
emily,emma,3
emily,emmy,4
emily,mel,2
emily,millie,4
emma,em,3
emma,emmy,4
epaphroditius,dite,3
epaphroditius,ditus,4
epaphroditius,dyce,3
epaphroditius,dyche,3
epaphroditius,eppa,3
ephraim,eph,4
erasmus,rasmus,4
erasmus,raze,2
eric,rick,4
eric,ricky,4
ernest,ernie,4
ernestine,erna,2
ernestine,ernest,4
ernestine,teeny,1
ernestine,tina,2
erwin,irwin,4
eseneth,senie,3
essy,es,3
estella,essy,3
estella,stella,4
estelle,essy,3
estelle,stella,4
esther,essie,2
esther,hester,4
eudicy,dicey,4
eudora,dora,4
eudoris,dosie,2
eudoris,dossie,2
eugene,gene,4
eunice,nicie,4
euphemia,effie,2
euphemia,effy,1
eurydice,dicey,3
eustacia,stacia,4
eustacia,stacy,3
eva,eve,3
evaline,eva,4
evaline,eve,4
evaline,lena,3
evangeline,ev,2
evangeline,evan,3
evangeline,vangie,3
evelyn,ev,2
evelyn,eve,4
evelyn,evelina,4
experience,exie,3
ezekiel,ez,3
ezekiel,zeke,4
ezideen,ez,2
ezra,ez,4
faith,fay,4
fallon,fal,4
fallon,falcon,4
fallon,fall,4
fallon,fallie,4
fallon,fally,4
fallon,falon,4
fallon,lon,4
fallon,lonnie,2
felicia,fel,4
felicia,feli,4
felicia,felix,3
felicity,flick,3
felicity,tick,2
feltie,felty,4
ferdinand,ferdie,4
ferdinand,fred,3
ferdinand,freddie,3
ferdinand,freddy,4
ferdinando,ferdie,4
ferdinando,fred,2
ferdinando,nando,4
fidelia,delia,4
fionna,fiona,4
flora,florence,3
florence,flo,5
florence,flora,4
florence,flossy,3
floyd,lloyd,4
fran,frannie,4
frances,cissy,3
frances,fanny,3
frances,fran,5
frances,francie,4
frances,frankie,5
frances,frannie,4
frances,franniey,4
frances,franny,3
frances,sis,3
francie,francine,4
francine,fran,4
francine,francie,4
francine,frannie,4
francine,franniey,4
francine,franny,3
francis,fran,4
francis,frank,4
francis,frankie,4
frankie,francis,3
frankie,frank,4
franklin,fran,4
franklin,frank,4
franklind,fran,4
franklind,frank,4
freda,frieda,4
frederica,erica,4
frederica,erika,2
frederica,freddy,2
frederica,frederick,4
frederica,rickey,2
frederick,derick,4
frederick,erick,4
frederick,fred,5
frederick,freddie,5
frederick,freddy,4
frederick,fritz,3
frederick,rick,4
frederick,ricky,2
fredericka,ericka,4
fredericka,freda,4
fredericka,freddy,3
fredericka,frieda,4
fredericka,ricka,4
fredericka,rickey,2
frieda,fred,4
frieda,freddie,4
frieda,freddy,4
gabriel,gabby,3
gabriel,gabe,4
gabriella,ella,4
gabriella,gabby,5
gabrielle,ella,3
gabrielle,gabby,5
gareth,gare,4
gareth,gary,4
garrett,barrett,4
garrett,gare,4
garrett,garratt,4
garrett,garret,4
garrett,garry,4
garrett,gary,3
garrett,jerry,2
garrett,rhett,3
garrick,garri,4
genevieve,eve,3
genevieve,jean,3
genevieve,jenny,3
geoffrey,geoff,4
geoffrey,jeff,3
george,georgie,5
georgiana,georgia,4
georgine,george,4
gerald,gerry,5
gerald,jerry,5
geraldine,dina,3
geraldine,gerri,2
geraldine,gerrie,4
geraldine,gerry,3
geraldine,jerry,3
gerhardt,gay,2
gertie,gert,4
gertie,gertrude,3
gertrude,gert,4
gertrude,gertie,4
gertrude,trudy,4
gilbert,bert,4
gilbert,gil,4
gilbert,wilber,4
giovanni,gio,4
glenn,glen,4
gloria,glory,4
governor,govie,4
greenberry,berry,4
greenberry,green,4
greggory,gregg,4
gregory,gory,4
gregory,greg,5
gretchen,margaret,2
griselda,grissel,4
gum,monty,1
gus,gussie,4
gustavus,gus,4
gustavus,gussie,2
gwen,wendy,3
gwendolyn,gwen,5
gwendolyn,wendy,4
hailey,haylee,3
hailey,hayley,4
hamilton,ham,4
hannah,anna,4
hannah,nan,3
hannah,nanny,4
harold,hal,4
harold,hap,2
harold,haps,2
harold,harry,4
harriet,hattie,5
harrison,hap,2
harrison,haps,2
harrison,harry,4
harry,hap,2
harry,haps,2
harry,harold,2
harry,henry,3
haseltine,hassie,2
haylee,hailey,3
haylee,hayley,4
hayley,hailey,4
hayley,haylee,4
heather,hetty,2
helen,ella,3
helen,ellen,4
helen,ellie,4
helen,lena,4
helena,aileen,2
helena,eileen,3
helena,elaine,2
helena,eleanor,3
helena,ellen,4
helena,lena,4
helena,nell,2
helena,nellie,2
helene,ella,3
helene,ellen,4
helene,ellie,4
helene,lena,4
heloise,eloise,4
heloise,elouise,4
heloise,lois,4
henrietta,etta,4
henrietta,etty,3
henrietta,hank,3
henrietta,henny,2
henrietta,nettie,4
henrietta,retta,4
henry,hal,3
henry,hank,5
henry,hap,1
henry,haps,1
henry,harry,5
hephsibah,hipsie,4
hepsibah,hipsie,4
herbert,bert,4
herbert,herb,4
herman,dutch,1
herman,harman,4
hermione,hermie,4
hester,esther,4
hester,hessy,4
hester,hetty,4
hezekiah,hez,4
hezekiah,hy,3
hezekiah,kiah,4
hillary,hilary,4
hipsbibah,hipsie,4
hiram,hy,3
honora,honey,3
honora,nora,4
honora,norah,4
honora,norry,2
hopkins,hop,4
hopkins,hopp,4
horace,horry,4
hortense,harty,2
hortense,tensey,3
hosea,hosey,4
hosea,hosie,4
howard,hal,2
howard,howie,3
hubert,bert,4
hubert,hub,4
hubert,hugh,3
ian,john,1
ignatius,iggy,3
ignatius,nace,3
ignatius,nate,3
ignatius,natius,4
ignatzio,iggy,2
ignatzio,nace,2
ignatzio,naz,2
immanuel,emmanuel,4
immanuel,manuel,4
india,indie,4
india,indy,4
inez,agnes,2
iona,onnie,2
irene,rena,4
irvin,irving,4
irving,irv,4
irwin,erwin,4
isaac,ike,3
isaac,zeke,3
isabel,bell,4
isabel,bella,4
isabel,belle,4
isabel,ib,3
isabel,issy,3
isabel,nib,3
isabel,nibby,3
isabel,tibbie,3
isabella,bella,5
isabella,belle,4
isabella,ib,3
isabella,issy,3
isabella,nib,3
isabella,nibby,3
isabella,tibbie,3
isabelle,bella,4
isabelle,belle,4
isabelle,ib,3
isabelle,issy,3
isabelle,nib,3
isabelle,nibby,3
isabelle,tibbie,3
isadora,dora,4
isadora,issy,3
isadore,izzy,1
isaiah,zadie,1
isaiah,zay,1
isidore,izzy,3
iva,ivy,4
ivan,john,1
jackson,jack,4
jacob,jaap,3
jacob,jake,3
jacob,jay,4
jacobus,jacob,4
jacqueline,jack,2
jacqueline,jackie,5
jacqueline,jacqui,4
jahoda,hoda,4
jahoda,hodie,2
jahoda,hody,3
jakob,jake,3
jalen,al,2
jalen,alen,4
jalen,haylen,4
jalen,jaelin,4
jalen,jaelyn,4
jalen,jailyn,4
jalen,jay,3
jalen,jaye,3
jalen,jaylin,4
jalen,jaylyn,4
jalen,len,4
jalen,lennie,2
jalen,lenny,3
james,jamie,4
james,jem,3
james,jim,5
james,jimmie,4
james,jimmy,5
jamey,james,4
jamey,jamie,4
jamie,james,4
jane,janie,4
jane,jean,4
jane,jennie,4
jane,jessie,3
janet,jan,4
janet,jessie,3
janice,jan,4
jannett,nettie,3
jasper,casper,4
jasper,jap,3
jayme,jay,4
jean,jane,4
jean,jeannie,4
jeanette,janet,4
jeanette,jean,4
jeanette,jessie,3
jeanette,nettie,4
jeanne,jane,4
jeanne,jeannie,4
jebadiah,jeb,4
jedediah,diah,4
jedediah,dyer,1
jedediah,jed,4
jedidiah,diah,4
jedidiah,dyer,1
jedidiah,jed,4
jefferey,jeff,4
jefferson,jeff,4
jefferson,sonny,3
jeffery,jeff,4
jeffrey,geoff,3
jeffrey,jeff,4
jehiel,hiel,4
jehu,gee,1
jehu,hugh,2
jemima,mima,4
jennet,jenn,4
jennet,jenny,4
jennet,jessie,2
jennifer,jen,5
jennifer,jenn,4
jennifer,jenni,4
jennifer,jennie,4
jennifer,jenny,5
jeremiah,jereme,4
jeremiah,jerry,3
jeremy,jez,2
jeremy,jezza,2
jerita,rita,4
jerry,geraldine,1
jerry,geri,2
jerry,gerry,4
jerry,jereme,2
jessica,jess,5
jessica,jessie,5
jessie,jane,2
jessie,janet,2
jessie,jess,4
jillian,jill,4
jim,jimmie,4
jincy,jane,2
jinsy,jane,2
joan,jo,4
joan,nonie,3
joann,jo,4
joanna,hannah,4
joanna,jo,3
joanna,joan,4
joanna,jodi,2
joanna,jody,3
joanne,jo,3
jody,jo,3
joe,joey,4
johann,john,4
johanna,jo,3
johannah,hannah,4
johannah,jo,2
johannah,joan,4
johannah,jody,3
johannah,nonie,3
johannes,john,3
johannes,johnny,3
johannes,jonathan,3
john,ian,1
john,jack,5
john,jock,3
john,johnny,5
john,jon,5
john,jonnie,3
john,jonny,3
johnathan,john,4
johnathan,johnathon,4
johnathan,johny,3
johnathan,jon,2
johnathan,jonathan,4
johnathan,jonathon,4
johnathan,jonnie,2
johnathan,jonny,2
johnathan,nathan,4
johnathon,john,4
johnathon,johnathan,4
johnathon,johny,3
johnathon,jon,2
johnathon,jonathan,4
johnathon,jonathon,4
johnathon,jonnie,2
johnathon,jonny,2
jon,john,4
jon,johnny,3
jon,jonnie,4
jon,jonny,4
jon,nathan,2
jonathan,john,3
jonathan,johnathan,4
jonathan,johnathon,4
jonathan,johny,2
jonathan,jon,5
jonathan,jonathon,4
jonathan,jonnie,2
jonathan,jonny,5
jonathan,nathan,4
jonathon,john,2
jonathon,johnathan,4
jonathon,johnathon,4
jonathon,johny,2
jonathon,jon,4
jonathon,jonathan,4
jonathon,jonnie,2
jonathon,jonny,3
joseph,jody,3
joseph,joe,5
joseph,joey,5
joseph,jos,4
josephine,fina,3
josephine,jo,5
josephine,jody,3
josephine,joey,4
josephine,josey,4
josephine,josie,5
josetta,jettie,3
josey,josophine,2
joshua,joe,2
joshua,jos,4
joshua,josh,4
josiah,jos,4
josophine,jo,2
josophine,joey,3
josophine,josey,3
joyce,joy,4
juanita,nettie,3
juanita,nita,4
judah,jude,3
judah,juder,3
judith,juda,3
judith,jude,3
judith,judi,4
judith,judie,4
judith,judy,5
judson,jud,4
judson,sonny,4
judy,judith,3
julia,jill,3
julia,jules,3
julia,julie,4
julian,jule,4
julian,jules,2
julias,jule,4
julias,jules,4
julie,jule,4
julie,jules,4
julie,julia,4
june,junius,3
junior,jr,3
junior,june,4
junior,junie,4
justin,justina,4
justin,juston,4
justin,justus,3
kaitlin,kait,4
kaitlin,kaitie,4
kaitlyn,kait,4
kaitlyn,kaitie,4
kaitlynn,kait,4
kaitlynn,kaitie,3
kalli,cali,3
kalli,kali,4
kameron,kam,4
karla,carla,4
karla,carly,3
kasey,k.c.,3
katarina,catherine,2
katarina,tina,3
kate,kay,3
katelin,kate,4
katelin,kay,4
katelin,kaye,4
katelyn,kate,4
katelyn,kay,4
katelyn,kaye,4
katherine,cassie,3
katherine,cathy,3
katherine,kate,5
katherine,kathy,5
katherine,katy,4
katherine,kay,4
katherine,kaye,3
katherine,kit,3
katherine,kittie,3
katherine,lena,3
katherine,trina,4
kathleen,cassie,3
kathleen,cathy,3
kathleen,kathy,4
kathleen,katy,4
kathleen,kay,4
kathleen,kit,3
kathleen,kittie,3
kathleen,lena,3
kathleen,trina,3
kathryn,kate,2
kathryn,kathy,4
kathryn,katie,3
katia,kate,3
katia,katie,4
katy,kate,4
katy,kathy,4
katy,katie,4
kayla,kay,4
kelley,kelli,4
kelley,kellie,4
kelley,kelly,4
kendall,ken,4
kendall,kenny,3
kendra,kay,2
kendra,kenj,3
kendra,kenji,2
kendra,kenny,2
kendrick,ken,4
kendrick,kenny,2
kendrik,ken,4
kendrik,kenny,2
kenneth,ken,5
kenneth,kendrick,3
kenneth,kenny,5
kenny,ken,4
kenny,kenneth,3
kent,ken,4
kent,kendrick,3
kent,kenny,4
kerry,kerri,4
kevin,kev,4
keziah,kizza,4
keziah,kizzie,3
kimberley,kim,3
kimberley,kimberli,4
kimberley,kimberly,4
kimberly,kim,5
kimberly,kimberley,4
kimberly,kimberli,4
kingsley,king,4
kingston,king,4
kit,kittie,4
kris,chris,3
kristel,kris,4
kristen,chris,3
kristin,chris,3
kristine,chris,3
kristine,christy,4
kristine,crissy,3
kristine,kris,4
kristine,kristy,4
kristine,tina,3
kristofer,chris,2
kristofer,kris,4
kristoffer,chris,2
kristoffer,kris,3
kristopher,chris,2
kristopher,kris,3
kristy,chris,4
kymberly,kym,4
lafayette,fate,4
lafayette,laffie,4
lamont,monty,4
laodicia,cenia,2
laodicia,dicy,2
larry,laurence,2
larry,lawrence,2
latisha,tish,4
latisha,tisha,4
laurel,laurie,4
lauren,laurie,4
lauren,ren,4
laurence,larry,3
laurence,lon,3
laurence,lonny,3
laurence,lorne,3
laurence,lorry,3
laurinda,laura,4
laurinda,lawrence,2
lauryn,laurie,4
laveda,veda,4
laverne,verna,3
laverne,vernon,3
lavina,ina,4
lavina,vina,4
lavina,viney,4
lavinia,ina,4
lavinia,vina,4
lavinia,viney,3
lavonia,vina,1
lavonia,viney,2
lavonia,vonnie,3
lavonia,wyncha,1
lavonne,von,4
lawrence,larry,5
lawrence,lawrie,4
lawrence,lon,3
lawrence,lonny,3
lawrence,lorne,3
lawrence,lorry,3
leanne,annie,4
leanne,lea,4
lecurgus,curg,4
leilani,lani,4
lemuel,lem,4
lena,ellen,3
lenora,lee,3
lenora,nora,4
leo,leon,4
leonard,len,4
leonard,lenny,3
leonard,leo,4
leonard,leon,4
leonard,lineau,3
leonidas,lee,2
leonidas,leon,4
leonora,nell,1
leonora,nellie,2
leonora,nora,4
leonore,elenor,4
leonore,honor,3
leonore,nora,2
leroy,l.r.,3
leroy,lee,3
leroy,roy,4
lesley,les,4
leslie,les,4
lester,les,4
letitia,lettice,4
letitia,lettie,4
letitia,tish,3
letitia,titia,4
levi,lee,4
levicy,vicy,4
levone,von,4
lib,libby,4
lidia,lyddy,3
lil,lilly,4
lil,lily,4
lillah,lil,4
lillah,lilly,4
lillah,lily,4
lillah,lolly,4
lillian,lil,4
lillian,lilly,4
lillian,lolly,3
lilly,lil,4
lilly,lily,4
lincoln,link,4
linda,lindy,4
linda,lynn,3
lindsay,lindsey,4
lindsay,lindsie,4
lindsay,lindsy,4
lindy,lynn,2
lionel,leon,3
lisa,alice,2
lisa,liz,2
lisa,melissa,4
littleberry,berry,3
littleberry,l.b.,1
littleberry,little,4
lizzie,liz,4
lois,lou,2
lois,louise,4
lonzo,lon,4
lorelei,laurie,2
lorelei,lori,4
lorelei,lorrie,3
lorenzo,loren,4
loretta,etta,4
loretta,lorie,4
loretta,lorrie,4
loretta,retta,4
lorraine,lorie,4
lorraine,lorrie,4
lotta,lottie,4
lou,louis,4
lou,lu,4
louis,lewis,3
louis,lou,4
louis,louie,4
louis,louise,4
louisa,eliza,4
louisa,lois,4
louisa,lou,4
louise,eliza,3
louise,lois,4
louise,lou,4
louvinia,vina,3
louvinia,viney,2
louvinia,vonnie,2
louvinia,wyncha,1
lucas,luke,3
lucia,lucius,4
lucia,lucy,4
lucias,luke,3
lucille,cille,4
lucille,lou,3
lucille,lu,3
lucille,lucy,4
lucina,sinah,2
lucinda,cindy,4
lucinda,lou,3
lucinda,lu,3
lucinda,lucy,4
lucretia,creasey,2
lucy,lucinda,2
luella,ella,4
luella,lu,3
luella,lula,4
luke,lucas,2
lunetta,nettie,3
lurana,lura,4
luther,luke,4
lydia,lyddy,4
lyndon,lindy,4
lyndon,lynn,4
mabel,amabel,4
mabel,mehitabel,3
mac,mc,4
mack,mac,4
mack,mc,3
mackenzie,kenzy,2
mackenzie,mac,2
mackenzie,mack,4
maddison,maddi,4
maddison,maddie,4
maddy,madeline,2
maddy,madelyn,3
maddy,madge,3
madeline,lena,3
madeline,maddi,3
madeline,maddie,5
madeline,maddy,5
madeline,madge,4
madeline,madie,4
madeline,magda,3
madeline,maggie,3
madeline,maud,2
madelyn,maddy,3
madelyn,madie,4
madie,madeline,4
madie,madelyn,3
madison,maddy,2
madison,mattie,2
maegen,meg,3
magdalena,lena,4
magdalena,maggie,2
magdelina,lena,3
magdelina,madge,4
magdelina,magda,4
magdelina,maggie,2
mahala,hallie,3
makayla,kayla,4
malachi,mally,2
malcolm,mac,3
malcolm,mal,4
malcolm,malc,4
malinda,lindy,3
manda,mandy,4
mandie,amanda,3
mandy,amanda,4
manerva,eve,2
manerva,minerva,4
manerva,nerva,4
manerva,nervie,3
manny,manuel,2
manoah,noah,4
manola,nonnie,2
manuel,emanuel,4
manuel,manny,2
marcus,marc,4
marcus,mark,4
margaret,daisy,3
margaret,gretta,4
margaret,madge,4
margaret,maggie,5
margaret,maggy,3
margaret,marge,5
margaret,margery,4
margaret,margie,5
margaret,margy,4
margaret,meg,5
margaret,midge,3
margaret,peg,3
margaret,peggy,5
margaret,rita,3
margaretta,daisy,3
margaretta,gretta,4
margaretta,madge,4
margaretta,maggie,3
margaretta,marge,4
margaretta,margery,4
margaretta,margie,4
margaretta,meg,3
margaretta,midge,3
margaretta,peg,3
margaretta,peggy,3
margaretta,rita,3
margarita,daisy,1
margarita,greta,2
margarita,madge,2
margarita,maggie,2
margarita,maisie,2
margarita,marge,2
margarita,margo,2
margarita,meg,2
margarita,megan,2
margarita,metta,2
margarita,midge,1
margarita,peggie,1
margarita,rita,4
marge,margaret,4
marge,margaretta,3
marge,margery,4
margie,marjorie,3
marguerite,peggy,1
mariah,maria,4
mariah,mary,4
marian,marianna,4
marian,marion,4
marie,mae,4
marie,mary,4
marietta,mae,2
marietta,mamie,3
marietta,maria,4
marietta,mariah,3
marietta,marie,4
marietta,marion,2
marietta,mary,3
marietta,maureen,2
marietta,may,3
marietta,mercy,2
marietta,minnie,2
marietta,mitzi,2
marietta,mollie,2
marietta,molly,1
marietta,polly,1
marilyn,mary,4
marion,mary,4
marissa,rissa,4
marjorie,margie,4
marjorie,margy,3
marni,marnie,4
marsha,marcia,3
marsha,marcie,2
marsha,mary,4
martha,marty,4
martha,mat,4
martha,mattie,3
martha,patsy,3
martha,patty,3
martin,marty,4
martina,tina,4
martine,tine,4
marv,marvin,4
marvin,marv,4
mary,mae,4
mary,mamie,3
mary,marie,4
mary,mitzi,3
mary,molly,5
mary,polly,5
masayuki,masa,4
mat,mattie,4
mathew,mat,4
mathew,matt,3
mathew,maty,4
mathilda,patty,2
mathilda,tillie,2
matilda,matty,3
matilda,maud,4
matilda,tilla,3
matilda,tilly,5
matthew,matt,5
matthew,mattie,4
matthew,matty,5
matthew,thias,3
matthew,thys,3
matthews,matt,4
matthews,mattie,4
matthews,matty,4
matthias,matt,4
matthias,thias,4
matthias,thys,3
maud,middy,2
maureen,mary,2
maurice,morey,3
mavery,mave,4
mavine,mave,4
maximilian,max,2
maximillian,max,2
maxine,max,4
maxwell,max,4
may,mae,3
mckenna,ken,4
mckenna,kenna,4
mckenna,meaka,2
medora,dora,4
megan,meg,4
meghan,meg,4
mehitabel,hetty,3
mehitabel,hitty,3
mehitabel,mabel,4
mehitabel,mitty,3
melanie,mellie,4
melchizedek,dick,1
melchizedek,zadock,1
melinda,linda,4
melinda,lindy,4
melinda,lynn,3
melinda,mel,4
melinda,mindy,4
melissa,lisa,4
melissa,lissa,4
melissa,mel,4
melissa,milly,3
melissa,missy,4
mellony,mellia,3
melody,lodi,3
melvin,mel,4
melvina,vina,4
mercedes,merci,3
mercedes,mercy,4
mercedes,sadie,1
merv,mervin,4
mervin,merv,4
mervyn,merv,4
micajah,cage,2
michael,micah,4
michael,mick,5
michael,mickey,3
michael,micky,3
michael,mike,5
michael,mikey,5
micheal,mike,2
micheal,mikey,2
micheal,miky,2
michelle,chelle,4
michelle,mickey,4
michelle,shelley,3
michelle,shellie,3
michelle,shelly,2
michelle,shely,2
mick,micky,4
miguel,michael,3
miguel,miggy,2
miguel,miguael,4
miguel,miguaell,4
miguel,miguail,4
miguel,miguaill,3
miguel,miguayl,4
miguel,miguayll,3
miguel,miguell,4
miguel,mike,3
mike,michael,2
mike,mick,4
mike,micky,3
mildred,milly,3
millicent,milly,4
millicent,missy,3
minerva,minnie,4
minnie,wilhelmina,2
miranda,mandy,4
miranda,mira,4
miranda,randi,3
miranda,randy,4
miriam,mimi,4
miriam,mitzi,4
miriam,mitzie,2
missy,melissa,3
mitch,mitchell,4
mitchell,mitch,4
mitzi,mary,1
mitzi,mittie,4
mitzi,mitty,3
mitzie,mittie,4
mitzie,mitty,2
monet,nettie,2
monica,monna,4
monica,monnie,3
monteleon,monte,4
montesque,monty,3
montgomery,gum,3
montgomery,monty,4
monty,lamont,4
morris,morey,4
mortimer,mort,4
moses,amos,3
moses,mose,4
moses,moss,4
muriel,mur,4
myrtle,mert,3
myrtle,myrt,4
myrtle,myrti,4
nadine,deedee,2
nadine,nada,3
nancy,ann,3
nancy,nan,5
nancy,nanny,4
naomi,omi,4
napoleon,leon,4
napoleon,nap,4
napoleon,nappy,3
natalie,natty,3
natalie,nettie,4
natasha,nat,4
natasha,tasha,4
nathan,nat,4
nathan,nate,4
nathaniel,nat,3
nathaniel,nate,4
nathaniel,nathan,4
nathaniel,natty,3
nathaniel,than,4
nelle,nelly,4
nelson,nels,4
newt,newton,4
newton,newt,4
nicholas,claas,4
nicholas,claes,4
nicholas,nic,4
nicholas,nick,5
nicholas,nickie,2
nicholas,nicky,5
nicholas,nico,3
nicholette,cole,2
nicholette,nichole,4
nicholette,nickey,2
nicholette,nicki,2
nicholette,nicky,2
nicholette,nicole,4
nicholette,nikki,1
nicodemus,nic,2
nicodemus,nick,2
nicodemus,nickie,2
nicodemus,nicky,2
nicodemus,nico,4
nicolas,nic,4
nicolas,nick,2
nicolas,nickie,2
nicolas,nicky,2
nicolas,nico,4
nicole,cole,4
nicole,nicki,2
nicole,nicky,2
nicole,nikki,5
nicole,nole,4
nikolas,claes,2
nikolas,nic,2
nikolas,nick,2
nikolas,nickie,2
nikolas,nicky,2
nikolas,nico,2
nikole,nikki,2
nora,nonie,2
norbert,bert,4
norbert,norby,4
norbusamte,norbu,4
norman,norm,4
nowell,noel,4
obadiah,diah,4
obadiah,dyer,3
obadiah,obed,4
obadiah,obie,4
obediah,obie,3
obedience,beda,2
obedience,beedy,2
obedience,biddie,2
obedience,obed,4
obie,obediah,2
octavia,tave,2
octavia,tavia,4
odell,odo,2
olive,livia,4
olive,nollie,4
olive,ollie,4
oliver,ollie,4
olivia,livia,4
olivia,nollie,3
olivia,ollie,4
ollie,oliver,4
onicyphorous,cy,1
onicyphorous,cyphorus,4
onicyphorous,one,1
onicyphorous,osaforum,2
onicyphorous,osaforus,2
onicyphorous,syphorous,4
orilla,ora,3
orilla,rilly,4
orlando,roland,4
orphelia,phelia,4
ossy,ozzy,2
oswald,ossy,3
oswald,ozzy,3
oswald,waldo,4
otis,ode,1
otis,ote,2
pamela,pam,4
pandora,dora,4
parmelia,amelia,4
parmelia,melia,4
parmelia,milly,3
parthenia,parsuny,2
parthenia,pasoonie,2
parthenia,phenie,3
parthenia,teeny,2
patience,pat,4
patience,patty,3
patricia,pat,5
patricia,patsy,3
patricia,patti,3
patricia,patty,5
patricia,tricia,5
patricia,trish,5
patricia,trisha,2
patrick,paddy,3
patrick,pat,5
patrick,pate,4
patrick,patsy,3
patrick,peter,3
patsy,patty,4
patty,patricia,2
paul,polly,2
paula,lina,3
paula,polly,3
paulina,lina,4
paulina,polly,3
pauline,polly,2
peggy,peg,4
pelegrine,perry,3
penelope,penny,5
percival,percy,4
peregrine,perry,2
permelia,mellie,2
permelia,melly,2
permelia,milly,2
pernetta,nettie,2
persephone,seph,3
persephone,sephy,2
peter,pate,4
peter,pete,5
petronella,nellie,2
pheney,josephine,2
pheriba,ferbie,2
pheriba,pherbia,4
philadelphia,delphia,4
philander,fie,2
philetus,leet,3
philetus,phil,4
philinda,linda,4
philinda,lindy,4
philinda,lynn,3
philip,phil,5
philip,pip,3
philipina,penie,1
philipina,phoebe,1
philipina,pip,2
phillip,phil,5
phillip,pip,3
philly,delphia,2
philomena,menaalmena,2
phoebe,fifi,1
pinckney,pink,3
pleasant,ples,3
pocahontas,pokey,1
posthuma,humey,2
prescott,pres,4
prescott,scott,4
prescott,scotty,4
priscilla,cilla,4
priscilla,cissy,3
priscilla,prissy,4
providence,provy,3
prudence,prudy,4
prudence,prue,4
prudy,prudence,3
rachel,rachael,4
rachel,shelly,3
rafaela,rafa,4
ramona,mona,4
randall,randy,4
randolf,dolph,2
randolf,randy,4
randolph,dolph,4
randolph,randy,4
raphael,ralph,4
ray,raymond,4
raymond,ray,5
reba,becca,2
reba,beck,1
rebecca,becca,5
rebecca,beck,4
rebecca,becky,5
rebecca,reba,4
reggie,reg,4
reggie,reginald,2
regina,gina,4
regina,reggie,4
reginald,naldo,4
reginald,reg,4
reginald,reggie,4
reginald,renny,3
relief,leafa,3
reuben,rube,4
reynold,reginald,3
rhoda,rodie,3
rhodella,della,4
rhyna,rhynie,4
ricardo,rick,4
ricardo,ricky,3
rich,dick,2
rich,rick,4
richard,dick,5
richard,dickie,3
richard,dickon,3
richard,dicky,3
richard,rich,5
richard,richie,5
richard,rick,5
richard,ricky,5
rick,ricky,4
ricky,dick,3
ricky,rich,3
robert,bill,1
robert,billy,1
robert,bob,5
robert,bobby,5
robert,dob,3
robert,dobbin,3
robert,hob,3
robert,hobkin,3
robert,rob,5
robert,robby,2
robert,rupert,3
roberta,bert,4
roberta,bertie,4
roberta,birdie,3
roberta,birtie,2
roberta,bobbie,3
roberta,robbie,4
roberta,roby,3
roberto,rob,4
roderick,erick,4
roderick,rickie,2
roderick,rod,4
roderick,roddy,2
rodger,bobby,3
rodger,hodge,4
rodger,robby,2
rodger,robin,2
rodger,rod,4
rodger,roge,4
rodger,roger,4
rodger,rupert,2
rodney,rod,4
roger,bobby,3
roger,hodge,4
roger,robby,2
roger,robin,2
roger,rod,3
roger,rodger,4
roger,roge,4
roger,rupert,3
roland,lanny,4
roland,orlando,4
roland,rollo,4
roland,rolly,4
ron,ronnie,4
ron,ronny,4
ronald,naldo,4
ronald,ron,5
ronald,ronnie,5
ronald,ronny,4
ronny,ronald,2
rosa,rose,4
rosabel,belle,3
rosabel,rosa,4
rosabel,rose,4
rosabel,roz,3
rosabella,bella,4
rosabella,belle,4
rosabella,rosa,4
rosabella,rose,4
rosabella,roz,3
rosaenn,ann,3
rosaenna,ann,2
rosalinda,linda,4
rosalinda,rosa,4
rosalinda,rose,3
rosalinda,roz,3
rosalyn,linda,3
rosalyn,rosa,4
rosalyn,rose,4
rosalyn,roz,3
roscoe,ross,3
rose,rosie,4
roseann,ann,4
roseann,rose,4
roseann,rosie,4
roseann,roz,3
roseanna,ann,4
roseanna,rose,4
roseanna,rosie,4
roseanna,roz,3
roseanne,ann,4
rosemary,marie,2
rosemary,mary,4
rosemary,rose,4
rosemary,rosemarie,4
rosemary,rosey,4
rosina,sina,4
roxane,rox,4
roxane,roxie,4
roxanna,ann,4
roxanna,rose,3
roxanna,roxie,4
roxanne,ann,4
roxanne,rose,4
roxanne,roxie,4
rudolph,dolph,4
rudolph,olph,4
rudolph,rolf,4
rudolph,rudy,4
rudolphus,dolph,4
rudolphus,olph,4
rudolphus,rolf,3
rudolphus,rudy,4
russell,russ,4
russell,rusty,3
ryan,ry,3
sabrina,brina,4
safieel,safie,4
salome,loomie,3
salvador,sal,4
salvador,sally,2
sam,sammy,4
samantha,mantha,4
samantha,sam,5
samantha,sammy,5
sampson,sam,4
sampson,sammy,2
samson,sam,4
samson,sammy,2
samuel,sam,5
samuel,sammy,5
samyra,myra,4
samyra,sam,4
samyra,sammy,4
sandra,cassandra,4
sandra,sandy,4
sandy,sandra,4
sanford,sandy,3
sarah,sadie,5
sarah,sally,5
sarah,sara,4
sarilla,silla,4
savannah,anna,4
savannah,savanna,4
savannah,vannie,2
scott,sceeter,2
scott,scottie,4
scott,scotty,4
scott,squat,2
sebastian,seb,2
sebastian,sebby,2
selma,anselm,4
serena,rena,4
serilla,rilla,4
seymour,morey,3
seymour,see,3
shaina,sha,4
shaina,shay,4
sharon,sha,4
sharon,shay,4
shaun,shawn,4
shawn,shaun,4
sheila,cecilia,3
sheldon,shelly,3
shelton,shel,4
shelton,shelly,4
shelton,tony,4
sheridan,dan,4
sheridan,danny,3
sheridan,sher,4
sheryl,cheri,2
sheryl,cherie,2
sheryl,sher,4
sheryl,sheri,4
sheryl,sherri,3
sheryl,sherry,4
sheryl,sherryl,4
shirley,lee,3
shirley,sherry,4
shirley,shirl,4
sibbilla,sibbell,4
sibbilla,sibbie,4
sibbilla,sybill,3
sidney,sid,4
sidney,syd,3
sigfired,sid,2
sigfrid,sid,3
sigismund,sig,2
silas,si,4
silence,liley,2
silvester,si,2
silvester,sly,2
silvester,syl,2
silvester,vest,4
silvester,vester,4
simeon,si,3
simeon,sion,4
simon,si,4
simon,sion,4
smith,smitty,4
socrates,crate,4
solomon,sal,3
solomon,salmon,1
solomon,saul,3
solomon,sol,4
solomon,solly,3
solomon,zolly,3
sondra,dre,2
sondra,sonnie,2
sophia,sophie,4
sophronia,frona,2
sophronia,fronia,3
sophronia,sophia,4
stacey,staci,4
stacey,stacie,4
stacey,stacy,4
stacie,stacey,4
stacie,staci,4
stacie,stacy,4
stacy,staci,4
stephan,steve,3
stephanie,annie,2
stephanie,steffi,2
stephanie,steffie,3
stephanie,steph,4
stephanie,stephani,4
stephanie,stephany,4
stephanie,stephie,4
stephanie,stephine,4
stephanie,stevie,3
stephen,steph,4
stephen,steve,5
steven,steph,4
steven,steve,5
steven,stevie,5
stuart,stu,4
submit,mitty,3
sue,susan,2
sue,susie,4
sullivan,sully,4
sullivan,van,4
susan,hannah,3
susan,sue,5
susan,sukey,3
susan,susie,5
susan,suzie,3
susannah,hannah,4
susannah,sue,3
susannah,sukey,3
susannah,susie,4
susie,suzie,4
suzanne,sue,3
suzanne,suki,2
suzanne,susie,2
sybill,sibbie,2
sydney,sid,2
sylvanus,sly,2
sylvanus,syl,4
sylvester,si,3
sylvester,sly,3
sylvester,sy,3
sylvester,syl,3
sylvester,vessie,4
sylvester,vester,4
sylvester,vet,3
tabby,tabitha,2
tabitha,tabby,3
tamarra,tammy,2
tammie,tami,4
tammie,tammy,4
tammy,tami,3
tammy,tammie,4
tanafra,tanny,2
tasha,tash,4
tasha,tashie,4
ted,teddy,4
temperance,tempy,3
terence,terry,3
teresa,terry,5
teresa,tess,5
teresa,tessa,4
teresa,tessie,2
terri,teri,4
terri,terrie,4
terri,terry,4
terry,terence,2
tess,teresa,3
tess,theresa,2
tessa,teresa,4
tessa,theresa,3
thad,thaddeus,4
thaddeus,thad,4
theo,theodore,4
theodora,dora,4
theodore,ted,4
theodore,teddy,3
theodore,theo,4
theodosia,dosia,4
theodosia,theo,4
theodosia,theodosius,4
theophilus,ophi,3
theotha,otha,4
theresa,terry,5
theresa,tess,5
theresa,tessa,4
theresa,tessie,3
theresa,thirza,4
theresa,thursa,4
theresa,traci,2
theresa,tracie,2
theresa,tracy,3
thom,thomas,4
thom,tom,4
thom,tommy,4
thomas,thom,4
thomas,tom,5
thomas,tommy,5
thomasa,tamzine,1
tiffany,tiff,4
tiffany,tiffy,4
tilford,tillie,2
tim,timmy,4
timothy,tim,5
timothy,timmy,5
tina,christina,4
tisha,tish,4
tobias,bias,4
tobias,toby,4
tom,thomas,3
tom,tommy,4
tony,anthony,4
tranquilla,quilla,4
tranquilla,trannie,2
trish,patricia,2
trish,trisha,4
trix,trixie,4
trudy,gertrude,3
tryphena,phena,4
unice,eunice,4
unice,nicie,4
uriah,riah,4
ursula,sula,4
ursula,sulie,2
valentina,felty,1
valentina,val,2
valentina,vallie,2
valentine,felty,3
valeri,val,4
valeri,valerie,4
valerie,val,4
vanburen,buren,4
vandalia,vannie,2
vanessa,essa,4
vanessa,nessa,4
vanessa,vanna,4
vernisee,nicey,2
veronica,franky,3
veronica,frony,3
veronica,ron,4
veronica,ronie,4
veronica,ronna,4
veronica,ronnie,4
veronica,ronny,2
veronica,vonnie,4
vic,vicki,4
vic,vickie,4
vic,vicky,4
vic,victor,4
vicki,vickie,4
vicki,vicky,4
vicki,victoria,3
victor,vic,4
victoria,tori,5
victoria,torie,4
victoria,torri,3
victoria,torrie,2
victoria,tory,3
victoria,vic,4
victoria,vicki,4
victoria,vickie,2
victoria,vicky,5
vijay,vij,4
vincent,vic,4
vincent,vin,4
vincent,vince,4
vincent,vinnie,4
vincent,vinny,4
vincenzo,vic,4
vincenzo,vin,4
vincenzo,vince,4
vincenzo,vinnie,4
vincenzo,vinny,4
vinson,vin,4
vinson,vince,2
vinson,vinnie,3
vinson,vinny,4
viola,ola,4
viola,vi,2
violetta,lettie,2
virginia,ginger,5
virginia,ginny,5
virginia,jane,3
virginia,jennie,3
virginia,virgy,4
vivian,vi,2
vivian,viv,4
waldo,ossy,1
waldo,ozzy,1
wallace,wally,4
wally,walt,3
walter,wally,4
walter,walt,4
washington,wash,4
webster,webb,2
wendy,wen,4
wesley,wes,4
westley,farmboy,1
westley,wes,4
westley,west,4
wilber,bert,4
wilber,will,4
wilbur,will,3
wilbur,willie,3
wilbur,willy,4
wilda,willie,2
wilfred,fred,4
wilfred,wil,4
wilfred,will,4
wilfred,willie,4
wilhelm,wil,4
wilhelm,willie,3
wilhelmina,mina,4
wilhelmina,minnie,3
wilhelmina,willie,3
wilhelmina,wilma,4
will,bill,4
will,fred,3
will,wilbur,3
will,willie,4
william,bela,3
william,bell,3
william,bill,5
william,billy,5
william,wil,4
william,will,5
william,willie,4
william,willy,5
willie,fred,3
willie,william,4
willis,bill,3
willis,willy,4
wilma,billiewilhelm,2
wilma,william,3
wilson,will,4
wilson,willie,3
wilson,willy,4
winfield,field,4
winfield,win,4
winfield,winny,3
winifred,freddie,4
winifred,winnet,4
winifred,winnie,5
winnie,winnifred,4
winnifred,fred,4
winnifred,freddie,3
winnifred,freddy,4
winnifred,winnie,4
winnifred,winny,4
winny,winnifred,2
winton,wint,4
woodrow,drew,4
woodrow,wood,4
woodrow,woody,4
yeona,ona,4
yeona,onie,2
yoshihiko,yoshi,4
yulan,lan,4
yulan,yul,4
yvonne,vonna,4
zach,zack,4
zach,zak,2
zachariah,zac,2
zachariah,zach,4
zachariah,zachy,4
zachariah,zack,2
zachariah,zak,2
zachariah,zakk,2
zachariah,zeke,3
zachary,zac,4
zachary,zach,4
zachary,zachy,4
zachary,zack,2
zachary,zak,2
zachary,zakk,2
zachary,zeke,1
zachery,zac,4
zachery,zach,4
zachery,zachy,4
zachery,zack,2
zachery,zak,2
zachery,zakk,2
zachery,zeke,2
zack,zach,4
zack,zak,4
zebedee,zeb,4
zedediah,diah,4
zedediah,dyer,3
zedediah,zed,4
zephaniah,zeph,4
`;
