/**
 * scoring.ts -- production port of redactor/candidate_quality.py's
 * score_candidate_quality() and every helper function it depends on. This
 * is Phase 5 (CandidateQualityEngine). See docs/detection/phase-5-findings.md
 * for the full port record and every documented deviation.
 *
 * PORT PHILOSOPHY (per Andrew's Phase 5 instruction): behavioral parity
 * before optimization. Every rule below traces back to a specific Python
 * function, cited inline. Nothing here "improves" on Python's scoring
 * logic -- that would be a redesign, not a migration. Where TS's domain
 * model shape genuinely cannot express something Python has (see
 * "SHAPE DIFFERENCES" below), the difference is documented at the point it
 * matters, not silently absorbed.
 *
 * SHAPE DIFFERENCES from Python, and how this file bridges them:
 *
 * 1. Python's Candidate nests its own `occurrences: List[Occurrence]` and
 *    exposes `candidate.count` as `len(occurrences)`. The TS domain model
 *    (src/domain/DocumentModel.ts) is flat: Candidate carries
 *    `occurrenceIds: string[]` and Occurrence is a separate cross-referenced
 *    array (the same flattening DetectionEngine.ts's `flatten()` already
 *    established in Phase 4). Every function below that needs "this
 *    candidate's occurrences" takes them as an explicit `occurrences:
 *    Occurrence[]` parameter instead of reading `candidate.occurrences` --
 *    the caller (CandidateQualityEngine.ts) is responsible for grouping
 *    DetectionResult.occurrences by candidateId once, up front.
 *
 * 2. Python's Occurrence carries a human-readable `location` string (e.g.
 *    "body paragraph 2", "header 1"), and `_is_heading_like()` checks
 *    `"header" in location`. Phase 4 already established the TS port has no
 *    equivalent location string (ContentBlock.id is opaque, e.g. "block-4"
 *    -- see phase-4-findings.md's documented deviation #2). This file
 *    substitutes a lookup of the occurrence's owning ContentBlock.kind
 *    (`"header"`) via a `blocksById` map instead -- structurally different
 *    input, behaviorally equivalent output for every case that matters
 *    (an occurrence in a header block was, in Python, one whose location
 *    string contained "header"). This is WHY scoreCandidateQuality's
 *    signature takes a `blocksById` parameter Python's equivalent function
 *    does not need.
 *
 * 3. `candidate.text` in Python (the literal text of the first occurrence
 *    found, used as the candidate's representative display form) is
 *    exactly TS's `Candidate.displayValue` -- confirmed by reading
 *    redactor/detectors.py's `Candidate(key, text, detected_type, source,
 *    confidence, [])` construction, which passes the first occurrence's
 *    matched text positionally into the same slot DetectionEngine.ts's
 *    `flatten()` already maps to `displayValue`. Every reference to
 *    `candidate.text` below reads `candidate.displayValue` instead.
 *
 * 4. Lexicon/weight/threshold data (QUALITY_DICTIONARIES, EVIDENCE_WEIGHTS,
 *    STATUS_THRESHOLDS) is imported from quality-dictionaries.data.ts --
 *    generated by directly dumping the LIVE Python module's already-merged
 *    values (see scripts/generate_quality_dictionaries.py), not
 *    re-implemented here. `scoreCandidateQuality()` takes `weights` and
 *    `reviewThreshold` as parameters (defaulting to the ported Python
 *    constants exported below as DEFAULT_EVIDENCE_WEIGHTS /
 *    DEFAULT_REVIEW_THRESHOLD) rather than hardcoding EVIDENCE_WEIGHTS
 *    inline -- this is deliberate, not extra ceremony: architecture v0.2
 *    ADR-015 / ScoringProfileSnapshot already exists specifically so a
 *    scoring session's weights/thresholds are pinned and reproducible even
 *    if an org's configured profile changes later. CandidateQualityEngine.ts
 *    (task #46) is responsible for building a default ScoringProfileSnapshot
 *    FROM these ported constants and passing profile.weights/
 *    profile.thresholds down into this function -- so parity is achieved via
 *    the default profile's *content*, while the *architecture* still reads
 *    through the profile mechanism Andrew's v0.2 design calls for, rather
 *    than bypassing it with an inline hardcoded copy.
 *
 * 5. `_context_text()` (candidate_quality.py line 663) is DEAD CODE in
 *    Python itself -- confirmed by grepping the entire work/
 *    pii_docx_redactor tree: it is defined but never called anywhere,
 *    including in tests. Not ported here; noted so this omission reads as
 *    a deliberate finding, not an oversight.
 *
 * 6. `is_filtered_candidate()` (always returns False) and
 *    `candidate_quality_metrics()` (an aggregate reporting/dashboard
 *    helper used by app.py/local_web_app.py, not by the scoring pipeline
 *    itself) are UI/reporting-layer concerns in Python, not part of
 *    CandidateQualityEngine's architectural responsibility ("evaluates
 *    candidates" -- architecture v0.2 §6.4). Not ported here; would belong
 *    to a future ReviewEngine/UI metrics component if ever needed.
 */

import type { Candidate, ContentBlock, Occurrence } from "../../domain/DocumentModel.js";
import type { QualityLabel, Recommendation } from "../../domain/Evidence.js";
import { EMAIL_RE } from "../detectors/patterns.js";
import {
  AMBIGUOUS_NAME_SOFT_NEGATIVES,
  COMMON_DICTIONARY_EXCLUSIONS,
  EVIDENCE_WEIGHTS,
  KNOWN_GIVEN_NAMES,
  KNOWN_SURNAMES,
  NEGATIVE_FILTER_RULES,
  PROTECTIVE_SINGLE_TOKEN_EVIDENCE_RULES,
  QUALITY_DICTIONARIES_DATA,
  STATUS_THRESHOLDS,
} from "./quality-dictionaries.data.js";

// ---- Data setup (module load time, mirrors Python's module-level dict
// construction in candidate_quality.py lines 349-460) -------------------

/** Rule name -> full, unsplit set of dictionary entries. Matches Python's
 *  `QUALITY_DICTIONARIES` exactly (used directly by _shape_rules and
 *  _single_token_classifications below -- NOT the single/phrase split,
 *  which is a separate index only _dictionary_rules uses). Key iteration
 *  order matches Python's real dict insertion order (see
 *  quality-dictionaries.data.ts's own header note) -- this matters because
 *  _dictionary_rules below iterates these keys to build an ordered
 *  `classifications` list that flows into QualityResult.reasons. */
const QUALITY_DICTIONARY_KEYS: string[] = Object.keys(QUALITY_DICTIONARIES_DATA);
const QUALITY_DICTIONARIES = new Map<string, Set<string>>(
  QUALITY_DICTIONARY_KEYS.map((rule) => [rule, new Set(QUALITY_DICTIONARIES_DATA[rule])])
);

// def _dictionary_index(dictionaries) -> (single_terms, phrase_terms):
function splitTerms(entries: Set<string>): { single: Set<string>; phrase: Set<string> } {
  const single = new Set<string>();
  const phrase = new Set<string>();
  for (const entry of entries) {
    (entry.includes(" ") ? phrase : single).add(entry);
  }
  return { single, phrase };
}

const QUALITY_SINGLE_TERMS = new Map<string, Set<string>>();
const QUALITY_PHRASE_TERMS = new Map<string, Set<string>>();
for (const [rule, entries] of QUALITY_DICTIONARIES) {
  const { single, phrase } = splitTerms(entries);
  QUALITY_SINGLE_TERMS.set(rule, single);
  QUALITY_PHRASE_TERMS.set(rule, phrase);
}

const COMMON_DICTIONARY_EXCLUSIONS_SET = new Set(COMMON_DICTIONARY_EXCLUSIONS);
// ALL_COMMON_DICTIONARY_WORDS = set().union(*(single terms for rules not excluded))
const ALL_COMMON_DICTIONARY_WORDS = new Set<string>();
for (const [rule, single] of QUALITY_SINGLE_TERMS) {
  if (COMMON_DICTIONARY_EXCLUSIONS_SET.has(rule)) continue;
  for (const term of single) ALL_COMMON_DICTIONARY_WORDS.add(term);
}

const NEGATIVE_FILTER_RULES_SET = new Set(NEGATIVE_FILTER_RULES);
const AMBIGUOUS_NAME_SOFT_NEGATIVES_SET = new Set(AMBIGUOUS_NAME_SOFT_NEGATIVES);
const PROTECTIVE_SINGLE_TOKEN_EVIDENCE_RULES_SET = new Set(PROTECTIVE_SINGLE_TOKEN_EVIDENCE_RULES);
const KNOWN_GIVEN_NAMES_SET = new Set(KNOWN_GIVEN_NAMES);
const KNOWN_SURNAMES_SET = new Set(KNOWN_SURNAMES);

/** Ported EVIDENCE_WEIGHTS, exposed so CandidateQualityEngine.ts can build
 *  a default ScoringProfileSnapshot from it (see this file's doc comment,
 *  point 4). Not read directly by scoreCandidateQuality() below -- that
 *  function takes weights as a parameter, defaulting to this. */
export const DEFAULT_EVIDENCE_WEIGHTS: Readonly<Record<string, number>> = EVIDENCE_WEIGHTS;

/** Python's `REVIEW = "To Review"` status constant, used as the key into
 *  STATUS_THRESHOLDS. Exposed for CandidateQualityEngine.ts's default
 *  ScoringProfileSnapshot construction. */
export const REVIEW_STATUS_KEY = "To Review";

/** Python's `STATUS_THRESHOLDS[REVIEW] = 25`. */
export const DEFAULT_REVIEW_THRESHOLD: number = STATUS_THRESHOLDS[REVIEW_STATUS_KEY] ?? 25;

function dedupe(values: string[]): string[] {
  // dict.fromkeys(values) -- JS Set preserves insertion order identically.
  return [...new Set(values)];
}

// ---- Regex constants (candidate_quality.py lines 20-36) ----------------

// TITLE_RE = re.compile(r"\b(?:dr|mr|mrs|ms|prof|professor|judge|dean)\.?\s+\[?", re.IGNORECASE)
const TITLE_RE = /\b(?:dr|mr|mrs|ms|prof|professor|judge|dean)\.?\s+\[?/i;

// LAST_FIRST_RE = re.compile(r"^[A-Z][A-Za-z'’.-]+,\s*[A-Z][A-Za-z'’.-]+(?:\s+[A-Z]{1,4})?$")
const LAST_FIRST_RE = /^[A-Z][A-Za-z'’.-]+,\s*[A-Z][A-Za-z'’.-]+(?:\s+[A-Z]{1,4})?$/;

// INITIAL_SURNAME_RE = re.compile(r"^(?:[A-Z]\.\s*)+[A-Z][A-Za-z'’.-]+$")
const INITIAL_SURNAME_RE = /^(?:[A-Z]\.\s*)+[A-Z][A-Za-z'’.-]+$/;

// SURNAME_INITIALS_RE = re.compile(r"^[A-Z][A-Za-z'’.-]+,\s*[A-Z]{1,4}$")
const SURNAME_INITIALS_RE = /^[A-Z][A-Za-z'’.-]+,\s*[A-Z]{1,4}$/;

// TWO_NAME_RE = re.compile(r"^[A-Z][A-Za-z'’.-]{1,}(?:\s+[A-Z][A-Za-z'’.-]{1,}){1,3}$")
const TWO_NAME_RE = /^[A-Z][A-Za-z'’.-]{1,}(?:\s+[A-Z][A-Za-z'’.-]{1,}){1,3}$/;

// BAD_CAPS_RE = re.compile(r"^[a-z]|[A-Z]{3,}[a-z]")
const BAD_CAPS_RE = /^[a-z]|[A-Z]{3,}[a-z]/;

// OCR_ARTIFACT_RE = re.compile(r"(?:[A-Za-z]\d|\d[A-Za-z]|[_\\/]{2,}|[A-Z]{2,}[a-z]{1,2}[A-Z])")
const OCR_ARTIFACT_RE = /(?:[A-Za-z]\d|\d[A-Za-z]|[_\\/]{2,}|[A-Z]{2,}[a-z]{1,2}[A-Z])/;

// ACRONYM_RE = re.compile(r"^(?:[A-Z]{2,10}|[A-Z]{1,6}\d{1,4}|(?:[A-Z]\.){2,}|[A-Z]{2,10}(?:[-/][A-Z0-9]{1,6})+|[A-Z]{2,10}-\d{1,6})$")
const ACRONYM_RE = /^(?:[A-Z]{2,10}|[A-Z]{1,6}\d{1,4}|(?:[A-Z]\.){2,}|[A-Z]{2,10}(?:[-/][A-Z0-9]{1,6})+|[A-Z]{2,10}-\d{1,6})$/;

// _tokens: re.findall(r"[A-Za-z][A-Za-z'’.-]*", ...)
const TOKEN_RE = /[A-Za-z][A-Za-z'’.-]*/g;

// _near_title's before_match regex (candidate_quality.py line 693)
const NEAR_TITLE_BEFORE_RE = /(?:^|[\s:;,.])(?:dr|mr|mrs|ms|prof|professor|judge|dean)\.?\s+\[?$/i;

// email-local-part token extraction inside _appears_in_email:
// re.findall(r"[a-z]+", email, re.IGNORECASE)
const EMAIL_LOCAL_TOKEN_RE = /[a-z]+/gi;

// _is_likely_acronym's title-case guard: re.match(r"^[A-Z][a-z]+$", compact)
const TITLECASE_WORD_RE = /^[A-Z][a-z]+$/;

const SUGGESTED_ORGANIZATION_PHRASES = new Set([
  "the records office",
  "human resources",
  "department",
  "faculty",
  "registrar",
  "records",
]);

// ---- Text normalization helpers (candidate_quality.py lines 281-298, 651-661) ---

// def normalize_lexicon_entry(value: str) -> str:
// Deviation (same one already recorded in phase-4-findings.md): Python's
// str.casefold() is slightly more aggressive than JS's toLowerCase() for a
// handful of non-ASCII characters (e.g. German "ß" -> "ss"). Every fixture
// and lexicon entry in scope is ASCII-range; not worth a hand-rolled
// casefold table against zero observed impact.
function normalizeLexiconEntry(value: string): string {
  const normalized = value.normalize("NFKC").replace(/[’‘`]/g, "'");
  return normalized.toLowerCase().trim();
}

// def _normalized_text(text: str) -> str:
function normalizedText(text: string): string {
  return normalizeLexiconEntry(text).replace(/\s+/g, " ");
}

// def _tokens(text: str) -> list[str]:
function tokens(text: string): string[] {
  return text.normalize("NFKC").match(TOKEN_RE) ?? [];
}

// def _normalized_token_set(text: str) -> set[str]:
function normalizedTokenSet(text: string): Set<string> {
  const set = new Set<string>();
  for (const token of tokens(text)) {
    set.add(normalizeLexiconEntry(token).replace(/^\.+|\.+$/g, ""));
  }
  return set;
}

// ---- Positive-evidence helpers (candidate_quality.py lines 667-718) ----

/** Substitute for Python's `_is_heading_like`'s `"header" in
 *  normalize_lexicon_entry(occurrence.location)` check -- see this file's
 *  doc comment, point 2. `blocksById` must contain every block referenced
 *  by `occurrences[].blockId`. */
// def _is_heading_like(candidate: Candidate) -> bool:
function isHeadingLike(occurrences: Occurrence[], blocksById: ReadonlyMap<string, ContentBlock>): boolean {
  for (const occurrence of occurrences) {
    const block = blocksById.get(occurrence.blockId);
    const context = occurrence.context;
    if (block?.kind === "header" || normalizeLexiconEntry(context).includes("subject")) {
      return true;
    }
    const bare = context.replace(/\[/g, "").replace(/\]/g, "").trim();
    if (bare && bare.toUpperCase() === bare && bare.length > 8) {
      return true;
    }
  }
  return false;
}

// def _appears_in_email(candidate: Candidate) -> bool:
function appearsInEmail(displayValue: string, occurrences: Occurrence[]): boolean {
  const candidateTokens = normalizedTokenSet(displayValue);
  if (candidateTokens.size === 0) return false;
  for (const occurrence of occurrences) {
    for (const match of occurrence.context.matchAll(EMAIL_RE)) {
      const email = match[0];
      const emailTokens = new Set<string>();
      for (const tokenMatch of email.matchAll(EMAIL_LOCAL_TOKEN_RE)) {
        emailTokens.add(normalizeLexiconEntry(tokenMatch[0]));
      }
      for (const t of candidateTokens) {
        if (emailTokens.has(t)) return true;
      }
    }
  }
  return false;
}

// def _near_title(candidate: Candidate) -> bool:
function nearTitle(occurrences: Occurrence[]): boolean {
  for (const occurrence of occurrences) {
    const context = occurrence.context;
    const bracketIndex = context.indexOf("[");
    const sliceEnd = bracketIndex >= 0 ? bracketIndex : context.length;
    const before = context.slice(0, sliceEnd);
    if (NEAR_TITLE_BEFORE_RE.test(before) || TITLE_RE.test(context)) {
      return true;
    }
  }
  return false;
}

const SIGNATURE_MARKERS = ["signature", "regards,", "sincerely,", "from:", "sent:"];

// def _signature_evidence(candidate: Candidate) -> bool:
function signatureEvidence(displayValue: string, occurrences: Occurrence[]): boolean {
  const text = normalizeLexiconEntry(displayValue);
  for (const occurrence of occurrences) {
    const context = normalizeLexiconEntry(occurrence.context);
    if (SIGNATURE_MARKERS.some((marker) => context.includes(marker)) && context.includes(text)) {
      return true;
    }
  }
  return false;
}

// def _positive_evidence(candidate: Candidate) -> list[str]:
function positiveEvidence(candidate: Candidate, occurrences: Occurrence[]): string[] {
  const reasons: string[] = [];
  if (candidate.detectedType !== "person") reasons.push("deterministic_non_person_type");
  if (appearsInEmail(candidate.displayValue, occurrences)) reasons.push("email_address_evidence");
  if (nearTitle(occurrences)) reasons.push("nearby_title");
  if (signatureEvidence(candidate.displayValue, occurrences)) reasons.push("signature_or_email_header_context");
  return reasons;
}

// ---- Dictionary / shape / acronym classification (lines 721-816) ------

// def _dictionary_rules(text: str, tokens: set[str]) -> list[str]:
function dictionaryRules(text: string, tokenSet: Set<string>): string[] {
  const folded = normalizedText(text);
  const rules: string[] = [];
  for (const rule of QUALITY_DICTIONARY_KEYS) {
    const phraseTerms = QUALITY_PHRASE_TERMS.get(rule);
    if (phraseTerms?.has(folded)) {
      rules.push(rule);
      continue;
    }
    const singleTerms = QUALITY_SINGLE_TERMS.get(rule);
    if (singleTerms) {
      for (const t of tokenSet) {
        if (singleTerms.has(t)) {
          rules.push(rule);
          break;
        }
      }
    }
  }
  return rules;
}

// def _is_likely_acronym(text: str) -> bool:
function isLikelyAcronym(text: string): boolean {
  const compact = text.normalize("NFKC").trim().replace(/\s+/g, "");
  if (!compact || TITLECASE_WORD_RE.test(compact)) return false;
  return ACRONYM_RE.test(compact);
}

// def _acronym_classifications(text: str) -> list[str]:
function acronymClassifications(text: string): string[] {
  return isLikelyAcronym(text) ? ["likely_acronym"] : [];
}

// def _shape_rules(text, tokens, token_set) -> list[str]:
function shapeRules(text: string, tokenList: string[], tokenSet: Set<string>): string[] {
  const rules: string[] = [];
  if (tokenList.length === 0) {
    rules.push("no_alpha_tokens");
    return rules;
  }
  if (isLikelyAcronym(text)) return rules;
  if (BAD_CAPS_RE.test(text)) rules.push("implausible_capitalization");

  const sentenceFragmentWords = QUALITY_DICTIONARIES.get("sentence_fragment_word") ?? new Set<string>();
  let fragmentOverlap = 0;
  for (const t of tokenSet) if (sentenceFragmentWords.has(t)) fragmentOverlap++;
  if (tokenList.length >= 2 && fragmentOverlap >= 1) rules.push("sentence_fragment");

  if (tokenSet.size > 0 && [...tokenSet].every((t) => ALL_COMMON_DICTIONARY_WORDS.has(t))) {
    rules.push("all_common_dictionary_words");
  }
  if (tokenList.length > 4) rules.push("grammatical_phrase_shape");
  if (tokenList.length === 1 && (tokenList[0]?.length ?? 0) <= 2) rules.push("too_short_single_token");
  if (OCR_ARTIFACT_RE.test(text) && !isLikelyAcronym(text)) rules.push("ocr_artifact");
  return rules;
}

// def _single_token_classifications(text, tokens, token_set) -> list[str]:
function singleTokenClassifications(text: string, tokenList: string[], tokenSet: Set<string>): string[] {
  if (tokenList.length !== 1) return [];
  const token = tokenSet.values().next().value ?? "";
  const has = (rule: string): boolean => QUALITY_DICTIONARIES.get(rule)?.has(token) ?? false;
  const classifications: string[] = [];

  if (KNOWN_GIVEN_NAMES_SET.has(token) || has("known_first_name")) classifications.push("known_first_name");
  if (KNOWN_SURNAMES_SET.has(token) || has("known_surname")) classifications.push("known_surname");
  if (has("common_english_word")) classifications.push("common_english_word");
  if (has("address_suffix")) classifications.push("address_suffix");
  if (has("calendar_abbreviation")) classifications.push("calendar_abbreviation");
  if (has("common_abbreviation")) classifications.push("common_abbreviation");
  if (has("contraction")) classifications.push("contraction");
  if (has("expanded_common_language_token")) classifications.push("expanded_common_language_token");
  if (has("interjection_casual")) classifications.push("interjection_casual");
  if (has("institution_acronym")) classifications.push("institution_acronym");
  if (has("product_system_name")) classifications.push("product_system_name");
  if (has("department_organization")) classifications.push("department_organization");
  if (has("honorific_title")) classifications.push("honorific_title");
  if (has("professional_credential")) classifications.push("professional_credential");
  if (has("organization_suffix")) classifications.push("organization_suffix");
  if (has("document_structure_term")) classifications.push("document_structure_term");
  if (has("legal_administrative_term")) classifications.push("legal_administrative_term");
  if (OCR_ARTIFACT_RE.test(text) && !isLikelyAcronym(text)) classifications.push("ocr_artifact");
  if (isLikelyAcronym(text)) classifications.push("likely_acronym");

  if (classifications.length === 0) {
    if (/^[A-Z]/.test(text)) classifications.push("unknown_capitalized_token");
    else if (/^[a-z]/.test(text)) classifications.push("unknown_lowercase_token");
    else classifications.push("unknown_token");
  }
  return classifications;
}

interface QualityEvidence {
  classifications: string[];
  positive: string[];
  negative: string[];
}

// def _quality_evidence(candidate, text, tokens, token_set) -> QualityEvidence:
function qualityEvidence(
  candidate: Candidate,
  occurrences: Occurrence[],
  text: string,
  tokenList: string[],
  tokenSet: Set<string>
): QualityEvidence {
  const positive = positiveEvidence(candidate, occurrences);
  const acronymRules = acronymClassifications(text);
  let dictRules = dictionaryRules(text, tokenSet);
  if (acronymRules.length > 0) {
    dictRules = dictRules.filter((r) => r !== "sentence_fragment_word");
  }
  const shapeRulesResult = shapeRules(text, tokenList, tokenSet);
  const singleTokenRules = singleTokenClassifications(text, tokenList, tokenSet);

  let classifications = dedupe([...dictRules, ...shapeRulesResult, ...acronymRules, ...singleTokenRules]);

  if (tokenList.length > 1 || classifications.includes("ambiguous_lexical_token")) {
    classifications = classifications.filter((r) => r !== "expanded_common_language_token");
  }
  const unknownFallbackRules = new Set(["unknown_capitalized_token", "unknown_lowercase_token", "unknown_token"]);
  if (classifications.some((r) => !unknownFallbackRules.has(r))) {
    classifications = classifications.filter((r) => !unknownFallbackRules.has(r));
  }

  const promoted = classifications.filter((r) => r === "known_first_name" || r === "known_surname");
  const positiveFull = dedupe([...positive, ...promoted]);
  const negative = dedupe(classifications.filter((r) => NEGATIVE_FILTER_RULES_SET.has(r)));

  return { classifications, positive: positiveFull, negative };
}

// ---- Scoring primitives (candidate_quality.py lines 580-648) -----------

export interface EvidenceContribution {
  rule: string;
  label: string;
  weight: number;
}

/** Result shape mirrors Python's QualityResult dataclass field-for-field
 *  (candidate_quality.py lines 497-508). `status` uses TS's existing
 *  `Recommendation` vocabulary ("ToReview"/"Unlikely") instead of Python's
 *  literal "To Review"/"Unlikely" strings -- same two-way status axis,
 *  just spelled to match src/domain/Evidence.ts's pre-existing type rather
 *  than introducing a second string vocabulary for the same concept. */
export interface ScoredQuality {
  quality: QualityLabel;
  reasons: string[];
  explanation: string;
  suggestedType?: string | undefined;
  status: Recommendation;
  score: number;
  evidenceBreakdown: EvidenceContribution[];
  positiveReasons: string[];
  filterRules: string[];
}

const EXPLICIT_EVIDENCE_LABELS: Record<string, string> = {
  deterministic_non_person_type: "Deterministic non-person type",
  email_address_evidence: "Email address evidence",
  nearby_title: "Nearby honorific or title",
  signature_or_email_header_context: "Signature or email header context",
  surname_given_structure: "Surname, given-name structure",
  initials_with_surname: "Initials with surname",
  strong_name_structure: "Strong name structure",
  known_personal_name_token: "Known personal-name token",
  known_first_name: "Known first name",
  known_surname: "Known surname",
  single_name_candidate: "Single-name candidate",
  single_token_reviewable_without_negative_evidence: "Single token without strong negative evidence",
  small_frequency_bonus: "Small frequency bonus",
  moderate_frequency_bonus: "Moderate frequency bonus",
  frequency_saturated: "Frequency saturation",
};

// Python's str.title(): here every input is already lowercase snake_case
// with underscores replaced by spaces, so uppercasing each word's first
// letter is behaviorally identical for every real input this sees.
function titleCase(value: string): string {
  return value.replace(/\b\w/g, (c) => c.toUpperCase());
}

// def _evidence_label(rule: str) -> str:
function evidenceLabel(rule: string): string {
  return EXPLICIT_EVIDENCE_LABELS[rule] ?? titleCase(rule.replace(/_/g, " "));
}

// def _score_from_evidence(reasons: list[str]) -> tuple[int, list[dict]]:
function scoreFromEvidence(
  reasons: string[],
  weights: Record<string, number>
): { score: number; breakdown: EvidenceContribution[] } {
  const uniqueReasons = dedupe(reasons);
  const contributions: EvidenceContribution[] = uniqueReasons.map((reason) => ({
    rule: reason,
    label: evidenceLabel(reason),
    weight: weights[reason] ?? 0,
  }));
  const rawScore = 35 + contributions.reduce((sum, c) => sum + c.weight, 0);
  const score = Math.max(1, Math.min(99, rawScore));
  return { score, breakdown: contributions };
}

// def _status_from_score(score: int) -> str:
function statusFromScore(score: number, reviewThreshold: number): Recommendation {
  return score >= reviewThreshold ? "ToReview" : "Unlikely";
}

// def _quality_from_score(score: int) -> str:
function qualityFromScore(score: number, reviewThreshold: number): QualityLabel {
  if (score >= 80) return "Strong";
  if (score >= reviewThreshold) return "Possible";
  return "Unlikely";
}

interface ScoredResultArgs {
  reasons: string[];
  explanation: string;
  suggestedType?: string | undefined;
  positiveReasons?: string[];
  filterRules?: string[];
}

// def _scored_result(*, reasons, explanation, suggested_type=None, positive_reasons=None, filter_rules=None) -> QualityResult:
function scoredResult(args: ScoredResultArgs, weights: Record<string, number>, reviewThreshold: number): ScoredQuality {
  const uniqueReasons = dedupe(args.reasons);
  const { score, breakdown } = scoreFromEvidence(uniqueReasons, weights);
  return {
    quality: qualityFromScore(score, reviewThreshold),
    reasons: uniqueReasons,
    explanation: args.explanation,
    suggestedType: args.suggestedType,
    status: statusFromScore(score, reviewThreshold),
    score,
    evidenceBreakdown: breakdown,
    positiveReasons: dedupe(args.positiveReasons ?? []),
    filterRules: dedupe(args.filterRules ?? []),
  };
}

// def _filter_result(candidate, base_reasons, filter_rules, evidence_rules=None) -> QualityResult:
// `candidate` param dropped -- Python's own implementation never reads it.
function filterResult(
  baseReasons: string[],
  filterRulesArg: string[],
  weights: Record<string, number>,
  reviewThreshold: number,
  evidenceRulesArg?: string[]
): ScoredQuality {
  // Python: `evidence = evidence_rules or filter_rules` -- `or` falls back
  // on both None AND an empty list, since both are falsy in Python.
  const evidenceRules = evidenceRulesArg && evidenceRulesArg.length > 0 ? evidenceRulesArg : filterRulesArg;
  return scoredResult(
    {
      reasons: [...baseReasons, ...evidenceRules, "no_positive_person_evidence"],
      explanation: "Deterministic evidence gives this candidate low review priority",
      filterRules: evidenceRules,
    },
    weights,
    reviewThreshold
  );
}

// ---- Main entry point (candidate_quality.py lines 872-968) -------------

/**
 * Faithful port of `score_candidate_quality(candidate)`. See this file's
 * top doc comment for why the signature differs from Python's
 * single-argument version (shape differences #1 and #2).
 *
 * @param candidate the candidate being scored (detectedType, displayValue)
 * @param occurrences exactly this candidate's occurrences -- the caller
 *   must group DetectionResult.occurrences by candidateId before calling
 *   (see CandidateQualityEngine.ts). Order does not affect the result:
 *   every occurrence-scanning helper here uses "any occurrence matches"
 *   semantics, same as Python's iteration.
 * @param blocksById every ContentBlock referenced by
 *   occurrences[].blockId, keyed by id -- substitutes for Python's
 *   per-occurrence location string (shape difference #2).
 * @param weights defaults to the ported Python EVIDENCE_WEIGHTS constants;
 *   pass ScoringProfileSnapshot.weights for profile-driven, reproducible
 *   scoring (shape difference #4 / ADR-015).
 * @param reviewThreshold defaults to the ported Python
 *   STATUS_THRESHOLDS[REVIEW]; pass ScoringProfileSnapshot.thresholds[...] .
 */
export function scoreCandidateQuality(
  candidate: Candidate,
  occurrences: Occurrence[],
  blocksById: ReadonlyMap<string, ContentBlock>,
  weights: Record<string, number> = DEFAULT_EVIDENCE_WEIGHTS,
  reviewThreshold: number = DEFAULT_REVIEW_THRESHOLD
): ScoredQuality {
  if (candidate.detectedType !== "person") {
    return scoredResult(
      {
        reasons: ["deterministic_non_person_type"],
        explanation: "Deterministic non-person detector",
        positiveReasons: ["deterministic_non_person_type"],
      },
      weights,
      reviewThreshold
    );
  }

  const text = candidate.displayValue.trim().replace(/\s+/g, " ");
  const folded = normalizedText(text);
  const tokenList = tokens(text);
  const tokenSet = normalizedTokenSet(text);
  const reasons: string[] = [];
  let suggestedType: string | undefined;

  const count = occurrences.length;
  if (count === 1) reasons.push("single_occurrence");
  else if (count === 2) reasons.push("small_frequency_bonus");
  else if (count <= 5) reasons.push("moderate_frequency_bonus");
  else reasons.push("frequency_saturated");

  const evidence = qualityEvidence(candidate, occurrences, text, tokenList, tokenSet);
  const positiveReasons = evidence.positive;
  const classifications = evidence.classifications;
  const filterRules = evidence.negative;

  if (SUGGESTED_ORGANIZATION_PHRASES.has(folded)) {
    suggestedType = "organization";
  }

  const hasAmbiguousNameEvidence = classifications.includes("ambiguous_lexical_token");
  const hasProtectiveSingleTokenEvidence =
    tokenList.length === 1 && classifications.some((r) => PROTECTIVE_SINGLE_TOKEN_EVIDENCE_RULES_SET.has(r));
  const onlySoftAmbiguousNegatives = filterRules.every((r) => AMBIGUOUS_NAME_SOFT_NEGATIVES_SET.has(r));

  if (
    filterRules.length > 0 &&
    positiveReasons.length === 0 &&
    !((hasAmbiguousNameEvidence || hasProtectiveSingleTokenEvidence) && onlySoftAmbiguousNegatives)
  ) {
    return filterResult(reasons, filterRules, weights, reviewThreshold, classifications);
  }

  if (LAST_FIRST_RE.test(text)) {
    return scoredResult(
      {
        reasons: [...reasons, ...positiveReasons, ...classifications, "surname_given_structure"],
        explanation: "Strong surname, given-name structure",
        positiveReasons: [...positiveReasons, "surname_given_structure"],
        filterRules: classifications,
      },
      weights,
      reviewThreshold
    );
  }

  if (SURNAME_INITIALS_RE.test(text) || INITIAL_SURNAME_RE.test(text)) {
    return scoredResult(
      {
        reasons: [...reasons, ...positiveReasons, ...classifications, "initials_with_surname"],
        explanation: "Strong surname and initials structure",
        positiveReasons: [...positiveReasons, "initials_with_surname"],
        filterRules: classifications,
      },
      weights,
      reviewThreshold
    );
  }

  if (TWO_NAME_RE.test(text)) {
    const structureReasons = ["strong_name_structure"];
    let hasKnownGivenNameToken = false;
    for (const t of tokenSet) {
      if (KNOWN_GIVEN_NAMES_SET.has(t)) {
        hasKnownGivenNameToken = true;
        break;
      }
    }
    if (hasKnownGivenNameToken) structureReasons.push("known_personal_name_token");

    if (isHeadingLike(occurrences, blocksById) && positiveReasons.length === 0) {
      return scoredResult(
        {
          reasons: [...reasons, ...positiveReasons, ...structureReasons, "heading_context"],
          explanation: "Name-like phrase, but heading context makes it less certain",
          positiveReasons: [...positiveReasons, ...structureReasons],
          filterRules: classifications,
        },
        weights,
        reviewThreshold
      );
    }
    return scoredResult(
      {
        reasons: [...reasons, ...positiveReasons, ...classifications, ...structureReasons],
        explanation: "Strong personal-name structure",
        positiveReasons: [...positiveReasons, ...structureReasons],
        filterRules: classifications,
      },
      weights,
      reviewThreshold
    );
  }

  if (tokenList.length === 1) {
    if (positiveReasons.length > 0) {
      return scoredResult(
        {
          reasons: [...reasons, ...positiveReasons, ...classifications, "single_name_candidate"],
          explanation: "Single-name candidate",
          positiveReasons,
          filterRules: classifications,
        },
        weights,
        reviewThreshold
      );
    }
    return scoredResult(
      {
        reasons: [...reasons, ...classifications, "single_token_reviewable_without_negative_evidence"],
        explanation: "Single-token candidate without strong negative evidence",
        filterRules: classifications,
      },
      weights,
      reviewThreshold
    );
  }

  return scoredResult(
    {
      reasons: [...reasons, ...positiveReasons, ...classifications, "weak_name_structure"],
      explanation: "Possible person candidate",
      suggestedType,
      positiveReasons,
      filterRules: classifications,
    },
    weights,
    reviewThreshold
  );
}
