/**
 * scoring.ts -- production port of redactor/candidate_quality.py's
 * score_candidate_quality() and every helper function it depends on. This
 * is Phase 5 (CandidateQualityEngine). See docs/detection/phase-5-findings.md
 * for the full port record and every documented deviation.
 *
 * PORT PHILOSOPHY (per Andrew's Phase 5 instruction): behavioral parity
 * before optimization. Every rule below traces back to a specific Python
 * function, cited inline. Nothing here "improves" on Python's scoring
 * logic -- that would be a redesign, not a migration. Where TS's domain
 * model shape genuinely cannot express something Python has (see
 * "SHAPE DIFFERENCES" below), the difference is documented at the point it
 * matters, not silently absorbed.
 *
 * SHAPE DIFFERENCES from Python, and how this file bridges them:
 *
 * 1. Python's Candidate nests its own `occurrences: List[Occurrence]` and
 *    exposes `candidate.count` as `len(occurrences)`. The TS domain model
 *    (src/domain/DocumentModel.ts) is flat: Candidate carries
 *    `occurrenceIds: string[]` and Occurrence is a separate cross-referenced
 *    array (the same flattening DetectionEngine.ts's `flatten()` already
 *    established in Phase 4). Every function below that needs "this
 *    candidate's occurrences" takes them as an explicit `occurrences:
 *    Occurrence[]` parameter instead of reading `candidate.occurrences` --
 *    the caller (CandidateQualityEngine.ts) is responsible for grouping
 *    DetectionResult.occurrences by candidateId once, up front.
 *
 * 2. Python's Occurrence carries a human-readable `location` string (e.g.
 *    "body paragraph 2", "header 1"), and `_is_heading_like()` checks
 *    `"header" in location`. Phase 4 already established the TS port has no
 *    equivalent location string (ContentBlock.id is opaque, e.g. "block-4"
 *    -- see phase-4-findings.md's documented deviation #2). This file
 *    substitutes a lookup of the occurrence's owning ContentBlock.kind
 *    (`"header"`) via a `blocksById` map instead -- structurally different
 *    input, behaviorally equivalent output for every case that matters
 *    (an occurrence in a header block was, in Python, one whose location
 *    string contained "header"). This is WHY scoreCandidateQuality's
 *    signature takes a `blocksById` parameter Python's equivalent function
 *    does not need.
 *
 * 3. `candidate.text` in Python (the literal text of the first occurrence
 *    found, used as the candidate's representative display form) is
 *    exactly TS's `Candidate.displayValue` -- confirmed by reading
 *    redactor/detectors.py's `Candidate(key, text, detected_type, source,
 *    confidence, [])` construction, which passes the first occurrence's
 *    matched text positionally into the same slot DetectionEngine.ts's
 *    `flatten()` already maps to `displayValue`. Every reference to
 *    `candidate.text` below reads `candidate.displayValue` instead.
 *
 * 4. Lexicon/weight/threshold data (QUALITY_DICTIONARIES, EVIDENCE_WEIGHTS,
 *    STATUS_THRESHOLDS) is imported from quality-dictionaries.data.ts --
 *    generated by directly dumping the LIVE Python module's already-merged
 *    values (see scripts/generate_quality_dictionaries.py), not
 *    re-implemented here. `scoreCandidateQuality()` takes `weights` and
 *    `reviewThreshold` as parameters (defaulting to the ported Python
 *    constants exported below as DEFAULT_EVIDENCE_WEIGHTS /
 *    DEFAULT_REVIEW_THRESHOLD) rather than hardcoding EVIDENCE_WEIGHTS
 *    inline -- this is deliberate, not extra ceremony: architecture v0.2
 *    ADR-015 / ScoringProfileSnapshot already exists specifically so a
 *    scoring session's weights/thresholds are pinned and reproducible even
 *    if an org's configured profile changes later. CandidateQualityEngine.ts
 *    (task #46) is responsible for building a default ScoringProfileSnapshot
 *    FROM these ported constants and passing profile.weights/
 *    profile.thresholds down into this function -- so parity is achieved via
 *    the default profile's *content*, while the *architecture* still reads
 *    through the profile mechanism Andrew's v0.2 design calls for, rather
 *    than bypassing it with an inline hardcoded copy.
 *
 * 5. `_context_text()` (candidate_quality.py line 663) is DEAD CODE in
 *    Python itself -- confirmed by grepping the entire work/
 *    pii_docx_redactor tree: it is defined but never called anywhere,
 *    including in tests. Not ported here; noted so this omission reads as
 *    a deliberate finding, not an oversight.
 *
 * 6. `is_filtered_candidate()` (always returns False) and
 *    `candidate_quality_metrics()` (an aggregate reporting/dashboard
 *    helper used by app.py/local_web_app.py, not by the scoring pipeline
 *    itself) are UI/reporting-layer concerns in Python, not part of
 *    CandidateQualityEngine's architectural responsibility ("evaluates
 *    candidates" -- architecture v0.2 §6.4). Not ported here; would belong
 *    to a future ReviewEngine/UI metrics component if ever needed.
 */

import type { Candidate, ContentBlock, Occurrence } from "../../domain/DocumentModel.js";
import type { QualityLabel, Recommendation } from "../../domain/Evidence.js";
import type {
  CandidateContextualEvidence,
  ContextualEvidenceRuleId,
} from "../contextual-person-evidence/contextual-person-evidence.js";
import { CONTEXTUAL_EVIDENCE_RULE } from "../contextual-person-evidence/contextual-person-evidence.js";
import { EMAIL_RE } from "../detectors/patterns.js";
import {
  AMBIGUOUS_NAME_SOFT_NEGATIVES,
  COMMON_DICTIONARY_EXCLUSIONS,
  EVIDENCE_WEIGHTS,
  KNOWN_GIVEN_NAMES,
  KNOWN_SURNAMES,
  NEGATIVE_FILTER_RULES,
  PROTECTIVE_SINGLE_TOKEN_EVIDENCE_RULES,
  QUALITY_DICTIONARIES_DATA,
  STATUS_THRESHOLDS,
} from "./quality-dictionaries.data.js";

// ---- Data setup (module load time, mirrors Python's module-level dict
// construction in candidate_quality.py lines 349-460) -------------------

/** Rule name -> full, unsplit set of dictionary entries. Matches Python's
 *  `QUALITY_DICTIONARIES` exactly (used directly by _shape_rules and
 *  _single_token_classifications below -- NOT the single/phrase split,
 *  which is a separate index only _dictionary_rules uses). Key iteration
 *  order matches Python's real dict insertion order (see
 *  quality-dictionaries.data.ts's own header note) -- this matters because
 *  _dictionary_rules below iterates these keys to build an ordered
 *  `classifications` list that flows into QualityResult.reasons. */
const QUALITY_DICTIONARY_KEYS: string[] = Object.keys(QUALITY_DICTIONARIES_DATA);
/** Exported (2026-08-09) for the contextual-person Guard 1, which builds its
 *  "cannot be a person" set from these lexicons rather than declaring a
 *  blacklist -- see contextual-person-evidence.ts. */
export const QUALITY_DICTIONARIES = new Map<string, Set<string>>(
  QUALITY_DICTIONARY_KEYS.map((rule) => [rule, new Set(QUALITY_DICTIONARIES_DATA[rule])])
);

// def _dictionary_index(dictionaries) -> (single_terms, phrase_terms):
function splitTerms(entries: Set<string>): { single: Set<string>; phrase: Set<string> } {
  const single = new Set<string>();
  const phrase = new Set<string>();
  for (const entry of entries) {
    (entry.includes(" ") ? phrase : single).add(entry);
  }
  return { single, phrase };
}

const QUALITY_SINGLE_TERMS = new Map<string, Set<string>>();
const QUALITY_PHRASE_TERMS = new Map<string, Set<string>>();
for (const [rule, entries] of QUALITY_DICTIONARIES) {
  const { single, phrase } = splitTerms(entries);
  QUALITY_SINGLE_TERMS.set(rule, single);
  QUALITY_PHRASE_TERMS.set(rule, phrase);
}

const COMMON_DICTIONARY_EXCLUSIONS_SET = new Set(COMMON_DICTIONARY_EXCLUSIONS);
// ALL_COMMON_DICTIONARY_WORDS = set().union(*(single terms for rules not excluded))
const ALL_COMMON_DICTIONARY_WORDS = new Set<string>();
for (const [rule, single] of QUALITY_SINGLE_TERMS) {
  if (COMMON_DICTIONARY_EXCLUSIONS_SET.has(rule)) continue;
  for (const term of single) ALL_COMMON_DICTIONARY_WORDS.add(term);
}

const NEGATIVE_FILTER_RULES_SET = new Set(NEGATIVE_FILTER_RULES);
const AMBIGUOUS_NAME_SOFT_NEGATIVES_SET = new Set(AMBIGUOUS_NAME_SOFT_NEGATIVES);
const PROTECTIVE_SINGLE_TOKEN_EVIDENCE_RULES_SET = new Set(PROTECTIVE_SINGLE_TOKEN_EVIDENCE_RULES);
const KNOWN_GIVEN_NAMES_SET = new Set(KNOWN_GIVEN_NAMES);
const KNOWN_SURNAMES_SET = new Set(KNOWN_SURNAMES);

/** Ported EVIDENCE_WEIGHTS, exposed so CandidateQualityEngine.ts can build
 *  a default ScoringProfileSnapshot from it (see this file's doc comment,
 *  point 4). Not read directly by scoreCandidateQuality() below -- that
 *  function takes weights as a parameter, defaulting to this. */
export const DEFAULT_EVIDENCE_WEIGHTS: Readonly<Record<string, number>> = {
  ...EVIDENCE_WEIGHTS,
  /**
   * ADDITIVE, TS-ONLY (AG, 2026-08-05). Not a ported Python weight -- the
   * generated parity data file is untouched, as it must be. This entry is
   * the CAP on the Contextual Person Evidence family's combined
   * contribution, not a fixed per-rule weight; scoreCandidateQuality()
   * substitutes the per-candidate figure at call time.
   *
   * INERT WITHOUT THE PASS. `contextual_person_evidence` can only appear in
   * a candidate's reasons when a caller supplies contextual evidence, so
   * adding this key changes no existing score -- including every score
   * verify/quality-parity.ts checks against Python.
   *
   * Setting it to 0 (or omitting it from a custom ScoringProfileSnapshot)
   * disables the whole family for that session.
   */
  [CONTEXTUAL_EVIDENCE_RULE]: 55,
};

/** Python's `REVIEW = "To Review"` status constant, used as the key into
 *  STATUS_THRESHOLDS. Exposed for CandidateQualityEngine.ts's default
 *  ScoringProfileSnapshot construction. */
export const REVIEW_STATUS_KEY = "To Review";

/** Python's `STATUS_THRESHOLDS[REVIEW] = 25`. */
export const DEFAULT_REVIEW_THRESHOLD: number = STATUS_THRESHOLDS[REVIEW_STATUS_KEY] ?? 25;

function dedupe(values: string[]): string[] {
  // dict.fromkeys(values) -- JS Set preserves insertion order identically.
  return [...new Set(values)];
}

// ---- Regex constants (candidate_quality.py lines 20-36) ----------------

// TITLE_RE = re.compile(r"\b(?:dr|mr|mrs|ms|prof|professor|judge|dean)\.?\s+\[?", re.IGNORECASE)
const TITLE_RE = /\b(?:dr|mr|mrs|ms|prof|professor|judge|dean)\.?\s+\[?/i;

/*
 * ORACLE DEVIATION #9 -- UNICODE NAME SHAPE (AG, 2026-08-10).
 *
 * Python's name-shape regexes are ASCII-only (`[A-Z]`, `[A-Za-z'’.-]`), and
 * the port copied them faithfully. The DETECTOR does not share that limit --
 * patterns.ts matches `\p{Lu}\p{Ll}` -- so every accented name is detected and
 * then fails its own shape test:
 *
 *     Yazmine Guzman   strong_name_structure   -> People
 *     Yazmine Guzmań  weak_name_structure     -> Other
 *     José Martínez    weak_name_structure     -> Other
 *     Ana Núñez        weak_name_structure     -> Other
 *
 * That is not a scoring judgment, it is a character-class defect, and it
 * systematically disadvantages exactly the population a redaction tool most
 * needs to protect. The classes below are widened to `\p{Lu}` / `\p{L}\p{M}`
 * with the `u` flag; the STRUCTURE each regex tests is unchanged, and no ASCII
 * input changes its answer.
 *
 * Display text is never touched -- this is a matching change only.
 *
 * CLASSIFICATION: correctness fix. Pinned in both directions by
 * verify/unicode-name-shape-verification.ts.
 */
const NAME_UPPER = "\\p{Lu}";
const NAME_REST = "[\\p{L}\\p{M}'’.-]";

// LAST_FIRST_RE = re.compile(r"^[A-Z][A-Za-z'’.-]+,\s*[A-Z][A-Za-z'’.-]+(?:\s+[A-Z]{1,4})?$")
const LAST_FIRST_RE = new RegExp(`^${NAME_UPPER}${NAME_REST}+,\\s*${NAME_UPPER}${NAME_REST}+(?:\\s+${NAME_UPPER}{1,4})?$`, "u");

// INITIAL_SURNAME_RE = re.compile(r"^(?:[A-Z]\.\s*)+[A-Z][A-Za-z'’.-]+$")   -- deviation #9
const INITIAL_SURNAME_RE = new RegExp(`^(?:${NAME_UPPER}\\.\\s*)+${NAME_UPPER}${NAME_REST}+$`, "u");

// SURNAME_INITIALS_RE = re.compile(r"^[A-Z][A-Za-z'’.-]+,\s*[A-Z]{1,4}$")   -- deviation #9
const SURNAME_INITIALS_RE = new RegExp(`^${NAME_UPPER}${NAME_REST}+,\\s*${NAME_UPPER}{1,4}$`, "u");

// TWO_NAME_RE = re.compile(r"^[A-Z][A-Za-z'’.-]{1,}(?:\s+[A-Z][A-Za-z'’.-]{1,}){1,3}$")   -- deviation #9
const TWO_NAME_RE = new RegExp(`^${NAME_UPPER}${NAME_REST}{1,}(?:\\s+${NAME_UPPER}${NAME_REST}{1,}){1,3}$`, "u");

// BAD_CAPS_RE = re.compile(r"^[a-z]|[A-Z]{3,}[a-z]")
const BAD_CAPS_RE = /^[a-z]|[A-Z]{3,}[a-z]/;

// OCR_ARTIFACT_RE = re.compile(r"(?:[A-Za-z]\d|\d[A-Za-z]|[_\\/]{2,}|[A-Z]{2,}[a-z]{1,2}[A-Z])")
const OCR_ARTIFACT_RE = /(?:[A-Za-z]\d|\d[A-Za-z]|[_\\/]{2,}|[A-Z]{2,}[a-z]{1,2}[A-Z])/;

// ACRONYM_RE = re.compile(r"^(?:[A-Z]{2,10}|[A-Z]{1,6}\d{1,4}|(?:[A-Z]\.){2,}|[A-Z]{2,10}(?:[-/][A-Z0-9]{1,6})+|[A-Z]{2,10}-\d{1,6})$")
const ACRONYM_RE = /^(?:[A-Z]{2,10}|[A-Z]{1,6}\d{1,4}|(?:[A-Z]\.){2,}|[A-Z]{2,10}(?:[-/][A-Z0-9]{1,6})+|[A-Z]{2,10}-\d{1,6})$/;

// _tokens: re.findall(r"[A-Za-z][A-Za-z'’.-]*", ...)   -- deviation #9
// Widened with the same reasoning: an ASCII-only tokenizer split "Guzmán"
// into "Guzm" and "n", so no lexicon lookup could ever match an accented name.
const TOKEN_RE = /[\p{L}][\p{L}\p{M}'’.-]*/gu;

// _near_title's before_match regex (candidate_quality.py line 693)
const NEAR_TITLE_BEFORE_RE = /(?:^|[\s:;,.])(?:dr|mr|mrs|ms|prof|professor|judge|dean)\.?\s+\[?$/i;

// email-local-part token extraction inside _appears_in_email:
// re.findall(r"[a-z]+", email, re.IGNORECASE)
const EMAIL_LOCAL_TOKEN_RE = /[a-z]+/gi;

// _is_likely_acronym's title-case guard: re.match(r"^[A-Z][a-z]+$", compact)
const TITLECASE_WORD_RE = /^[A-Z][a-z]+$/;

const SUGGESTED_ORGANIZATION_PHRASES = new Set([
  "the records office",
  "human resources",
  "department",
  "faculty",
  "registrar",
  "records",
]);

// ---- Text normalization helpers (candidate_quality.py lines 281-298, 651-661) ---

// def normalize_lexicon_entry(value: str) -> str:
// Deviation (same one already recorded in phase-4-findings.md): Python's
// str.casefold() is slightly more aggressive than JS's toLowerCase() for a
// handful of non-ASCII characters (e.g. German "ß" -> "ss"). Every fixture
// and lexicon entry in scope is ASCII-range; not worth a hand-rolled
// casefold table against zero observed impact.
function normalizeLexiconEntry(value: string): string {
  const normalized = value.normalize("NFKC").replace(/[’‘`]/g, "'");
  return normalized.toLowerCase().trim();
}

// def _normalized_text(text: str) -> str:
function normalizedText(text: string): string {
  return normalizeLexiconEntry(text).replace(/\s+/g, " ");
}

// def _tokens(text: str) -> list[str]:
function tokens(text: string): string[] {
  return text.normalize("NFKC").match(TOKEN_RE) ?? [];
}

// def _normalized_token_set(text: str) -> set[str]:
function normalizedTokenSet(text: string): Set<string> {
  const set = new Set<string>();
  for (const token of tokens(text)) {
    set.add(normalizeLexiconEntry(token).replace(/^\.+|\.+$/g, ""));
  }
  return set;
}

// ---- Positive-evidence helpers (candidate_quality.py lines 667-718) ----

/** Substitute for Python's `_is_heading_like`'s `"header" in
 *  normalize_lexicon_entry(occurrence.location)` check -- see this file's
 *  doc comment, point 2. `blocksById` must contain every block referenced
 *  by `occurrences[].blockId`. */
// def _is_heading_like(candidate: Candidate) -> bool:
function isHeadingLike(occurrences: Occurrence[], blocksById: ReadonlyMap<string, ContentBlock>): boolean {
  for (const occurrence of occurrences) {
    const block = blocksById.get(occurrence.blockId);
    const context = occurrence.context;
    if (block?.kind === "header" || normalizeLexiconEntry(context).includes("subject")) {
      return true;
    }
    const bare = context.replace(/\[/g, "").replace(/\]/g, "").trim();
    if (bare && bare.toUpperCase() === bare && bare.length > 8) {
      return true;
    }
  }
  return false;
}

// def _appears_in_email(candidate: Candidate) -> bool:
function appearsInEmail(displayValue: string, occurrences: Occurrence[]): boolean {
  const candidateTokens = normalizedTokenSet(displayValue);
  if (candidateTokens.size === 0) return false;
  for (const occurrence of occurrences) {
    for (const match of occurrence.context.matchAll(EMAIL_RE)) {
      const email = match[0];
      const emailTokens = new Set<string>();
      for (const tokenMatch of email.matchAll(EMAIL_LOCAL_TOKEN_RE)) {
        emailTokens.add(normalizeLexiconEntry(tokenMatch[0]));
      }
      for (const t of candidateTokens) {
        if (emailTokens.has(t)) return true;
      }
    }
  }
  return false;
}

// def _near_title(candidate: Candidate) -> bool:
/*
 * ============================================================================
 * DELIBERATE ORACLE DEVIATION #6 -- nearby_title SCOPE (AG, 2026-08-09)
 *
 * Python's rule is `NEAR_TITLE_BEFORE_RE.test(before) || TITLE_RE.test(context)`.
 * The second branch tests the WHOLE 140-character context window, so a title
 * anywhere in it fires -- after the candidate, in a different sentence, or
 * belonging to somebody else entirely:
 *
 *   before  anywhere  fires
 *   true    true      true   "Dr. [Garcia] will review it"          <- correct
 *   false   true      true   "[The] Reg audit report came in.  Dr. Garcia will..."
 *   false   true      true   "[Grades] are due Friday, per Dean Martinez"
 *   false   true      true   "[Morning] everyone -- Dr. Lopez is out today"
 *   false   true      true   "[Andrew] met with Dr. Garcia"
 *
 * The last row states the defect most plainly: the rule attributes ONE
 * PERSON'S HONORIFIC TO A DIFFERENT CANDIDATE. On Andrew's live document it
 * was the sole remaining reason "The" was held as "recognized as a name",
 * and it explains the whole observed family -- Last, Thank, Grades, Morning.
 *
 * THE DEVIATION: the whole-context branch is deleted. Title evidence now
 * requires the honorific to be ATTACHED TO or IMMEDIATELY PRECEDING this
 * candidate:
 *
 *   1. `NEAR_TITLE_BEFORE_RE` on the text before the candidate -- unchanged,
 *      and the branch that was always right.
 *   2. the candidate's OWN text beginning with a title ("Dr. Garcia" detected
 *      as one candidate). Added deliberately: it was previously carried by
 *      the whole-context branch, and deleting that without this replacement
 *      would have LOST a legitimate signal rather than narrowed a bad one.
 *
 * Classification: this is a PRECISION FIX, not a behaviour change -- the
 * oracle's answer is a false claim about the document ("a title is near this
 * candidate" when it is near a different one), and the evidence layer's
 * credibility is what the whole residual gate rests on.
 * ============================================================================
 */
function nearTitle(displayValue: string, occurrences: Occurrence[]): boolean {
  // 2. Attached: the candidate itself carries the honorific.
  if (TITLE_RE.test(displayValue)) return true;
  // 1. Immediately preceding, in this occurrence's own context.
  for (const occurrence of occurrences) {
    const context = occurrence.context;
    const bracketIndex = context.indexOf("[");
    const sliceEnd = bracketIndex >= 0 ? bracketIndex : context.length;
    const before = context.slice(0, sliceEnd);
    if (NEAR_TITLE_BEFORE_RE.test(before)) return true;
  }
  return false;
}

const SIGNATURE_MARKERS = ["signature", "regards,", "sincerely,", "from:", "sent:"];

// def _signature_evidence(candidate: Candidate) -> bool:
function signatureEvidence(displayValue: string, occurrences: Occurrence[]): boolean {
  const text = normalizeLexiconEntry(displayValue);
  for (const occurrence of occurrences) {
    const context = normalizeLexiconEntry(occurrence.context);
    if (SIGNATURE_MARKERS.some((marker) => context.includes(marker)) && context.includes(text)) {
      return true;
    }
  }
  return false;
}

// def _positive_evidence(candidate: Candidate) -> list[str]:
function positiveEvidence(candidate: Candidate, occurrences: Occurrence[]): string[] {
  const reasons: string[] = [];
  if (candidate.detectedType !== "person") reasons.push("deterministic_non_person_type");
  if (appearsInEmail(candidate.displayValue, occurrences)) reasons.push("email_address_evidence");
  if (nearTitle(candidate.displayValue, occurrences)) reasons.push("nearby_title");
  if (signatureEvidence(candidate.displayValue, occurrences)) reasons.push("signature_or_email_header_context");
  return reasons;
}

// ---- Dictionary / shape / acronym classification (lines 721-816) ------

// def _dictionary_rules(text: str, tokens: set[str]) -> list[str]:
function dictionaryRules(text: string, tokenSet: Set<string>): string[] {
  const folded = normalizedText(text);
  const rules: string[] = [];
  for (const rule of QUALITY_DICTIONARY_KEYS) {
    const phraseTerms = QUALITY_PHRASE_TERMS.get(rule);
    if (phraseTerms?.has(folded)) {
      rules.push(rule);
      continue;
    }
    const singleTerms = QUALITY_SINGLE_TERMS.get(rule);
    if (singleTerms) {
      for (const t of tokenSet) {
        if (singleTerms.has(t)) {
          rules.push(rule);
          break;
        }
      }
    }
  }
  return rules;
}

// def _is_likely_acronym(text: str) -> bool:
function isLikelyAcronym(text: string): boolean {
  const compact = text.normalize("NFKC").trim().replace(/\s+/g, "");
  if (!compact || TITLECASE_WORD_RE.test(compact)) return false;
  return ACRONYM_RE.test(compact);
}

/**
 * DEVIATION #2 from the Python oracle (2026-08-05, AG) -- a category the
 * ported vocabulary cannot express, added rather than approximated. The
 * first deviation is in engines/detectors/patterns.ts; both are deliberate
 * and named so a behavioral difference from Python is never accidental.
 *
 * WHY. Acronym detection is pure shape: ACRONYM_RE's first alternative is
 * `[A-Z]{2,10}`, any 2-10 consecutive capitals, consulting no lexicon. So
 * CALENDAR, OPEN, NOTE, TODAY, NEWS and VETERAN all classify as
 * `likely_acronym` on the strength of their capitalization alone.
 *
 * WHAT THIS IS NOT. It is NOT a dictionary EXCLUSION -- Andrew's
 * instruction is explicit, and correct: real acronyms often are real words
 * (NOTE, NEWS, CARE), so removing them would lose true positives to fix a
 * presentation problem. `likely_acronym` is still emitted, always, and this
 * category rides ALONGSIDE it rather than replacing it.
 *
 * It is also NOT a score. There is no acronym-confidence band in this
 * engine to lower: EVIDENCE_WEIGHTS scores PERSONHOOD, and
 * `likely_acronym: -8` means "acronym-shaped is mild evidence against being
 * a person" -- nothing to do with how confident we are that it IS an
 * acronym. Deliberately absent from EVIDENCE_WEIGHTS, so `weights[rule] ?? 0`
 * gives it a zero contribution: it appears in the evidence breakdown as an
 * EXPLANATION and moves no number. Deliberately absent from
 * NEGATIVE_FILTER_RULES for the same reason.
 *
 * NAMING. Per Andrew, explicitly not "common word" or any label implying
 * that dictionary membership DISPROVES acronym status. The claim is
 * strictly weaker than that, and is exactly:
 *
 *     Acronym-shaped, but lexically ambiguous.
 *
 * The reviewer decides which reading applies; this category exists so the
 * UI can ask rather than assert.
 */
export const ACRONYM_LEXICALLY_AMBIGUOUS = "acronym_lexically_ambiguous";

/**
 * The LEXICAL dictionaries -- the ones that answer "is this an ordinary
 * word of English", which is the only question this category asks.
 *
 * DO NOT substitute ALL_COMMON_DICTIONARY_WORDS here. It looks like the
 * right set and is precisely wrong for this purpose, in both directions,
 * which a first implementation of this function proved empirically:
 *
 *   - It EXCLUDES `expanded_common_language_token` (via
 *     COMMON_DICTIONARY_EXCLUSIONS), which is the 51k-entry lexicon where
 *     NOTE, NEWS, OPEN, TODAY and CALENDAR actually live -- i.e. it misses
 *     every example Andrew raised.
 *   - It INCLUDES `institution_acronym`, `institution_term`,
 *     `department_organization`, `product_system_name` and friends, so it
 *     fires on CSULA and FERPA -- genuine, unambiguous acronyms, exactly
 *     the items that must NOT be qualified.
 *
 * That set is a union built for the `all_common_dictionary_words` rule, a
 * different question with a different answer. Kept separate deliberately.
 *
 * `sentence_fragment_word` is deliberately absent: the assembly in
 * qualityEvidence() already strips that rule whenever acronym rules fire,
 * so including it here would quietly reintroduce what that line suppresses.
 * `calendar_term` is also absent -- MAY/MARCH already carry their own
 * strong signal and their own reviewer vocabulary; widening this category
 * to cover them would be a second claim, not this one.
 */
const LEXICAL_WORD_RULES = [
  "common_english_word",
  "expanded_common_language_token",
  "common_verb",
  "pronoun_or_determiner",
  "greeting_or_courtesy",
  "interjection_casual",
];
/** Exported (2026-08-09) for the People-routing investigation's read-only
 *  diagnostic. Exporting a constant changes no behaviour; the alternative
 *  was rebuilding this union in the diagnostic, which is exactly the
 *  duplicate-lexicon drift the comment above exists to prevent. */
export const LEXICAL_WORDS = new Set<string>();
for (const rule of LEXICAL_WORD_RULES) {
  for (const term of QUALITY_SINGLE_TERMS.get(rule) ?? []) LEXICAL_WORDS.add(term);
}

/**
 * True when the candidate is acronym-shaped AND its whole compacted form is
 * also an ordinary word.
 *
 * Tests the COMPACTED FORM, not any constituent token: ACRONYM_RE is
 * anchored `^...$`, so the acronym is always the entire candidate, and a
 * per-token test would fire on multi-word candidates that merely contain a
 * common word.
 */
function isLexicallyAmbiguousAcronym(text: string): boolean {
  const compact = normalizeLexiconEntry(text.normalize("NFKC").trim().replace(/\s+/g, ""));
  return compact.length > 0 && LEXICAL_WORDS.has(compact);
}

// def _acronym_classifications(text: str) -> list[str]:
// DEVIATION #2: the second entry has no Python counterpart. See above.
function acronymClassifications(text: string): string[] {
  if (!isLikelyAcronym(text)) return [];
  const classifications = ["likely_acronym"];
  if (isLexicallyAmbiguousAcronym(text)) classifications.push(ACRONYM_LEXICALLY_AMBIGUOUS);
  return classifications;
}

// def _shape_rules(text, tokens, token_set) -> list[str]:
function shapeRules(text: string, tokenList: string[], tokenSet: Set<string>): string[] {
  const rules: string[] = [];
  if (tokenList.length === 0) {
    rules.push("no_alpha_tokens");
    return rules;
  }
  if (isLikelyAcronym(text)) return rules;
  if (BAD_CAPS_RE.test(text)) rules.push("implausible_capitalization");

  const sentenceFragmentWords = QUALITY_DICTIONARIES.get("sentence_fragment_word") ?? new Set<string>();
  let fragmentOverlap = 0;
  for (const t of tokenSet) if (sentenceFragmentWords.has(t)) fragmentOverlap++;
  if (tokenList.length >= 2 && fragmentOverlap >= 1) rules.push("sentence_fragment");

  if (tokenSet.size > 0 && [...tokenSet].every((t) => ALL_COMMON_DICTIONARY_WORDS.has(t))) {
    rules.push("all_common_dictionary_words");
  }
  if (tokenList.length > 4) rules.push("grammatical_phrase_shape");
  if (tokenList.length === 1 && (tokenList[0]?.length ?? 0) <= 2) rules.push("too_short_single_token");
  if (OCR_ARTIFACT_RE.test(text) && !isLikelyAcronym(text)) rules.push("ocr_artifact");
  return rules;
}

// def _single_token_classifications(text, tokens, token_set) -> list[str]:
function singleTokenClassifications(text: string, tokenList: string[], tokenSet: Set<string>): string[] {
  if (tokenList.length !== 1) return [];
  const token = tokenSet.values().next().value ?? "";
  const has = (rule: string): boolean => QUALITY_DICTIONARIES.get(rule)?.has(token) ?? false;
  const classifications: string[] = [];

  if (KNOWN_GIVEN_NAMES_SET.has(token) || has("known_first_name")) classifications.push("known_first_name");
  if (KNOWN_SURNAMES_SET.has(token) || has("known_surname")) classifications.push("known_surname");
  if (has("common_english_word")) classifications.push("common_english_word");
  if (has("address_suffix")) classifications.push("address_suffix");
  if (has("calendar_abbreviation")) classifications.push("calendar_abbreviation");
  if (has("common_abbreviation")) classifications.push("common_abbreviation");
  if (has("contraction")) classifications.push("contraction");
  if (has("expanded_common_language_token")) classifications.push("expanded_common_language_token");
  if (has("interjection_casual")) classifications.push("interjection_casual");
  if (has("institution_acronym")) classifications.push("institution_acronym");
  if (has("product_system_name")) classifications.push("product_system_name");
  if (has("department_organization")) classifications.push("department_organization");
  if (has("honorific_title")) classifications.push("honorific_title");
  if (has("professional_credential")) classifications.push("professional_credential");
  if (has("organization_suffix")) classifications.push("organization_suffix");
  if (has("document_structure_term")) classifications.push("document_structure_term");
  if (has("legal_administrative_term")) classifications.push("legal_administrative_term");
  if (OCR_ARTIFACT_RE.test(text) && !isLikelyAcronym(text)) classifications.push("ocr_artifact");
  if (isLikelyAcronym(text)) classifications.push("likely_acronym");

  if (classifications.length === 0) {
    if (/^[A-Z]/.test(text)) classifications.push("unknown_capitalized_token");
    else if (/^[a-z]/.test(text)) classifications.push("unknown_lowercase_token");
    else classifications.push("unknown_token");
  }
  return classifications;
}

interface QualityEvidence {
  classifications: string[];
  positive: string[];
  negative: string[];
}

// def _quality_evidence(candidate, text, tokens, token_set) -> QualityEvidence:
function qualityEvidence(
  candidate: Candidate,
  occurrences: Occurrence[],
  text: string,
  tokenList: string[],
  tokenSet: Set<string>
): QualityEvidence {
  const positive = positiveEvidence(candidate, occurrences);
  const acronymRules = acronymClassifications(text);
  let dictRules = dictionaryRules(text, tokenSet);
  if (acronymRules.length > 0) {
    dictRules = dictRules.filter((r) => r !== "sentence_fragment_word");
  }
  const shapeRulesResult = shapeRules(text, tokenList, tokenSet);
  const singleTokenRules = singleTokenClassifications(text, tokenList, tokenSet);

  let classifications = dedupe([...dictRules, ...shapeRulesResult, ...acronymRules, ...singleTokenRules]);

  if (tokenList.length > 1 || classifications.includes("ambiguous_lexical_token")) {
    classifications = classifications.filter((r) => r !== "expanded_common_language_token");
  }
  const unknownFallbackRules = new Set(["unknown_capitalized_token", "unknown_lowercase_token", "unknown_token"]);
  if (classifications.some((r) => !unknownFallbackRules.has(r))) {
    classifications = classifications.filter((r) => !unknownFallbackRules.has(r));
  }

  const promoted = classifications.filter((r) => r === "known_first_name" || r === "known_surname");
  const positiveFull = dedupe([...positive, ...promoted]);
  const negative = dedupe(classifications.filter((r) => NEGATIVE_FILTER_RULES_SET.has(r)));

  return { classifications, positive: positiveFull, negative };
}

// ---- Scoring primitives (candidate_quality.py lines 580-648) -----------

export interface EvidenceContribution {
  rule: string;
  label: string;
  weight: number;
}

/** Result shape mirrors Python's QualityResult dataclass field-for-field
 *  (candidate_quality.py lines 497-508). `status` uses TS's existing
 *  `Recommendation` vocabulary ("ToReview"/"Unlikely") instead of Python's
 *  literal "To Review"/"Unlikely" strings -- same two-way status axis,
 *  just spelled to match src/domain/Evidence.ts's pre-existing type rather
 *  than introducing a second string vocabulary for the same concept. */
export interface ScoredQuality {
  quality: QualityLabel;
  reasons: string[];
  explanation: string;
  suggestedType?: string | undefined;
  status: Recommendation;
  score: number;
  evidenceBreakdown: EvidenceContribution[];
  positiveReasons: string[];
  filterRules: string[];
  /**
   * ADDITIVE (AG, 2026-08-05). The individual contextual usages behind the
   * single `contextual_person_evidence` contribution, and the occurrence id
   * that best demonstrates them. Empty on every candidate scored without
   * contextual evidence -- which is every candidate in the Python-parity
   * harness, by construction.
   *
   * Carried on the RESULT rather than folded into `reasons` on purpose:
   * `reasons` is what evidenceBreakdown is built from, and putting eleven
   * zero-weight rule ids there would mint eleven empty chips. These travel
   * to the explanation and Expert View instead. See the ONE CHIP, NOT ELEVEN
   * note in contextual-person-evidence.ts.
   */
  contextualRules: ContextualEvidenceRuleId[];
  contextualRepresentativeOccurrenceId?: string | undefined;
}

const EXPLICIT_EVIDENCE_LABELS: Record<string, string> = {
  // DEVIATION #2 -- explicit so the breakdown never shows the titleCase
  // fallback ("Acronym Lexically Ambiguous"), and so the wording stays
  // two-sided rather than reading as a verdict against acronym status.
  [ACRONYM_LEXICALLY_AMBIGUOUS]: "Could be an acronym or an ordinary word",
  deterministic_non_person_type: "Deterministic non-person type",
  email_address_evidence: "Email address evidence",
  nearby_title: "Nearby honorific or title",
  signature_or_email_header_context: "Signature or email header context",
  surname_given_structure: "Surname, given-name structure",
  initials_with_surname: "Initials with surname",
  strong_name_structure: "Strong name structure",
  known_personal_name_token: "Known personal-name token",
  known_first_name: "Known first name",
  known_surname: "Known surname",
  single_name_candidate: "Single-name candidate",
  single_token_reviewable_without_negative_evidence: "Single token without strong negative evidence",
  small_frequency_bonus: "Small frequency bonus",
  moderate_frequency_bonus: "Moderate frequency bonus",
  frequency_saturated: "Frequency saturation",
};

// Python's str.title(): here every input is already lowercase snake_case
// with underscores replaced by spaces, so uppercasing each word's first
// letter is behaviorally identical for every real input this sees.
function titleCase(value: string): string {
  return value.replace(/\b\w/g, (c) => c.toUpperCase());
}

// def _evidence_label(rule: str) -> str:
function evidenceLabel(rule: string): string {
  return EXPLICIT_EVIDENCE_LABELS[rule] ?? titleCase(rule.replace(/_/g, " "));
}

// def _score_from_evidence(reasons: list[str]) -> tuple[int, list[dict]]:
function scoreFromEvidence(
  reasons: string[],
  weights: Record<string, number>
): { score: number; breakdown: EvidenceContribution[] } {
  const uniqueReasons = dedupe(reasons);
  const contributions: EvidenceContribution[] = uniqueReasons.map((reason) => ({
    rule: reason,
    label: evidenceLabel(reason),
    weight: weights[reason] ?? 0,
  }));
  const rawScore = 35 + contributions.reduce((sum, c) => sum + c.weight, 0);
  const score = Math.max(1, Math.min(99, rawScore));
  return { score, breakdown: contributions };
}

// def _status_from_score(score: int) -> str:
function statusFromScore(score: number, reviewThreshold: number): Recommendation {
  return score >= reviewThreshold ? "ToReview" : "Unlikely";
}

// def _quality_from_score(score: int) -> str:
function qualityFromScore(score: number, reviewThreshold: number): QualityLabel {
  if (score >= 80) return "Strong";
  if (score >= reviewThreshold) return "Possible";
  return "Unlikely";
}

interface ScoredResultArgs {
  reasons: string[];
  explanation: string;
  suggestedType?: string | undefined;
  positiveReasons?: string[];
  filterRules?: string[];
  /** See ScoredQuality.contextualRules. Absent on every path that was not
   *  given contextual evidence, which keeps the Python-parity output shape
   *  unchanged apart from two empty additive fields. */
  contextualRules?: ContextualEvidenceRuleId[];
  contextualRepresentativeOccurrenceId?: string | undefined;
}

// def _scored_result(*, reasons, explanation, suggested_type=None, positive_reasons=None, filter_rules=None) -> QualityResult:
function scoredResult(args: ScoredResultArgs, weights: Record<string, number>, reviewThreshold: number): ScoredQuality {
  const uniqueReasons = dedupe(args.reasons);
  const { score, breakdown } = scoreFromEvidence(uniqueReasons, weights);
  return {
    quality: qualityFromScore(score, reviewThreshold),
    reasons: uniqueReasons,
    explanation: args.explanation,
    suggestedType: args.suggestedType,
    status: statusFromScore(score, reviewThreshold),
    score,
    evidenceBreakdown: breakdown,
    positiveReasons: dedupe(args.positiveReasons ?? []),
    filterRules: dedupe(args.filterRules ?? []),
    contextualRules: args.contextualRules ?? [],
    contextualRepresentativeOccurrenceId: args.contextualRepresentativeOccurrenceId,
  };
}

// def _filter_result(candidate, base_reasons, filter_rules, evidence_rules=None) -> QualityResult:
// `candidate` param dropped -- Python's own implementation never reads it.
function filterResult(
  baseReasons: string[],
  filterRulesArg: string[],
  weights: Record<string, number>,
  reviewThreshold: number,
  evidenceRulesArg?: string[]
): ScoredQuality {
  // Python: `evidence = evidence_rules or filter_rules` -- `or` falls back
  // on both None AND an empty list, since both are falsy in Python.
  const evidenceRules = evidenceRulesArg && evidenceRulesArg.length > 0 ? evidenceRulesArg : filterRulesArg;
  return scoredResult(
    {
      reasons: [...baseReasons, ...evidenceRules, "no_positive_person_evidence"],
      explanation: "Deterministic evidence gives this candidate low review priority",
      filterRules: evidenceRules,
    },
    weights,
    reviewThreshold
  );
}

// ---- Main entry point (candidate_quality.py lines 872-968) -------------

/**
 * Faithful port of `score_candidate_quality(candidate)`. See this file's
 * top doc comment for why the signature differs from Python's
 * single-argument version (shape differences #1 and #2).
 *
 * @param candidate the candidate being scored (detectedType, displayValue)
 * @param occurrences exactly this candidate's occurrences -- the caller
 *   must group DetectionResult.occurrences by candidateId before calling
 *   (see CandidateQualityEngine.ts). Order does not affect the result:
 *   every occurrence-scanning helper here uses "any occurrence matches"
 *   semantics, same as Python's iteration.
 * @param blocksById every ContentBlock referenced by
 *   occurrences[].blockId, keyed by id -- substitutes for Python's
 *   per-occurrence location string (shape difference #2).
 * @param weights defaults to the ported Python EVIDENCE_WEIGHTS constants;
 *   pass ScoringProfileSnapshot.weights for profile-driven, reproducible
 *   scoring (shape difference #4 / ADR-015).
 * @param reviewThreshold defaults to the ported Python
 *   STATUS_THRESHOLDS[REVIEW]; pass ScoringProfileSnapshot.thresholds[...] .
 * @param contextual OPTIONAL, ADDITIVE (AG, 2026-08-05) -- this candidate's
 *   Contextual Person Evidence, if the caller ran that pass. OMITTED BY THE
 *   PYTHON-PARITY HARNESS ON PURPOSE: with no contextual evidence this
 *   function behaves exactly as the port always did, which is what lets
 *   verify/quality-parity.ts keep diffing exact scores and exact `reasons`
 *   arrays against Python with no fixture deviations. See
 *   engines/contextual-person-evidence/contextual-person-evidence.ts for
 *   why the family lives outside this file.
 *
 *   The profile governs it twice over: the family is inert unless
 *   `weights[CONTEXTUAL_EVIDENCE_RULE]` is present, and that weight acts as
 *   the CAP on the contribution -- so a ScoringProfileSnapshot genuinely
 *   pins what a session was scored with (ADR-015) even though the
 *   contribution itself is computed per candidate.
 */
export function scoreCandidateQuality(
  candidate: Candidate,
  occurrences: Occurrence[],
  blocksById: ReadonlyMap<string, ContentBlock>,
  weights: Record<string, number> = DEFAULT_EVIDENCE_WEIGHTS,
  reviewThreshold: number = DEFAULT_REVIEW_THRESHOLD,
  contextual?: CandidateContextualEvidence | undefined
): ScoredQuality {
  const cap = weights[CONTEXTUAL_EVIDENCE_RULE] ?? 0;
  const contribution = contextual && cap > 0 ? Math.min(contextual.contribution, cap) : 0;

  if (contribution <= 0) {
    return scoreCandidateQualityCore(candidate, occurrences, blocksById, weights, reviewThreshold, []);
  }

  const scored = scoreCandidateQualityCore(
    candidate,
    occurrences,
    blocksById,
    // The per-candidate contribution replaces the profile's cap entry for
    // this one call, so evidenceBreakdown's weight is the number that
    // actually moved the score -- the invariant the evidence panel relies on.
    { ...weights, [CONTEXTUAL_EVIDENCE_RULE]: contribution },
    reviewThreshold,
    [CONTEXTUAL_EVIDENCE_RULE]
  );
  return {
    ...scored,
    contextualRules: contextual?.rules ?? [],
    contextualRepresentativeOccurrenceId: contextual?.representative?.occurrenceId,
  };
}

/**
 * The unmodified port. `contextualReasons` is either empty (every historical
 * caller, and the parity harness) or the single
 * `contextual_person_evidence` id, injected into positiveReasons so that it
 * both scores AND clears the negative-evidence gate below.
 *
 * CLEARING THE GATE IS THE POINT, more than the weight is. The early return
 * at "filterRules.length > 0 && positiveReasons.length === 0" discards
 * structure entirely and lands a candidate at the floor. "May" in
 * "Thanks, May" carries calendar_term and common_english_word and no lexical
 * positives, so today it scores 1 and is never seen. Entering as a positive
 * reason routes it to the single-token branch instead: 35 -4 +40 +8 -50 =
 * 29, To Review. The lexical negatives SURVIVE in that sum -- contextual
 * evidence overcomes the ambiguity without erasing it, which is the
 * behaviour Andrew specified, produced by the arithmetic rather than by a
 * special case.
 */
function scoreCandidateQualityCore(
  candidate: Candidate,
  occurrences: Occurrence[],
  blocksById: ReadonlyMap<string, ContentBlock>,
  weights: Record<string, number>,
  reviewThreshold: number,
  contextualReasons: string[]
): ScoredQuality {
  if (candidate.detectedType !== "person") {
    return scoredResult(
      {
        reasons: ["deterministic_non_person_type"],
        explanation: "Deterministic non-person detector",
        positiveReasons: ["deterministic_non_person_type"],
      },
      weights,
      reviewThreshold
    );
  }

  const text = candidate.displayValue.trim().replace(/\s+/g, " ");
  const folded = normalizedText(text);
  const tokenList = tokens(text);
  const tokenSet = normalizedTokenSet(text);
  const reasons: string[] = [];
  let suggestedType: string | undefined;

  const count = occurrences.length;
  if (count === 1) reasons.push("single_occurrence");
  else if (count === 2) reasons.push("small_frequency_bonus");
  else if (count <= 5) reasons.push("moderate_frequency_bonus");
  else reasons.push("frequency_saturated");

  const evidence = qualityEvidence(candidate, occurrences, text, tokenList, tokenSet);
  const positiveReasons = dedupe([...evidence.positive, ...contextualReasons]);
  const classifications = evidence.classifications;
  const filterRules = evidence.negative;

  if (SUGGESTED_ORGANIZATION_PHRASES.has(folded)) {
    suggestedType = "organization";
  }

  const hasAmbiguousNameEvidence = classifications.includes("ambiguous_lexical_token");
  const hasProtectiveSingleTokenEvidence =
    tokenList.length === 1 && classifications.some((r) => PROTECTIVE_SINGLE_TOKEN_EVIDENCE_RULES_SET.has(r));
  const onlySoftAmbiguousNegatives = filterRules.every((r) => AMBIGUOUS_NAME_SOFT_NEGATIVES_SET.has(r));

  if (
    filterRules.length > 0 &&
    positiveReasons.length === 0 &&
    !((hasAmbiguousNameEvidence || hasProtectiveSingleTokenEvidence) && onlySoftAmbiguousNegatives)
  ) {
    return filterResult(reasons, filterRules, weights, reviewThreshold, classifications);
  }

  /*
   * REPRESENTATION DEFECT #1 -- ORACLE DEVIATION #8 (AG, 2026-08-10).
   *
   * The known-given-name lookup used to live INSIDE the TWO_NAME_RE branch
   * below, which is unreachable for `Surname, Given` input because the
   * LAST_FIRST_RE branch returns first. Same person, two spellings, two
   * different evidence records:
   *
   *   Christopher Cobb    strong_name_structure + known_personal_name_token
   *   Cobb, Christopher   surname_given_structure                  <- nothing
   *
   * `christopher`, `nelly`, `tamara` and `andrew` are ALL already in
   * KNOWN_GIVEN_NAMES. The lexicon has the answer and the branch never
   * asked. That is a REPRESENTATION defect, not a scoring judgment: the
   * evidence exists, is already trusted for the other spelling, and simply
   * never got attached. Hoisting the lookup above both branches makes one
   * fact reach the candidate regardless of name ordering.
   *
   * NOT a new heuristic and NOT a dictionary widening -- KNOWN_GIVEN_NAMES
   * is untouched. Nothing here consults a new source.
   *
   * DEVIATION CLASSIFICATION: correctness / representation consistency.
   * Python's `score_candidate_quality()` shares the branch order, so this
   * diverges from the oracle deliberately. It is recorded here and pinned by
   * verify/last-first-name-evidence-verification.ts, whose load-bearing half
   * asserts that first-last spellings are byte-identical to before.
   *
   * BLAST RADIUS, measured rather than assumed -- see that suite:
   *   score            94 -> 99 (clamped) for an affected candidate
   *   status/label     unchanged (both sides are already Strong / ToReview)
   *   categories       gain `known_personal_name_token`, so
   *                    hasKnownNameEvidence() becomes true for these
   *   archetype        unchanged: every archetype gate that reads name
   *                    evidence also requires personTokenCount <= 1, and a
   *                    last-first candidate has two tokens
   *   review tier      may move null -> "needs-review" where identity
   *                    options exist -- the intended correction
   *   semanticTypeFor  unchanged (surname-given-structure already routed
   *                    these to `people`)
   *   residual gate    unchanged (rule 1 is single-token-only)
   *   confidence copy  "Likely name-shaped text. No name evidence was
   *                    found." -> "Almost certainly a person's name."
   *                    This is deviation #7 working correctly for the first
   *                    time on this population, not a regression.
   */
  let hasKnownGivenNameToken = false;
  for (const t of tokenSet) {
    if (KNOWN_GIVEN_NAMES_SET.has(t)) {
      hasKnownGivenNameToken = true;
      break;
    }
  }

  if (LAST_FIRST_RE.test(text)) {
    const structureReasons = ["surname_given_structure"];
    if (hasKnownGivenNameToken) structureReasons.push("known_personal_name_token");
    return scoredResult(
      {
        reasons: [...reasons, ...positiveReasons, ...classifications, ...structureReasons],
        explanation: "Strong surname, given-name structure",
        positiveReasons: [...positiveReasons, ...structureReasons],
        filterRules: classifications,
      },
      weights,
      reviewThreshold
    );
  }

  if (SURNAME_INITIALS_RE.test(text) || INITIAL_SURNAME_RE.test(text)) {
    return scoredResult(
      {
        reasons: [...reasons, ...positiveReasons, ...classifications, "initials_with_surname"],
        explanation: "Strong surname and initials structure",
        positiveReasons: [...positiveReasons, "initials_with_surname"],
        filterRules: classifications,
      },
      weights,
      reviewThreshold
    );
  }

  if (TWO_NAME_RE.test(text)) {
    // The lookup itself is hoisted above LAST_FIRST_RE (see deviation #8).
    // This branch's behaviour is byte-identical to before.
    const structureReasons = ["strong_name_structure"];
    if (hasKnownGivenNameToken) structureReasons.push("known_personal_name_token");

    if (isHeadingLike(occurrences, blocksById) && positiveReasons.length === 0) {
      return scoredResult(
        {
          reasons: [...reasons, ...positiveReasons, ...structureReasons, "heading_context"],
          explanation: "Name-like phrase, but heading context makes it less certain",
          positiveReasons: [...positiveReasons, ...structureReasons],
          filterRules: classifications,
        },
        weights,
        reviewThreshold
      );
    }
    return scoredResult(
      {
        reasons: [...reasons, ...positiveReasons, ...classifications, ...structureReasons],
        explanation: "Strong personal-name structure",
        positiveReasons: [...positiveReasons, ...structureReasons],
        filterRules: classifications,
      },
      weights,
      reviewThreshold
    );
  }

  if (tokenList.length === 1) {
    if (positiveReasons.length > 0) {
      return scoredResult(
        {
          reasons: [...reasons, ...positiveReasons, ...classifications, "single_name_candidate"],
          explanation: "Single-name candidate",
          positiveReasons,
          filterRules: classifications,
        },
        weights,
        reviewThreshold
      );
    }
    return scoredResult(
      {
        reasons: [...reasons, ...classifications, "single_token_reviewable_without_negative_evidence"],
        explanation: "Single-token candidate without strong negative evidence",
        filterRules: classifications,
      },
      weights,
      reviewThreshold
    );
  }

  return scoredResult(
    {
      reasons: [...reasons, ...positiveReasons, ...classifications, "weak_name_structure"],
      explanation: "Possible person candidate",
      suggestedType,
      positiveReasons,
      filterRules: classifications,
    },
    weights,
    reviewThreshold
  );
}
