/**
 * Domain-parity harness for Phase 6: runs the real
 * src/engines/EntityResolutionEngine.ts (RegexEntityResolutionEngine, via
 * src/engines/entity-resolution/resolution.ts) against every domain-parity
 * fixture and diffs the result against Python's own
 * expected/entity-groups.json + expected/ambiguity-proposals.json --
 * generated by scripts/export_fixtures.py calling
 * redactor.entity_resolution.build_entity_groups() /
 * build_ambiguous_matches() directly against the same candidates the
 * fixture's candidates.json/occurrences.json already capture.
 *
 * Compares (per Andrew's Phase 6 verification requirements): group
 * membership, group ordering, canonical/display labels, ambiguity
 * proposals, confidence values (both group-level and per-member), ordered
 * evidence/reasons, and candidate-to-group mappings.
 *
 * APPROVED DEVIATION (2026-07-28): entity-resolution-001 is compared
 * against a locally-defined CORRECTED expectation for entityGroups/
 * ambiguityProposals, not the raw Python-exported expected/*.json for
 * those two fields -- see fixtures/domain-parity/entity-resolution-001/
 * manifest.json's deviations[] entry and src/engines/entity-resolution/
 * resolution.ts's top doc comment ("DISCLOSED BEHAVIORAL CHANGE") for the
 * full trace. This fixture's own "Maria"/"Maria Alvarez" pairing turned
 * out to independently exercise the exact silent-auto-merge defect Andrew
 * traced from a real document ("Andrew"/"Andrew Goodloe") -- Python's own
 * oracle exhibits it too, so the raw expected/*.json files still capture
 * the ORIGINAL buggy Python output on purpose, as a historical record.
 * Every OTHER fixture (and every OTHER field of this one) is still
 * compared against the real Python export, unmodified.
 *
 * Run with:
 *   node --experimental-strip-types --experimental-loader ./verify/ts-loader.mjs verify/entity-resolution-parity.ts
 */

import { readFileSync } from "node:fs";
import { OoxmlDocumentParser } from "../src/io/DocumentParser.ts";
import { RegexDetectionEngine } from "../src/engines/DetectionEngine.ts";
import { RegexCandidateQualityEngine, buildDefaultScoringProfileSnapshot } from "../src/engines/CandidateQualityEngine.ts";
import { RegexEntityResolutionEngine } from "../src/engines/EntityResolutionEngine.ts";
import { loadSourceFile } from "./fixture-io.ts";

interface ExpectedEntityGroup {
  id: string;
  canonicalName: string;
  detectedType: string;
  memberKeys: string[];
  confidence: number;
  memberConfidences: Record<string, number>;
  reasons: string[];
}

interface ExpectedAmbiguityProposal {
  candidateKey: string;
  possibleGroups: Array<{ id: string; canonicalName: string; confidence: number }>;
}

function loadExpectedGroups(caseId: string): ExpectedEntityGroup[] {
  const data = JSON.parse(readFileSync(`fixtures/domain-parity/${caseId}/expected/entity-groups.json`, "utf8"));
  return data.entityGroups;
}

function loadExpectedAmbiguity(caseId: string): ExpectedAmbiguityProposal[] {
  const data = JSON.parse(readFileSync(`fixtures/domain-parity/${caseId}/expected/ambiguity-proposals.json`, "utf8"));
  return data.ambiguityProposals;
}

/**
 * entity-resolution-001's CORRECTED expectation for entityGroups/
 * ambiguityProposals -- see this file's top doc comment. The Jackson and
 * Goodloe groups are byte-identical to Python's own export (unaffected by
 * the fix, since both independently had 2 real spelling variants). The
 * Alvarez/Maria bucket no longer qualifies as a realized group (its bare
 * "Maria" member is no longer silently auto-merged in), so it is dropped
 * from entityGroups and "person:maria" gains its own ambiguity proposal
 * instead -- exactly the corrected behavior "person:andrew" already
 * demonstrated against Python's own (still-buggy) two-real-group case.
 * Values below were captured directly from a real, passing run of the
 * corrected pipeline against this fixture, not hand-computed.
 */
function correctedExpectedGroupsFor(caseId: string, pythonExpected: ExpectedEntityGroup[]): ExpectedEntityGroup[] {
  if (caseId !== "entity-resolution-001") return pythonExpected;
  return pythonExpected.filter((g) => g.id !== "person:alvarez:m");
}

function correctedExpectedAmbiguityFor(caseId: string, pythonExpected: ExpectedAmbiguityProposal[]): ExpectedAmbiguityProposal[] {
  if (caseId !== "entity-resolution-001") return pythonExpected;
  return [
    ...pythonExpected,
    {
      candidateKey: "person:maria",
      possibleGroups: [{ id: "person:alvarez:m", canonicalName: "Maria Alvarez", confidence: 90 }],
    },
  ];
}

const FIXED_SCORING_TIMESTAMP = "2026-07-27T00:00:00.000Z";

function arraysEqual(a: readonly unknown[], b: readonly unknown[]): boolean {
  return JSON.stringify(a) === JSON.stringify(b);
}

async function runFixture(caseId: string): Promise<boolean> {
  const file = loadSourceFile(caseId);
  const model = await new OoxmlDocumentParser().parse(file);
  const detection = new RegexDetectionEngine().detect(model);
  const profile = buildDefaultScoringProfileSnapshot(FIXED_SCORING_TIMESTAMP);
  const quality = new RegexCandidateQualityEngine().evaluate(model, detection, profile);
  const grouping = new RegexEntityResolutionEngine().propose(detection, quality);

  const expectedGroups = correctedExpectedGroupsFor(caseId, loadExpectedGroups(caseId));
  const expectedAmbiguity = correctedExpectedAmbiguityFor(caseId, loadExpectedAmbiguity(caseId));

  const problems: string[] = [];

  // --- Group ordering + membership + labels + confidence + reasons ---
  if (grouping.entityGroupProposals.length !== expectedGroups.length) {
    problems.push(
      `group count ${grouping.entityGroupProposals.length} != expected ${expectedGroups.length} ` +
        `(ts ids: ${grouping.entityGroupProposals.map((g) => g.groupId).join(",")}; expected ids: ${expectedGroups.map((g) => g.id).join(",")})`
    );
  } else {
    for (let i = 0; i < expectedGroups.length; i++) {
      const expected = expectedGroups[i]!;
      const actual = grouping.entityGroupProposals[i]!;
      if (actual.groupId !== expected.id) {
        problems.push(`group[${i}]: id "${actual.groupId}" != expected "${expected.id}" (ordering mismatch)`);
        continue;
      }
      if (actual.canonicalName !== expected.canonicalName) {
        problems.push(`${expected.id}: canonicalName "${actual.canonicalName}" != expected "${expected.canonicalName}"`);
      }
      if (actual.detectedType !== expected.detectedType) {
        problems.push(`${expected.id}: detectedType "${actual.detectedType}" != expected "${expected.detectedType}"`);
      }
      if (!arraysEqual(actual.candidateIds, expected.memberKeys)) {
        problems.push(`${expected.id}: candidateIds ${JSON.stringify(actual.candidateIds)} != expected memberKeys ${JSON.stringify(expected.memberKeys)}`);
      }
      if (actual.originalProposalConfidence !== expected.confidence) {
        problems.push(`${expected.id}: confidence ${actual.originalProposalConfidence} != expected ${expected.confidence}`);
      }
      if (JSON.stringify(actual.memberConfidences) !== JSON.stringify(expected.memberConfidences)) {
        problems.push(
          `${expected.id}: memberConfidences ${JSON.stringify(actual.memberConfidences)} != expected ${JSON.stringify(expected.memberConfidences)}`
        );
      }
      if (!arraysEqual(actual.reasons, expected.reasons)) {
        problems.push(`${expected.id}: reasons ${JSON.stringify(actual.reasons)} != expected ${JSON.stringify(expected.reasons)}`);
      }
    }
  }

  // --- Ambiguity proposals: ordering, candidate-to-options mapping, confidence ---
  if (grouping.ambiguityProposals.length !== expectedAmbiguity.length) {
    problems.push(
      `ambiguity count ${grouping.ambiguityProposals.length} != expected ${expectedAmbiguity.length} ` +
        `(ts: ${grouping.ambiguityProposals.map((p) => p.candidateId).join(",")}; expected: ${expectedAmbiguity.map((p) => p.candidateKey).join(",")})`
    );
  } else {
    for (let i = 0; i < expectedAmbiguity.length; i++) {
      const expected = expectedAmbiguity[i]!;
      const actual = grouping.ambiguityProposals[i]!;
      if (actual.candidateId !== expected.candidateKey) {
        problems.push(`ambiguity[${i}]: candidateId "${actual.candidateId}" != expected "${expected.candidateKey}" (ordering mismatch)`);
        continue;
      }
      const actualOptions = [...actual.candidateGroupOptions].sort((a, b) => (a.groupId < b.groupId ? -1 : a.groupId > b.groupId ? 1 : 0));
      const expectedOptions = [...expected.possibleGroups]
        .map((g) => ({ groupId: g.id, canonicalName: g.canonicalName, confidence: g.confidence }))
        .sort((a, b) => (a.groupId < b.groupId ? -1 : a.groupId > b.groupId ? 1 : 0));
      if (JSON.stringify(actualOptions) !== JSON.stringify(expectedOptions)) {
        problems.push(
          `${expected.candidateKey}: possibleGroups ${JSON.stringify(actualOptions)} != expected ${JSON.stringify(expectedOptions)}`
        );
      }
    }
  }

  const ok = problems.length === 0;
  console.log(
    `${ok ? "PASS" : "FAIL"}  ${caseId}  (expected groups: ${expectedGroups.length}, ts groups: ${grouping.entityGroupProposals.length}, ` +
      `expected ambiguous: ${expectedAmbiguity.length}, ts ambiguous: ${grouping.ambiguityProposals.length}, problems: ${problems.length})`
  );
  for (const p of problems) console.log(`    MISMATCH: ${p}`);
  if (caseId === "entity-resolution-001") {
    console.log("    (compared against a CORRECTED expectation, not raw Python export -- see manifest.json deviations[] and this file's top doc comment)");
  }

  return ok;
}

async function main(): Promise<void> {
  const fixtureCases = [
    "synthetic-transcript-001",
    "run-split-name-001",
    "field-codes-001",
    "drawing-objects-001",
    "hyperlink-001",
    "nested-table-001",
    "footer-001",
    "diacritics-001",
    "comments-001",
    "tracked-changes-001",
    "text-box-001",
    "content-control-001",
    "entity-resolution-001",
  ];

  const results: boolean[] = [];
  for (const caseId of fixtureCases) {
    results.push(await runFixture(caseId));
  }
  const passCount = results.filter(Boolean).length;
  console.log(`\n${passCount}/${results.length} fixtures fully match Python entity resolution`);
  process.exitCode = passCount === results.length ? 0 : 1;
}

main();
