/**
 * Domain-parity harness for Phase 5: runs the real
 * src/engines/CandidateQualityEngine.ts (RegexCandidateQualityEngine, via
 * src/engines/quality/scoring.ts) against every domain-parity fixture and
 * diffs the result against Python's own expected/candidates.json quality
 * fields (`quality`, `qualityStatus`, `candidateScore`, `qualityReasons`) --
 * generated by scripts/export_fixtures.py calling
 * redactor.candidate_quality.apply_candidate_quality() directly against the
 * same detection output the fixture's candidates.json/occurrences.json
 * already capture.
 *
 * This harness only scores candidates the real RegexDetectionEngine ALSO
 * found (see verify/detection-parity.ts, which already establishes 12/12
 * candidate/occurrence parity for body/header/footer content). A candidate
 * Python never detected has no expected quality data to compare against by
 * construction -- reported separately as "no expected data", not a failure.
 *
 * Run with:
 *   node --experimental-strip-types --experimental-loader ./verify/ts-loader.mjs verify/quality-parity.ts
 */

import { readFileSync } from "node:fs";
import { OoxmlDocumentParser } from "../src/io/DocumentParser.ts";
import { RegexDetectionEngine } from "../src/engines/DetectionEngine.ts";
import { RegexCandidateQualityEngine, buildDefaultScoringProfileSnapshot } from "../src/engines/CandidateQualityEngine.ts";
import { loadSourceFile } from "./fixture-io.ts";

interface ExpectedQualityCandidate {
  key: string;
  quality: string;
  qualityStatus: string;
  candidateScore: number;
  qualityReasons: string[];
}

function loadExpectedCandidates(caseId: string): ExpectedQualityCandidate[] {
  const data = JSON.parse(readFileSync(`fixtures/domain-parity/${caseId}/expected/candidates.json`, "utf8"));
  return data.candidates;
}

// Python's status vocabulary ("To Review"/"Unlikely") mapped onto TS's
// existing Recommendation type ("ToReview"/"Unlikely") -- same two-way
// axis, different string spelling (see scoring.ts's ScoredQuality doc
// comment).
function expectedStatusToRecommendation(status: string): string {
  return status === "To Review" ? "ToReview" : status;
}

const FIXED_SCORING_TIMESTAMP = "2026-07-27T00:00:00.000Z";

async function runFixture(caseId: string): Promise<boolean> {
  const file = loadSourceFile(caseId);
  const model = await new OoxmlDocumentParser().parse(file);
  const detection = new RegexDetectionEngine().detect(model);
  const profile = buildDefaultScoringProfileSnapshot(FIXED_SCORING_TIMESTAMP);
  const quality = new RegexCandidateQualityEngine().evaluate(model, detection, profile);

  const expectedCandidates = loadExpectedCandidates(caseId);
  const expectedByKey = new Map(expectedCandidates.map((c) => [c.key, c]));
  const tsCandidateIds = new Set(detection.candidates.map((c) => c.id));

  const mismatches: string[] = [];
  const matched: string[] = [];
  const noExpectedData: string[] = [];

  for (const candidate of detection.candidates) {
    const expected = expectedByKey.get(candidate.id);
    if (!expected) {
      // Not one of Python's own candidates (e.g. a comment/tracked-deletion/
      // content-control extra -- see detection-parity.ts) -- no ground
      // truth to compare quality against.
      noExpectedData.push(candidate.id);
      continue;
    }
    const assessment = quality.assessmentByCandidate[candidate.id];
    const score = quality.scoreByCandidate[candidate.id];
    const recommendation = quality.recommendationByCandidate[candidate.id];
    if (!assessment) {
      mismatches.push(`${candidate.id}: no assessment produced`);
      continue;
    }

    const fieldErrors: string[] = [];
    if (assessment.quality !== expected.quality) {
      fieldErrors.push(`quality "${assessment.quality}" != expected "${expected.quality}"`);
    }
    if (recommendation !== expectedStatusToRecommendation(expected.qualityStatus)) {
      fieldErrors.push(`status "${recommendation}" != expected "${expected.qualityStatus}"`);
    }
    if (score !== expected.candidateScore) {
      fieldErrors.push(`score ${score} != expected ${expected.candidateScore}`);
    }
    if (JSON.stringify(assessment.reasons) !== JSON.stringify(expected.qualityReasons)) {
      fieldErrors.push(`reasons ${JSON.stringify(assessment.reasons)} != expected ${JSON.stringify(expected.qualityReasons)}`);
    }

    if (fieldErrors.length > 0) {
      mismatches.push(`${candidate.id}: ${fieldErrors.join("; ")}`);
    } else {
      matched.push(candidate.id);
    }
  }

  // Any expected candidate Python scored that this run's detection didn't
  // even produce is a detection-layer gap, not a quality-layer one --
  // already tracked by detection-parity.ts. Not re-reported as a failure
  // here to avoid double-counting across the two harnesses.
  const missingFromDetection = [...expectedByKey.keys()].filter((k) => !tsCandidateIds.has(k));

  const ok = mismatches.length === 0;
  console.log(
    `${ok ? "PASS" : "FAIL"}  ${caseId}  (expected: ${expectedCandidates.length}, matched: ${matched.length}, ` +
      `mismatches: ${mismatches.length}, no-expected-data: ${noExpectedData.length}, missing-from-detection: ${missingFromDetection.length})`
  );
  for (const m of mismatches) console.log(`    MISMATCH: ${m}`);
  for (const m of noExpectedData) console.log(`    (no expected quality data, approved detection-layer extra) ${m}`);
  for (const m of missingFromDetection) console.log(`    (tracked by detection-parity.ts, not re-reported here) ${m}`);

  return ok;
}

async function main(): Promise<void> {
  const fixtureCases = [
    "synthetic-transcript-001",
    "run-split-name-001",
    "field-codes-001",
    "drawing-objects-001",
    "hyperlink-001",
    "nested-table-001",
    "footer-001",
    "diacritics-001",
    "comments-001",
    "tracked-changes-001",
    "text-box-001",
    "content-control-001",
  ];

  const results: boolean[] = [];
  for (const caseId of fixtureCases) {
    results.push(await runFixture(caseId));
  }
  const passCount = results.filter(Boolean).length;
  console.log(`\n${passCount}/${results.length} fixtures fully match Python quality scoring`);
  process.exitCode = passCount === results.length ? 0 : 1;
}

main();
