/**
 * contextual-lexicons.data.ts -- module-owned vocabulary for the Contextual
 * Person Evidence pass (AG, 2026-08-05).
 *
 * ADDITIVE, NOT A PARITY DICTIONARY. This follows the SENTENCE_CONTEXT_TOKENS
 * precedent (entity-resolution/identity-cleanup.ts) and DOCUMENT_NOISE_TOKENS
 * (normalization/normalization.ts): a small curated list owned by the one pass
 * that reads it, deliberately NOT merged into quality-dictionaries.data.ts.
 *
 * WHY IT MUST STAY SEPARATE. quality-dictionaries.data.ts is generated by
 * dumping the live Python module (scripts/generate_quality_dictionaries.py)
 * and is diffed field-for-field by verify/quality-parity.ts. Anything added
 * to it either breaks parity or has to be re-exported from Python first.
 * These lists have no Python counterpart at all -- there is no oracle to
 * diverge from -- so they belong to this module.
 *
 * WHAT THESE LISTS ARE FOR. Every rule in this pass asks a question about
 * GRAMMATICAL ROLE, never about spelling. That means the vocabulary here
 * describes the words AROUND a candidate, never the candidate itself. No
 * entry below is ever tested against candidate text -- if a future rule
 * wants to do that, it belongs in the lexical layer, not here.
 *
 * INFLECTION. Verb lists carry base forms only. matchesVerb() below applies
 * a deliberately small suffix tolerance (-s, -es, -d, -ed, -ing) rather than
 * enumerating conjugations, because an over-long list is harder to audit than
 * a short list plus one visible rule. Irregular past tenses that matter are
 * listed explicitly (wrote, said, sent, met, left, took, gave).
 */

/**
 * Verbs whose SUBJECT is normally a person: "Jordan approved the request."
 *
 * DELIBERATELY EXCLUDES verbs that institutions, systems and documents
 * perform just as naturally -- "begins", "requires", "includes", "shows",
 * "contains", "applies". Those are exactly the shapes that would let
 * "Fall enrollment begins" or "Section 4 requires" mint person evidence, and
 * this rule family is only as safe as this exclusion. When adding an entry,
 * the test is not "can a person do this?" but "would a non-person subject
 * read as odd?"
 */
export const HUMAN_ACTION_VERBS: readonly string[] = [
  "acknowledge", "advise", "agree", "answer", "apologize", "apply", "approve",
  "ask", "assign", "attend", "authorize", "call", "cancel", "certify", "chair",
  "clarify", "comment", "complain", "complete", "confirm", "consent", "consult",
  "contact", "decide", "decline", "delegate", "deny", "disagree", "email",
  "emphasize", "enroll", "escalate", "explain", "file", "flag", "follow",
  "forward", "graduate", "grant", "greet", "hire", "initial", "inquire",
  "instruct", "interview", "join", "leave", "mention", "meet", "note", "notify",
  "object", "observe", "offer", "phone", "promise", "propose", "recommend",
  "recuse", "refer", "remind", "reply", "report", "request", "resign",
  "respond", "retire", "review", "revise", "schedule", "sign", "state",
  "submit", "suggest", "supervise", "teach", "thank", "transfer", "verify",
  "volunteer", "vote", "withdraw", "write",
  // Irregular pasts that the suffix tolerance below cannot reach.
  "wrote", "said", "sent", "met", "left", "took", "gave", "spoke", "began",
  "held", "taught", "chose", "kept", "told",
];

/**
 * Verbs whose OBJECT is normally a person: "Contact Jordan.", "Email Alex."
 *
 * Weaker than the subject family on purpose -- an imperative "Review Jordan"
 * is genuinely ambiguous in a document that also contains a file named
 * Jordan -- so the weight assigned to this rule is the lowest in the family.
 */
export const DIRECTED_AT_PERSON_VERBS: readonly string[] = [
  "ask", "assign", "brief", "cc", "call", "consult", "contact", "copy",
  "email", "inform", "invite", "message", "notify", "page", "phone", "reach",
  "remind", "text", "thank", "tell", "welcome",
  "asked", "told", "met", "emailed", "called", "thanked", "reminded",
];

/**
 * Verbs of speaking, writing and authorship. Overlaps HUMAN_ACTION_VERBS by
 * design -- "said" and "wrote" are both. evaluateOccurrence() resolves the
 * overlap by letting attribution WIN and suppressing the weaker subject rule
 * for the same span, so one linguistic fact is never counted twice. That
 * suppression is the diminishing-returns principle applied at its source,
 * which is cheaper and more explainable than discounting it afterwards.
 */
export const ATTRIBUTION_VERBS: readonly string[] = [
  "said", "says", "wrote", "writes", "stated", "states", "noted", "notes",
  "mentioned", "mentions", "added", "adds", "explained", "explains",
  "reported", "reports", "replied", "replies", "commented", "comments",
  "confirmed", "confirms", "asked", "asks", "observed", "observes",
  "argued", "argues", "indicated", "indicates", "advised", "advises",
];

/** Phrases that attribute what FOLLOWS to the named person: "according to
 *  Alex", "per Casey", "signed by Jordan". Matched against the text BEFORE
 *  the candidate. */
export const ATTRIBUTION_LEAD_INS: readonly string[] = [
  "according to", "per", "signed by", "written by", "authored by",
  "submitted by", "prepared by", "reported by", "as told to", "quoted by",
  "confirmed by", "approved by", "reviewed by", "sent by", "requested by",
];

/**
 * Nouns that unambiguously denote a person occupying a role. Used by the
 * coordination rule ("the chair and Casey") and by the full-name-with-role
 * anchor ("Jordan Lee, Director of Finance").
 *
 * DELIBERATELY EXCLUDES unit and body names -- "committee", "board",
 * "office", "department", "services". Those denote groups, and "Jordan and
 * the committee" says nothing about Jordan being a person that the sentence
 * did not already say. Keeping them out is what stops this rule from firing
 * on organizational prose.
 */
export const PERSON_ROLE_NOUNS: readonly string[] = [
  "administrator", "advisor", "adviser", "analyst", "assistant", "associate",
  "attorney", "chair", "chairman", "chairwoman", "chancellor", "clerk",
  "coach", "consultant", "coordinator", "counsel", "counselor", "dean",
  "delegate", "designee", "director", "doctor", "editor", "engineer",
  "examiner", "faculty member", "fellow", "instructor", "interviewer",
  "investigator", "lead", "lecturer", "liaison", "manager", "nurse",
  "officer", "official", "paralegal", "partner", "physician", "president",
  "principal", "professor", "provost", "recruiter", "registrar",
  "representative", "reviewer", "secretary", "specialist", "sponsor",
  "steward", "student", "superintendent", "supervisor", "teacher",
  "technician", "treasurer", "trustee", "tutor", "vice president",
  "witness",
];

/** Openers that mark what follows as an addressee rather than a mention.
 *  Matched at the END of the text before the candidate. */
export const DIRECT_ADDRESS_OPENERS: readonly string[] = [
  "hi", "hello", "hey", "dear", "good morning", "good afternoon",
  "good evening", "greetings", "thanks", "thank you", "attn", "attention",
  "cc", "to", "re",
];

/** Second-person continuations that mark a preceding name as an addressee:
 *  "Casey, could you review this?" Matched at the START of the text after
 *  the candidate, once a comma has been consumed. */
export const DIRECT_ADDRESS_FOLLOW_ONS: readonly string[] = [
  "could you", "can you", "would you", "will you", "please", "do you",
  "are you", "did you", "have you", "if you", "when you", "let me know",
  "any chance you", "thanks for", "thank you for",
];

/** Tail words that mark a comma-attached phrase as an ORGANIZATION rather
 *  than a role -- "Jordan Lee, Enrollment Services". Kept separate from
 *  PERSON_ROLE_NOUNS because the two anchor rules carry different weights
 *  and a reviewer reads them differently. */
export const ORGANIZATION_TAIL_TOKENS: readonly string[] = [
  "administration", "affairs", "agency", "association", "bureau", "college",
  "commission", "company", "corporation", "council", "department", "division",
  "foundation", "group", "hospital", "inc", "institute", "llc", "llp",
  "ltd", "office", "organization", "program", "resources", "school",
  "services", "society", "system", "team", "unit", "university",
];

const SUFFIXES = ["s", "es", "d", "ed", "ing"];

/**
 * Base-form membership test with the small suffix tolerance documented in
 * this file's header. Case-insensitive; the caller is responsible for having
 * already lowercased, this only guards against a stray capital.
 */
export function matchesVerb(word: string, lexicon: ReadonlySet<string>): boolean {
  const w = word.toLowerCase().replace(/[^a-z]/g, "");
  if (!w) return false;
  if (lexicon.has(w)) return true;
  for (const suffix of SUFFIXES) {
    if (!w.endsWith(suffix)) continue;
    const stem = w.slice(0, w.length - suffix.length);
    if (stem.length < 3) continue;
    if (lexicon.has(stem)) return true;
    // "replied" -> "reply", "notified" -> "notify": the -y/-ie alternation is
    // common enough among these verbs to be worth one explicit rule rather
    // than duplicate entries.
    if (stem.endsWith("i") && lexicon.has(`${stem.slice(0, -1)}y`)) return true;
    // "approving" -> "approve", "scheduling" -> "schedule".
    if (suffix === "ing" && lexicon.has(`${stem}e`)) return true;
  }
  return false;
}
