#!/usr/bin/env python3
"""
generate_domain_terminology_pack.py -- generates the production runtime assets
for provenance-carrying DOMAIN TERMINOLOGY reference packs (AG, 2026-08-10).

    python3 scripts/generate_domain_terminology_pack.py finance       <csv>
    python3 scripts/generate_domain_terminology_pack.py legal         <csv>
    python3 scripts/generate_domain_terminology_pack.py employment_hr <csv>
    python3 scripts/generate_domain_terminology_pack.py government_public_admin <csv>

ONE GENERATOR, FOUR PACKS -- AND WHY THAT IS NOT PREMATURE
    `generate_higher_ed_terminology.py` is a per-asset script, matching the
    repo's convention (census, GNIS, quality dictionaries each have their
    own). This one is shared because the Finance/Accounting/Tax and Legal
    packs arrived together with the SAME row model, and writing the identical
    interning/TSV emitter twice would guarantee the two copies drift. The
    Employment/HR pack (AG, 2026-08-10) arrived third with that same row
    model and is generated here for the same reason -- it added a PACKS entry
    and nothing else structural, which is the outcome this shape was for.
    What differs between them is data-shaped and lives in PACKS below:

        normalization policy   (per source methodology -- see below)
        sub-domain column      (finance has FINANCE/ACCOUNTING/TAX; legal none)
        extra columns          (finance: source_id, acronym, acronym_expansion)
        provenance merging     (legal merges co-attesting sources into one row
                                with `|`-separated fields; finance does not)
        licensing table        (employment_hr ships per-source tier/licence/
                                retrieval columns; emitted as a side table
                                rather than folded into `notes`, so the
                                shared row contract is untouched)
        authority table        (government_public_admin names the authority
                                behind each machine source-family key; same
                                side-table treatment, same reason)
        constant columns       (government_public_admin's `jurisdiction` never
                                varies, so it is one exported constant rather
                                than 412 copies -- and the generator STOPS if
                                a later revision makes it vary, because that
                                would be a shared-contract change)

    The Government/Public Administration pack (AG, 2026-08-10) arrived fourth
    on the same row model. It needed two new PACKS keys and no change to the
    row contract, the intern tables, or any other pack's shipped asset -- which
    is the property this shape exists to keep while several packs are being
    integrated concurrently.

    Higher-ed is deliberately NOT regenerated by this script. Its asset is
    shipped, verified and shaped slightly differently; migrating it is a
    separate, mechanical change and there was no reason to couple the two.

NORMALIZATION -- REPRODUCED, NOT REINVENTED
    `normalized_term` in each CSV was produced by that dataset's own
    generator. This script re-derives it from `term` with the rules its
    methodology documents and ASSERTS equality on EVERY row. If an assertion
    fires, the TypeScript normalizer in the corresponding provider -- a second
    implementation of the same steps -- would silently disagree with the
    shipped keys and lookups would quietly miss. That is a class of bug no
    type checker catches, so it is caught here instead.

    Verified at time of writing: finance 710/710, legal 445/445,
    employment_hr 267/267, government_public_admin 412/412.

    finance (docscrub_finance_accounting_tax_methodology.md, §Normalization)
        1. NFKC
        2. curly quotes -> ASCII
        3. unicode dashes/minus -> ASCII hyphen
        4. casefold
        5. collapse whitespace, trim
        6. PUNCTUATION PRESERVED -- `Form 10-K` must not become `Form 10K`.
           Hyphenation alternates are shipped as explicit derived rows.

    legal (docscrub_legal_terms_methodology.md, §Deterministic normalization)
        steps 1-5 identical, then
        6. remove spaces immediately around `/` and `-`
        7. all other punctuation preserved

    employment_hr (docscrub_employment_hr_methodology.md, §Normalization)
        the SAME six steps as finance, arrived at independently by that
        pack's own methodology. It is aliased rather than merged below,
        because two packs agreeing today is not a reason to give them one
        normalizer they would then have to share forever: a later revision of
        either methodology must be able to move without dragging the other.
        The alias is asserted against all 267 shipped keys like every other.

    government_public_admin (docscrub_government_public_admin_methodology.md,
                             §Deterministic normalization)
        the SAME seven steps as legal, arrived at independently, and aliased
        rather than merged for the same reason. NOTE that step 6 is INERT on
        the v1 data -- no shipped row has a space next to `/` or `-`, so the
        finance policy would reproduce all 412 keys as well. It is implemented
        because the contract says so, and the verification suite exercises it
        with a synthetic input so it cannot rot unnoticed.

    All four differ from higher-ed (every non-alphanumeric run -> SPACE) and
    from census (punctuation stripped to nothing). Those differences are forced
    by the data, are documented in each provider, and are NOT to be unified.

WHAT A MATCH LICENSES
    Exactly one sentence: "this phrase is attested <domain> terminology."
    NOT a semantic type, NOT a Keep, and NOT evidence of non-personhood. The
    Legal pack contains `Doe`, `Judge`, `Levy`, `answer`, `brief` and
    `record`; the Finance pack contains `basis`, `trust`, `security`,
    `interest` and `margin`; the Employment/HR pack contains `Grade`,
    `detail`, `series`, `transfer` and `appeal`. Several are Census-attested
    personal names. Any consumer that reads membership as a person-suppressor
    reintroduces the exact failure the Census experiment already measured and
    rejected.

WHY EVERY ROW SURVIVES, AND WHY LEGAL'S MERGED ROWS ARE UN-MERGED
    52 finance keys are attested by more than one row -- `account balance` by
    Treasury/USSGL as ACCOUNTING and by the FDIC as FINANCE. The Legal pack
    instead merges co-attesting sources into ONE row with `|`-separated
    source_name/url/family/authority (4 rows do this). This script EXPANDS
    those back into one attestation per source, so both packs present the
    identical runtime shape: a key maps to a list of single-source
    attestations. That is un-merging what the pack merged, not fabrication --
    the segment counts are asserted equal across all four piped columns.

OUTPUT
    src/engines/knowledge/finance-accounting-tax-terminology.data.ts
    src/engines/knowledge/legal-terminology.data.ts
    src/engines/knowledge/employment-hr-terminology.data.ts
    src/engines/knowledge/government-public-admin-terminology.data.ts

    Format is `DomainReferencePackAsset` from
    src/engines/knowledge/DomainReferenceEvidence.ts -- intern tables plus a
    TAB-separated row block. Intern-table ORDER IS LOAD-BEARING.
"""

import csv
import re
import sys
import unicodedata
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

QUOTES = {"\u2018": "'", "\u2019": "'", "\u201a": "'", "\u201b": "'",
          "\u201c": '"', "\u201d": '"', "\u201e": '"', "\u201f": '"'}
DASHES = {"\u2010": "-", "\u2011": "-", "\u2012": "-", "\u2013": "-",
          "\u2014": "-", "\u2015": "-", "\u2212": "-"}


def _base(text):
    """Steps 1-5, shared by both packs' documented policies."""
    text = unicodedata.normalize("NFKC", text)
    text = "".join(QUOTES.get(c, DASHES.get(c, c)) for c in text)
    text = text.casefold()
    return re.sub(r"\s+", " ", text).strip()


def normalize_finance(term):
    return _base(term)


def normalize_legal(term):
    return re.sub(r"\s*([/-])\s*", r"\1", _base(term))


def normalize_employment_hr(term):
    """Deliberately a separate name for the same six steps -- see the module
    docstring. Aliasing documents that the agreement is a measured fact about
    two methodologies, not a shared dependency between two packs."""
    return _base(term)


def normalize_government(term):
    """Same seven steps the Legal methodology documents, arrived at
    independently by the Government/Public Administration methodology
    (§Deterministic normalization, steps 1-8). Separately named for the same
    reason `normalize_employment_hr` is: two methodologies agreeing today is a
    measured fact, not a shared dependency that would force a later revision
    of one to drag the other.

    STEP 6 IS INERT ON THE v1 DATA and is implemented anyway. No shipped
    government row contains a space adjacent to `/` or `-`, so the finance
    policy would reproduce all 412 keys too. The contract is what is
    implemented, not the accident of what this snapshot happens to exercise --
    a v2 row written `pre - award` must key the same as `pre-award`, and the
    verification suite pins that behaviour with a synthetic input rather than
    letting it rot undetected."""
    return re.sub(r"\s*([/-])\s*", r"\1", _base(term))


PACKS = {
    "finance": {
        "family": "finance-accounting-tax",
        "version": "docscrub-finance-accounting-tax-terminology/2026-08-10",
        "out": "src/engines/knowledge/finance-accounting-tax-terminology.data.ts",
        "prefix": "FINANCE_TAX",
        "consumer": "FinanceAccountingTaxEvidence",
        "normalize": normalize_finance,
        "sub_domain_column": "source_domain",
        "merged_provenance": False,
        "noun": "finance/accounting/tax terminology",
        "sources_blurb": (
            "IRS, SEC/Investor.gov, CFPB, CFTC, Federal Reserve, FDIC and the\n"
            " * U.S. Treasury Standard General Ledger (USSGL). Federal public glossaries\n"
            " * only -- FASB/GASB/AICPA vocabularies were reviewed and deliberately NOT\n"
            " * ingested for copyright reasons, and no commercial dictionary was scraped.\n"
            " * Term labels and provenance only; no source definitions are reproduced."
        ),
        "collision_blurb": (
            "`basis`, `interest`, `security`, `margin`, `position`,\n"
            " * `appeal`, `stock`, `gain` and `loss` are all attested here AND are\n"
            " * ordinary English, legal terminology, or Census-attested personal names.\n"
            " * `ADR` is attested here as an American Depositary Receipt and in the Legal\n"
            " * pack as Alternative Dispute Resolution -- same string, both correct"
        ),
    },
    "legal": {
        "family": "legal-terminology",
        "version": "docscrub-legal-terminology/2026-08-10",
        "out": "src/engines/knowledge/legal-terminology.data.ts",
        "prefix": "LEGAL",
        "consumer": "LegalTerminologyEvidence",
        "normalize": normalize_legal,
        "sub_domain_column": None,
        "merged_provenance": True,
        "noun": "legal terminology",
        "sources_blurb": (
            "the U.S. Courts/AO federal glossary, DOJ Justice 101, the Ninth\n"
            " * Circuit, federal bankruptcy courts, PACER/CM-ECF, N.D. Cal. ADR and\n"
            " * filing-under-seal terminology, the SEC, USPTO, FTC and EEOC, plus\n"
            " * California superior-court self-help glossaries. Cornell LII was\n"
            " * researched and REJECTED (noncommercial/share-alike licence), and no\n"
            " * commercial legal dictionary was scraped. Term labels and provenance\n"
            " * only; state-judiciary glossary definitions are explicitly not copied."
        ),
        "collision_blurb": (
            "`answer`, `brief`, `file`, `record`, `motion`, `counsel`,\n"
            " * `court`, `Doe`, `Judge` and `Levy` are all attested here AND are\n"
            " * ordinary English or Census-attested personal names"
        ),
    },
    "employment_hr": {
        "family": "employment-hr-terminology",
        "version": "docscrub-employment-hr-terminology/2026-08-10",
        "out": "src/engines/knowledge/employment-hr-terminology.data.ts",
        "prefix": "EMPLOYMENT_HR",
        "consumer": "EmploymentHrEvidence",
        "normalize": normalize_employment_hr,
        # The pack's own sub-domain axis. Kept so an evidence trace can say
        # "EEOC equal-employment-opportunity terminology" rather than the
        # uselessly broad "HR terminology".
        "sub_domain_column": "category",
        "merged_provenance": False,
        # This pack ships per-row source_tier / license_status /
        # retrieval_date. They are constant per source family (asserted
        # below), so they are emitted ONCE per family as a side table rather
        # than 267 times inside `notes` -- which would have meant rewriting
        # provenance prose the source wrote, and would have put licensing
        # into a field reviewers read.
        "licensing_columns": True,
        "noun": "employment/HR terminology",
        "sources_blurb": (
            "OPM (general personnel policy, classification, pay/leave and\n"
            " * performance management), DOL/WHD (FMLA), EEOC, NLRB, FLRA, MSPB, OSHA\n"
            " * and EBSA. US federal public glossaries only. O*NET/SOC is CC BY 4.0 and\n"
            " * was researched but DELIBERATELY NOT bulk-ingested in v1: the occupational\n"
            " * title universe would have turned an HR-ADMINISTRATION pack into a\n"
            " * role/title dictionary and multiplied name collisions. It is recorded as a\n"
            " * separately measured future expansion, not silent scope growth. No\n"
            " * commercial HR dictionary and no vendor HRIS vocabulary was ingested;\n"
            " * term labels and provenance only, no source definitions reproduced."
        ),
        "collision_blurb": (
            "`Grade`, `detail`, `series`, `transfer`, `appeal`,\n"
            " * `beneficiary`, `participant` and the acronyms `ADA`, `EEO`, `FMLA`,\n"
            " * `PIP`, `PPP`, `SPD` are all attested here AND are ordinary English,\n"
            " * legal or finance terminology, or Census-attested personal names"
        ),
    },
    "government_public_admin": {
        "family": "government-public-admin",
        "version": "docscrub-government-public-admin-terminology/2026-08-10",
        "out": "src/engines/knowledge/government-public-admin-terminology.data.ts",
        "prefix": "GOVERNMENT",
        "consumer": "GovernmentPublicAdminEvidence",
        "normalize": normalize_government,
        # The pack's own sub-domain axis, and the load-bearing one for this
        # family: it is what separates `OFFICIAL_ORGANIZATION` (29 rows, named
        # federal bodies) from the general administrative vocabulary. An
        # evidence trace can then say "NARA records-management terminology" or
        # "FAR procurement terminology" rather than the useless "government".
        "sub_domain_column": "category",
        "merged_provenance": False,
        # tier column is absent from this pack's CSV; licence and retrieval
        # date are present and constant per source family (asserted below).
        "licensing_columns": True,
        # 1:1 with source_family in this dataset (7 families, 7 authorities),
        # so it is emitted once per family rather than 412 times. Kept because
        # `NARA_RM` is a machine key and "National Archives and Records
        # Administration" is what an audit trail has to be able to print.
        "authority_column": "source_authority",
        # Constant across every v1 row. Asserted single-valued and emitted as
        # ONE pack-level constant rather than a 412-times-repeated row column,
        # which would have meant widening the shared row contract -- and every
        # other pack's shipped asset with it -- to carry a fact that does not
        # vary. If a v2 adds state or local rows this must become a row
        # column; the assertion below is what will force that conversation.
        "jurisdiction_column": "jurisdiction",
        "noun": "government/public-administration terminology",
        "sources_blurb": (
            "the Federal Acquisition Regulation (Acquisition.gov Part 2),\n"
            " * NARA records-management key terms, Grants.gov, FOIA.gov/DOJ OIP, the\n"
            " * Office of the Federal Register, OPM classification, and a deliberately\n"
            " * small USA.gov official-organization slice. US federal public glossaries\n"
            " * only; deliberately federal-heavy, and NOT an exhaustive ontology of\n"
            " * government -- state and local administrative vocabulary is a documented\n"
            " * v1 gap, not an absence finding. Term labels and provenance only; no\n"
            " * source definitions are reproduced."
        ),
        "collision_blurb": (
            "`Band`, `Contractor`, `Grade`, `Notice`, `Record`,\n"
            " * `Risk`, `Role`, `Rule`, `Search`, `Series`, `State` and `Title` are all\n"
            " * attested here AND are ordinary English, Census-attested personal names,\n"
            " * or terminology in the legal / employment-HR / finance / higher-ed packs.\n"
            " * `Applicant`, `Contract`, `Claim`, `Disposition`, `Budget` and `Asset`\n"
            " * are attested here AND elsewhere, and both attestations are correct"
        ),
    },
}


def ts_string(value):
    escaped = (value.replace("\\", "\\\\").replace('"', '\\"')
                    .replace("\n", "\\n").replace("\r", "").replace("\t", "\\t"))
    return f'"{escaped}"'


def chunked_literal(parts, name, exported=True):
    """Emit a long string as concatenated chunks -- one huge source literal
    trips editors and some toolchains, and this costs nothing at runtime."""
    body = " +\n  ".join(ts_string(p) for p in parts)
    return f"{'export ' if exported else ''}const {name} =\n  {body};\n"


def main(pack_key, csv_path):
    if pack_key not in PACKS:
        raise SystemExit(f"unknown pack {pack_key!r}; expected one of {sorted(PACKS)}")
    pack = PACKS[pack_key]
    normalize = pack["normalize"]

    with open(csv_path, newline="", encoding="utf-8") as handle:
        source_rows = list(csv.DictReader(handle))
    if not source_rows:
        raise SystemExit(f"{csv_path}: no rows")

    # ---- NORMALIZATION PARITY. The whole point of generating rather than
    # hand-writing: if the documented policy does not reproduce the shipped
    # keys, stop, because the runtime normalizer implements that same policy.
    mismatches = [(r["term"], r["normalized_term"], normalize(r["term"]))
                  for r in source_rows if normalize(r["term"]) != r["normalized_term"]]
    if mismatches:
        for term, shipped, derived in mismatches[:20]:
            print(f"  NORMALIZATION MISMATCH {term!r}: csv={shipped!r} derived={derived!r}")
        raise SystemExit(f"{len(mismatches)} of {len(source_rows)} rows do not reproduce "
                         f"normalized_term under the documented policy -- refusing to generate.")

    # ---- Expand legal's `|`-merged provenance into one attestation per source.
    attestations = []
    for row in source_rows:
        names = [row["source_name"]]
        urls = [row["source_url"]]
        families = [row["source_family"]]
        authorities = [row["source_authority_level"]]
        if pack["merged_provenance"] and "|" in row["source_name"]:
            names = [s.strip() for s in row["source_name"].split("|")]
            urls = [s.strip() for s in row["source_url"].split("|")]
            families = [s.strip() for s in row["source_family"].split("|")]
            authorities = [s.strip() for s in row["source_authority_level"].split("|")]
            if not (len(names) == len(urls) == len(families) == len(authorities)):
                raise SystemExit(f"{row['term']!r}: piped provenance columns disagree on segment count "
                                 f"({len(names)}/{len(urls)}/{len(families)}/{len(authorities)})")
        sub_column = pack["sub_domain_column"]
        for name, url, family, authority in zip(names, urls, families, authorities):
            attestations.append({
                "normalized": row["normalized_term"],
                "term": row["term"],
                "hints": row["semantic_hint"].strip(),
                "sub_domain": (row.get(sub_column) or "").strip() if sub_column else "",
                "source": (name.strip(), url.strip(), family.strip(), authority.strip()),
                "source_id": (row.get("source_id") or "").strip(),
                "source_attested": row["source_attested"].strip().lower() == "true",
                "derived_variant": row["derived_variant"].strip().lower() == "true",
                "parent_term": (row.get("parent_term") or "").strip(),
                "risk": row["collision_risk"].strip(),
                "acronym": (row.get("acronym") or "").strip(),
                "acronym_expansion": (row.get("acronym_expansion") or "").strip(),
                "notes": (row.get("notes") or "").strip(),
            })

    # ---- LICENSING SIDE TABLE, for packs that ship licensing columns.
    # Asserted constant per source family: if a pack ever attaches two
    # different licences to one family, that is a real fact about the data
    # and the side-table shape is wrong for it -- stop rather than silently
    # keep whichever row sorted last.
    licensing = bool(pack.get("licensing_columns"))
    licensing_rows = []
    if licensing:
        by_family = {}
        for row in source_rows:
            family = row["source_family"].strip()
            entry = (row.get("source_tier", "").strip(),
                     row.get("license_status", "").strip(),
                     row.get("retrieval_date", "").strip())
            if by_family.setdefault(family, entry) != entry:
                raise SystemExit(f"source family {family!r} carries more than one "
                                 f"tier/licence/retrieval combination: "
                                 f"{by_family[family]} vs {entry}")
        licensing_rows = [(f, *by_family[f]) for f in sorted(by_family)]

    # ---- AUTHORITY SIDE TABLE. Same shape and same reasoning as the
    # licensing table: a value that is constant per source family is stored
    # once per family, not once per row. This one exists because a source
    # family is a machine key (`NARA_RM`, `FAR_PART_2`) and an audit trail has
    # to be able to name the authority behind it in words.
    authority_column = pack.get("authority_column")
    authority_rows = []
    if authority_column:
        by_family = {}
        for row in source_rows:
            family = row["source_family"].strip()
            authority = (row.get(authority_column) or "").strip()
            if by_family.setdefault(family, authority) != authority:
                raise SystemExit(f"source family {family!r} carries more than one authority: "
                                 f"{by_family[family]!r} vs {authority!r} -- a per-family side "
                                 f"table is the wrong shape for that and would drop one.")
        authority_rows = [(f, by_family[f]) for f in sorted(by_family)]

    # ---- PACK-LEVEL CONSTANT COLUMNS. A column that never varies is a fact
    # about the DATASET, not about a phrase, and is emitted once. The assert
    # is the point: the day a pack ships a second value here, this stops
    # rather than silently keeping whichever row it saw first, and whoever is
    # holding it has to decide to widen the shared row contract on purpose.
    constant_column = pack.get("jurisdiction_column")
    constant_value = None
    if constant_column:
        values = {(r.get(constant_column) or "").strip() for r in source_rows}
        if len(values) != 1:
            raise SystemExit(f"{constant_column} is not constant across the pack ({sorted(values)}) -- "
                             f"it can no longer be a pack-level constant and must become a row column "
                             f"in DomainReferencePackAsset, which changes every pack's asset.")
        constant_value = values.pop()

    # Sorted by key, then by original CSV order within a key -- stable output,
    # so a regeneration with unchanged input produces a byte-identical file.
    attestations.sort(key=lambda a: a["normalized"])

    # ---- Intern tables. ORDER IS LOAD-BEARING once shipped.
    hint_sets = sorted({a["hints"] for a in attestations})
    sub_domains = [""] + sorted({a["sub_domain"] for a in attestations} - {""})
    sources = sorted({a["source"] for a in attestations})
    strings = [""] + sorted(
        {a[k] for a in attestations for k in ("source_id", "parent_term", "acronym", "acronym_expansion", "notes")} - {""}
    )
    risks = ["LOW", "MEDIUM", "HIGH"]

    hint_index = {v: i for i, v in enumerate(hint_sets)}
    sub_index = {v: i for i, v in enumerate(sub_domains)}
    source_index = {v: i for i, v in enumerate(sources)}
    string_index = {v: i for i, v in enumerate(strings)}

    lines = []
    for a in attestations:
        if a["risk"] not in risks:
            raise SystemExit(f"{a['term']!r}: unexpected collision_risk {a['risk']!r}")
        if "\t" in a["term"] or "\t" in a["normalized"]:
            raise SystemExit(f"{a['term']!r}: TAB in a value would corrupt the row block")
        lines.append("\t".join([
            a["normalized"],
            a["term"],
            str(hint_index[a["hints"]]),
            str(sub_index[a["sub_domain"]]),
            str(source_index[a["source"]]),
            str(string_index[a["source_id"]]),
            "1" if a["source_attested"] else "0",
            "1" if a["derived_variant"] else "0",
            str(string_index[a["parent_term"]]),
            str(risks.index(a["risk"])),
            str(string_index[a["acronym"]]),
            str(string_index[a["acronym_expansion"]]),
            str(string_index[a["notes"]]),
        ]))

    keys = {a["normalized"] for a in attestations}
    multi = sum(1 for _, n in Counter(a["normalized"] for a in attestations).items() if n > 1)
    derived_count = sum(1 for a in attestations if a["derived_variant"])
    risk_counts = Counter(a["risk"] for a in attestations)
    domain_counts = Counter(a["sub_domain"] for a in attestations if a["sub_domain"])
    family_counts = Counter(a["source"][2] for a in attestations)

    P = pack["prefix"]
    domain_line = ("\n * SUB-DOMAINS: " + ", ".join(f"{k} {v}" for k, v in sorted(domain_counts.items())) + "."
                   if domain_counts else "")
    header = f'''/**
 * {Path(pack["out"]).name} -- GENERATED. DO NOT HAND-EDIT.
 *
 * Regenerate with:
 *     python3 scripts/generate_domain_terminology_pack.py {pack_key} <csv>
 * Source CSV is versioned at investigation/data/{Path(csv_path).name}.
 *
 * SOURCE: {pack["sources_blurb"]}
 *
 * CONTENT: {len(attestations)} attestation rows over {len(keys)} distinct
 * normalized terms. {multi} terms are attested by more than one row and every
 * such row is retained -- corroboration across independent source families is
 * evidence a future combination layer will want, and collapsing to a key set
 * would destroy it. {derived_count} rows are mechanically derived variants rather
 * than direct source labels. Collision risk: LOW {risk_counts["LOW"]},
 * MEDIUM {risk_counts["MEDIUM"]}, HIGH {risk_counts["HIGH"]}.{domain_line}
 *
 * THE ONE CLAIM A MATCH LICENSES: "this phrase is attested {pack["noun"]}."
 * Not a semantic type, not a Keep, and NOT evidence of non-personhood --
 * {pack["collision_blurb"]}.
 *
 * REPRESENTATION: `DomainReferencePackAsset` (see DomainReferenceEvidence.ts
 * for the column contract). Intern tables plus a TAB-separated row block,
 * sorted by normalized key then source order. Intern-table order is
 * load-bearing: regenerating with a different order invalidates every row.
 */

import type {{ DomainReferencePackAsset }} from "./DomainReferenceEvidence.js";

export const {P}_SOURCE = "{pack["version"]}";
export const {P}_ROW_COUNT = {len(attestations)};
export const {P}_TERM_COUNT = {len(keys)};

/** Pipe-separated hint combinations, verbatim from the source dataset.
 *  Index-addressed by row column 2. Order is load-bearing. */
const HINT_SETS: readonly string[] = [
{chr(10).join("  " + ts_string(v) + "," for v in hint_sets)}
];

/** Index-addressed by row column 3. Index 0 is "" -- no sub-domain. */
const SUB_DOMAINS: readonly string[] = [
{chr(10).join("  " + ts_string(v) + "," for v in sub_domains)}
];

/** Index-addressed by row column 4: [name, url, family, authorityLevel]. */
const SOURCES: readonly (readonly [string, string, string, string])[] = [
{chr(10).join("  [" + ", ".join(ts_string(x) for x in v) + "]," for v in sources)}
];

/** Shared pool for the sparse columns (source ids, parent terms, acronyms,
 *  acronym expansions, notes). Index 0 is "". */
const STRINGS: readonly string[] = [
{chr(10).join("  " + ts_string(v) + "," for v in strings)}
];

'''

    out_path = ROOT / pack["out"]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as out:
        out.write(header)
        per_piece = 200
        groups = [lines[i:i + per_piece] for i in range(0, len(lines), per_piece)]
        parts = ["\n".join(g) + ("\n" if n < len(groups) - 1 else "") for n, g in enumerate(groups)]
        out.write("/** One line per attestation row, TAB-separated. Columns, in order:\n"
                  " *  normalized, term, hintSetIdx, subDomainIdx, sourceIdx, sourceIdIdx,\n"
                  " *  sourceAttested(0|1), derivedVariant(0|1), parentIdx, riskIdx,\n"
                  " *  acronymIdx, acronymExpIdx, notesIdx */\n")
        out.write(chunked_literal(parts, "ROWS", exported=False))
        if licensing:
            out.write(f'''
/**
 * SOURCE LICENSING AND RETRIEVAL, one row per source family:
 *   [sourceFamily, sourceTier, licenseStatus, retrievalDate]
 *
 * `sourceTier` is "" for packs whose dataset ships no tier grade; the licence
 * and retrieval date are what every such pack carries and they are the two
 * that matter for redistribution.
 *
 * A SIDE TABLE, not a row column, for two reasons. These values are constant
 * per source family in the dataset (the generator asserts it), so per-row
 * storage would be {len(attestations)} copies of {len(licensing_rows)} facts. And
 * licensing is provenance ABOUT a dataset, not evidence about a phrase --
 * folding it into `notes` would put it in front of reviewers, who are reading
 * that field to judge a candidate.
 *
 * Downstream redistribution should carry this attribution forward.
 */
export const {P}_SOURCE_LICENSING: readonly (readonly [string, string, string, string])[] = [
{chr(10).join("  [" + ", ".join(ts_string(x) for x in v) + "]," for v in licensing_rows)}
];
''')
        if authority_rows:
            out.write(f'''
/**
 * SOURCE AUTHORITY, one row per source family: [sourceFamily, authority]
 *
 * The source family is the machine key an attestation carries; this names the
 * body behind it in the words the dataset used. Constant per family (the
 * generator asserts it), so it is stored once per family rather than
 * {len(attestations)} times. An audit path that wants to print "why does DocScrub
 * say this is {pack["noun"]}" resolves it here.
 */
export const {P}_SOURCE_AUTHORITIES: readonly (readonly [string, string])[] = [
{chr(10).join("  [" + ", ".join(ts_string(x) for x in v) + "]," for v in authority_rows)}
];
''')
        if constant_value is not None:
            out.write(f'''
/**
 * The `{constant_column}` every row in this pack carries -- asserted
 * single-valued at generation. A pack-level constant rather than a row
 * column, because storing one value {len(attestations)} times would have meant
 * widening `DomainReferencePackAsset` and regenerating every other pack's
 * asset to carry a field that does not vary.
 *
 * IF A LATER VERSION OF THIS DATASET VARIES IT, the generator stops. That is
 * deliberate: the conversion to a row column is a shared-contract change and
 * should be a decision, not a silent widening.
 */
export const {P}_{constant_column.upper()} = {ts_string(constant_value)};
''')
        out.write(f'''
/** The pack asset. Consumed by {pack["consumer"]}.ts,
 *  which owns this pack's normalization policy and its evidence contract. */
export const {P}_PACK: DomainReferencePackAsset = {{
  source: {P}_SOURCE,
  rowCount: {P}_ROW_COUNT,
  termCount: {P}_TERM_COUNT,
  rows: ROWS,
  hintSets: HINT_SETS,
  subDomains: SUB_DOMAINS,
  sources: SOURCES,
  strings: STRINGS,
}};
''')

    size = out_path.stat().st_size
    print(f"wrote {out_path.relative_to(ROOT)} ({size / 1024:.0f} KiB)")
    print(f"  csv rows={len(source_rows)}  attestations={len(attestations)}  keys={len(keys)}  "
          f"multi-provenance={multi}  derived={derived_count}")
    print(f"  interned: hintSets={len(hint_sets)} subDomains={len(sub_domains)} "
          f"sources={len(sources)} strings={len(strings)}")
    print(f"  collision risk: " + "  ".join(f"{k}={risk_counts[k]}" for k in risks))
    if domain_counts:
        print(f"  sub-domains: " + "  ".join(f"{k}={v}" for k, v in sorted(domain_counts.items())))
    print(f"  source families: " + "  ".join(f"{k}={v}" for k, v in sorted(family_counts.items())))
    print(f"  normalization parity: {len(source_rows)}/{len(source_rows)} rows reproduce normalized_term")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    main(sys.argv[1], sys.argv[2])
